- src/components/Button/Button-test.js
- src/components/Button/Button.jsx
- src/components/Link/Link-test.js
> feat: add on mouse down to button

- package-lock.json
- src/components/Search/Search.jsx
- src/components/TextField/InputField-test.js
> fix: autocomplete props

- src/components/Button/Button.jsx
- src/hooks/useMergeRefs-test.js
- src/hooks/useMergeRefs.js
> useMergeRefs hook

- src/components/RadioButton/RadioButton.jsx
- src/components/RadioButton/RadioButton.scss
- src/components/RadioButton/RadioButtonConstants.js
- src/components/RadioButton/__stories__/RadioButtonStoryLine.jsx
- src/components/RadioButton/__stories__/radioButton.stories.js
- src/components/RadioButton/__stories__/radioButton.stories.scss
- src/components/RadioButton/__tests__/__snapshots__/radioButton.jest.js.snap
- src/components/RadioButton/__tests__/radioButton.jest.js
- src/components/index.js
- src/published-components.js
Description: Added new RadioButton component
> added RadioButton component

- src/components/Label/Label.scss
> Fix inverted color on label

- .storybook/addons.js
- .storybook/main.js
- package-lock.json
- package.json
- plop/component/component-stories-js.txt
- src/components/AttentionBox/__stories__/attentionBox.stories.js
- src/components/Button/__stories__/button.stories.js
- src/components/Checkbox/__stories__/checkbox.stories.js
- src/components/Counter/__stories__/counter.stories.js
- src/components/DialogContentContainer/__stories__/dialogContentContainer.stories.js
- src/components/Divider/__stories__/divider.stories.js
- src/components/FormattedNumber/__stories__/formattedNumber.stories.js
- src/components/Icon/__stories__/icon.stories.js
- src/components/Label/__stories__/label.stories.js
- src/components/Link/__stories__/link.stories.js
- src/components/Loader/__stories__/loader.stories.js
- src/components/Menu/Menu/__stories__/menu.stories.js
- src/components/Menu/MenuItem/__stories__/menuItem.stories.js
- src/components/Menu/MenuTitle/__stories__/menuTitle.stories.js
- src/components/MenuButton/__stories__/menuButton.stories.js
- src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.js
- src/components/RadioButton/__stories__/radioButton.stories.js
- src/components/Search/__stories__/search.stories.js
- src/components/SplitButton/__stories__/splitButton.stories.js
- src/components/TextField/__stories__/textField.stories.js
- src/components/Tooltip/__stories__/tooltip.stories.js
- src/hooks/useDebounceEvent.js
> feat: add performance to all stories and plop

- src/components/Dropdown/Dropdown.jsx
Description: 
Editing Dropdown Component
Adding value prop to Dropdown for setting value from a server (for example)
> add value to drop down

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/DropdownConstants.js
> feat: add customStyles and menuPortalTarget props support

- src/components/Menu/MenuItem/MenuItem.jsx
- src/components/Menu/MenuItem/MenuItem.scss
- src/components/Menu/MenuItem/__stories__/menuItem.stories.js
- src/hooks/useForceUpdate.js
- src/hooks/useIsMouseOver.js
- src/hooks/useIsOverflowing.js
- src/hooks/usePopover.js
Add menu ellipsis
Add sub menu icon
Add sub sub menu story
Improve usePopover performance
> menu item ellipsis

- src/components/MultiStepIndicator/MultiStepIndicator.jsx
- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
Description: Fixed minor issues with the MultiStepIndicator component - 
- Passed step icon props (previously accepted and documented, but unpassed) to `StepIndicator` from `MultiStepIndicator`.
- Centered the number/icon within the step icon.
- Fixed visibility issue in dark mode for active/fulfilled steps.
Resulting display:
> Fixed minor issues with MultiStepIndicator

- src/hooks/useResizeObserver.js
> feat: support in ff and safari

- src/components/Dropdown/Dropdown.jsx
Added onBlur callback to Dropdown Component
> Added onBlur callback to Dropdown Component

- package-lock.json
- src/components/EditableHeading/EditableHeading.jsx
- src/components/EditableHeading/__stories__/editableHeading.stories.js
- src/components/EditableInput/EditableInput.scss
- src/components/EditableInput/__stories__/editableInput.stories.js
- src/components/Heading/Heading.jsx
- src/components/Heading/Heading.scss
- src/components/Heading/__stories__/heading.stories.js
- src/components/Toast/Toast.jsx
- src/styles/typography.scss
> Heading component continue

- src/components/EditableHeading/EditableHeading.scss
- src/components/EditableHeading/__stories__/editableHeading.stories.js
- src/components/EditableInput/EditableInput.scss
- src/components/Heading/Heading.scss
- src/styles/typography.scss
Heading Border radius and minor fixes
> Heading fixes

- src/styles/typography.scss
> Heading fixes - line height

- src/components/Menu/Menu/Menu.jsx
- src/components/Menu/MenuItem/MenuItem.jsx
- src/components/Menu/MenuItem/MenuItem.scss
- src/components/MenuButton/MenuButton.jsx
Support menu item label
Render empty div for falsy menu button
> Allow to auto focus on specific option in the menu

- src/components/MenuButton/MenuButton.jsx
- src/components/MenuButton/MenuButton.scss
- src/components/MenuButton/__stories__/menuButton.stories.js
Added "disabled" support for the menu button.
> disabled button support for menu button

- src/components/DialogContentContainer/DialogContentContainer.scss
- src/components/Menu/Menu/Menu.jsx
- src/components/Menu/MenuDevider/MenuDevider.jsx
- src/components/Menu/MenuDevider/MenuDevider.scss
- src/components/Menu/MenuItem/MenuItem.jsx
- src/components/Menu/MenuItem/__stories__/menuItem.stories.js
- src/components/Menu/MenuTitle/MenuTitle.jsx
- src/components/Menu/MenuTitle/MenuTitle.scss
allow only whitelist of elements inside menu
menu style improvements
> menu style improvements

- package.json
- src/components/Menu/Menu/__stories__/menu.stories.js
- src/components/Menu/MenuDevider/__stories__/menuDevider.stories.js
- src/components/Menu/MenuItem/__stories__/menuItem.stories.js
- src/components/Menu/MenuTitle/__stories__/menuTitle.stories.js
> release menu

- package-lock.json
- package.json
- src/hooks/useKeyEvent.js
fix default ref on document in key event listener
> fix default ref on document in key event listener

- package.json
- src/components/Divider/Divider.scss
- src/components/Menu/Menu/Menu.jsx
- src/components/Menu/Menu/hooks/useCloseMenuOnKeyEvent.jsx
- src/components/Menu/Menu/hooks/useMenuKeyboardNavigation.jsx
- src/components/Menu/Menu/hooks/useOnCloseMenu.jsx
- src/components/Menu/MenuItem/MenuItem.jsx
- src/components/Menu/MenuItem/__stories__/menuItem.stories.js
- src/components/Menu/MenuItem/hooks/useMenuItemKeyboardEvents.js
> menu improvements

- package.json
> bump version to 0.0.99

- src/components/EditableHeading/EditableHeading.jsx
- src/components/Heading/Heading.jsx
> Fix size prop

- webpack.config.js
Fix Webpack compile - to support Server Side Rendering component
> Update webpack config - fix ssr 

- package.json
- src/components/Search/Search.jsx
- src/components/TextField/TextField.jsx
> Added a11y params

- package.json
- src/components/EditableHeading/EditableHeading.jsx
- src/components/EditableHeading/__stories__/editableHeading.stories.js
- src/components/EditableInput/EditableInput.jsx
- src/components/EditableInput/__stories__/editableInput.stories.js
- src/components/EditableInput/__tests__/__snapshots__/editableInput.jest.js.snap
- src/components/EditableInput/__tests__/editableInput.jest.js
Description: add aria-label prop to both editable-heading and editable-input
> #inc add aria-label to editable-heading & editable-input

- package.json
- src/components/ButtonGroup/ButtonGroup.jsx
- src/components/ButtonGroup/ButtonGroup.scss
- src/components/ButtonGroup/ButtonGroupConstants.js
- src/components/ButtonGroup/__stories__/buttonGroup.stories.js
> Button Group component

- .babelrc
- package.json
> Revert ie remove

- package.json
- src/components/Menu/Menu/Menu.jsx
Description: **Added an option to pass focusItemIndexOnMount to the menu component**
> add option to auto focus specific menu item

- package.json
> Remove IE support

- package.json
> bump version to 0.3.14

- src/components/ButtonGroup/ButtonGroup.jsx
- src/components/ButtonGroup/ButtonWrapper.jsx
- src/components/ButtonGroup/__stories__/buttonGroup.stories.js
Description: add support on toolbars above/under button group toolbar
- [v ] PR has description
- [v ] Changes to the component are backward compatible (including selectors structure). If not - add to the title of the PR "BREAKABLE_CHANGE""
- [v ] All the changes to the component should be reflected in the Storybook.
- [ v] Component passed Accessibility Plugin checks
group button component does not have tests at the moment
> feat: button group toolbar

- package.json
- src/components/AlertBanner/__tests__/__snapshots__/AlertBanner.jest.js.snap
- src/components/AttentionBox/__tests__/__snapshots__/attentionBox.jest.js.snap
- src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/breadcrumbItem.jest.js.snap
- src/components/BreadcrumbsBar/__tests__/__snapshots__/breadcrumbsBar.jest.js.snap
- src/components/Chips/Chips.jsx
- src/components/Chips/Chips.scss
- src/components/Chips/__stories__/chips.stories.js
- src/components/Chips/__stories__/chips.stories.scss
- src/components/Chips/__tests__/__snapshots__/chips.jest.js.snap
- src/components/Chips/__tests__/chips.jest.js
- src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
- src/components/ExpandCollapse/__tests__/__snapshots__/expandCollapse.jest.js.snap
- src/components/Heading/__tests__/__snapshots__/heading.jest.js.snap
- src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem.jest.js.snap
- src/components/Menu/MenuItemButton/__tests__/__snapshots__/menuItemButton.jest.js.snap
- src/components/MenuButton/__tests__/__snapshots__/menuButton.jest.js.snap
- src/components/MultiStepIndicator/__tests__/__snapshots__/multiStepIndicator.jest.js.snap
- src/components/SplitButton/__tests__/__snapshots__/splitButton.jest.js.snap
- src/components/index.js
- src/general-stories/colors/colors-vars-map.js
- src/published-components.js
- src/styles/typography.scss
- src/utils/function-utils.js
> Add chips component

- src/components/SplitButton/SplitButton.scss
solves this https://github.com/mondaycom/monday-ui-react-core/issues/133
> fix split button bug on safari

- package.json
- src/components/AlertBanner/AlertBanner.jsx
- src/components/AlertBanner/__stories__/AlertBanner.stories.js
- src/components/AlertBanner/__tests__/AlertBanner.jest.js
- src/components/AlertBanner/__tests__/__snapshots__/AlertBanner.jest.js.snap
Description: add support for hide the close button on alert banner
- [ V] PR has description
- [ V] Changes to the component are backward compatible (including selectors structure). If not - add to the title of the PR "BREAKABLE_CHANGE""
- [ V] All the changes to the component should be reflected in the Storybook.
- [ V] Component passed Accessibility Plugin checks
- [ V] All current tests are passing
- [ V] New functionality is covered with tests
- [ V] Tests are compliant with TESTING_README.md instructions
> feature: support hide close button on banner

- package.json
- src/components/Checkbox/Checkbox.js
1. fix bug on checkbox focus
https://user-images.githubusercontent.com/72390374/123946450-e6cea400-d9a7-11eb-84cb-00bace26b33c.mov
2. add new prop for checkbox - ariaLabelledBy
> fix checkbox focus & add aria labelled by support

- package.json
- src/components/Combobox/Combobox.jsx
- src/components/Combobox/Combobox.scss
- src/components/Combobox/ComboboxService.js
- src/components/Combobox/__stories__/combobox.stories.js
- src/components/Combobox/__stories__/combobox.stories.scss
- src/components/Combobox/__tests__/__snapshots__/combobox.jest.js.snap
- src/components/Combobox/__tests__/combobox.jest.js
- src/components/Combobox/components/ComboboxCategory/ComboboxCategory.jsx
- src/components/Combobox/components/ComboboxCategory/ComboboxCategory.scss
- src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
- src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
- src/styles/themes.scss
Description: 
Combobox component changes:
1. Adding categories support for the combobox, including categories that are only visible on search
2. Adding props for: option height, background color
3. Adding option props: leftIconType, rightIconType to allow custom rendering of functions
3. Fix screen reader capabilities for combobox (aria-activedecendant was in the wrong place)
4. Added a bunch of knobs to the sandbox and a new page showing the categories usage
5. Fixed the placeholder var color (looks like a copy paste error)
> support categories and custom icons in combobox

- src/components/ResponsiveList/ResponsiveList.jsx
- src/components/ResponsiveList/__stories__/responsiveList.stories.js
Need to override the icon, because we already use the Menu icon inside this menu in our use case, and it makes it confusing to see them twice
> expose menuButtonProps

- package.json
- src/components/Button/Button.jsx
- src/components/Menu/MenuItemButton/MenuItemButton.jsx
> Fix react warnings

- src/components/Combobox/Combobox.jsx
- src/components/Combobox/Combobox.scss
- src/components/Combobox/__stories__/combobox.stories.js
- src/components/Combobox/__stories__/combobox.stories.scss
- src/components/Combobox/__tests__/__snapshots__/combobox.jest.js.snap
- src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
Description: Add scroll support for the combobox component
> Ayelet and orr/combobox scroll

- package.json
- src/components/Avatar/AvatarContent.jsx
- src/components/Icon/CustomSvgIcon.jsx
- src/components/Icon/Icon.jsx
- src/helpers/screenReaderAccessHelper.js
set aria hidden true as default in icons when they are not clickable and false when they are clickable (because most of the time the icons are hidden when not clickable )
> default is hidden on icon

- .github/workflows/npm-publish.yml
> release fix try

- package-lock.json
- package.json
> update: latest monday-ui-style

- package-lock.json
- package.json
> Feat/orr/update monday UI

- .github/workflows/test-workflow.yml
- .github/workflows/update-icons.yml
upgrade monday style automaticlly
> update icons every 10 minutes

- src/components/Banner/__stories__/banner.stories.js
> fix: broken image

- src/components/Counter/Counter.scss
- src/components/Counter/__stories__/counter.stories.js
> fix: roundness of counter

- src/components/TextWithHighlight/TextWithHighlight.jsx
- src/components/TextWithHighlight/TextWithHighlight.scss
- src/components/TextWithHighlight/__stories__/textWithHighlight.stories.js
- src/components/TextWithHighlight/__tests__/__snapshots__/textWithHighlight.jest.js.snap
- src/components/TextWithHighlight/__tests__/textWithHighlight.jest.js
- src/components/index.js
- src/published-components.js
> Text with highlight

- src/components/ColorPicker/ColorPicker.jsx
- src/components/ColorPicker/__stories__/colorPicker.stories.js
- src/components/ColorPicker/__tests__/colorPicker.jest.js
- src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx
- src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
> multiselect color picker

- src/components/ColorPicker/__tests__/__snapshots__/colorPicker.jest.js.snap
- src/components/ColorPicker/__tests__/colorPicker.jest.js
- src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx
- src/general-stories/colors/colors-vars-map.js
- src/published-components.js
Fixes the behavior of whitelist to be intersects (if some of the values does not match the content colors we will take the ones that did)
> BREAKABLE_CHANGE - amitha/fix/color-picker-whitelist

- src/components/Combobox/components/ComboboxCategory/ComboboxCategory.jsx
- src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
- src/components/EditableInput/EditableInput.jsx
> fix: incorrect usage aria labels

- src/components/Checkbox/Checkbox.js
- src/components/Checkbox/Checkbox.scss
- src/components/Checkbox/__stories__/checkbox.stories.js
> feat: add support for indeterminate checkbox

- src/components/MenuButton/MenuButton.jsx
- src/components/MenuButton/__stories__/menuButton.stories.js
> reference classname

- src/components/Dropdown/Dropdown.jsx
> add autoFocus to dropdown

- babel.config.js
- src/components/Combobox/Combobox.jsx
- src/components/Combobox/Combobox.scss
- src/components/Combobox/__stories__/combobox.stories.js
- src/components/Combobox/__tests__/__snapshots__/combobox.jest.js.snap
1. Add sticky categories support
2. Fix search width to match items
> Combobox sticky categories and search width

- src/components/EditableInput/EditableInput.jsx
> editable input focus in animation frame

- src/components/Button/Button.jsx
- src/components/Button/Button.scss
- src/components/Button/__stories__/button.stories.js
Fix issue with button loading on mount (initial state is loading)
> Fix button initial loading state

- src/components/Button/Button.jsx
Description: Added a successIconSize property calculated based on the button size if the icon is a function
> successIconSize property to determine function success icon size

- src/components/Tooltip/Tooltip.jsx
- src/components/Tooltip/__tests__/tooltip.jest.js
Description: Add onTooltipShow/Hide props.
> Tooltip add show/hide events

- .eslintrc.json
> change fixed eslint to error

- .storybook/preview.js
- src/components/Button/__stories__/button.stories.mdx
- src/storybook/components/component-rule/component-rule.jsx
- src/storybook/components/component-rules/component-rules.jsx
- src/storybook/components/index.jsx
- src/storybook/components/link/link.jsx
- src/storybook/components/link/link.scss
- src/storybook/components/styles/typography.scss
- src/storybook/components/usage-guidelines/usage-guidelines.jsx
> add links support to stories

- src/components/Dialog/Dialog.jsx
> fix: callback on mount when should show on mount

- src/hooks/useResizeObserver.js
> fix: safari useReszieObserver

- src/hooks/useForceUpdate.js
After reading [your article](https://medium.com/@moshe_31114/building-our-recycle-list-solution-in-react-17a21a9605a0) on the recycle list, I was browsing through the code and found some typo's.
> Fix typo in useForceUpdate

- .storybook/preview.js
- src/storybook/components/component-rules/component-rules.scss
- src/storybook/components/doc-footer/doc-footer.scss
- src/storybook/components/index.jsx
- src/storybook/components/information-box/information-box.scss
- src/storybook/components/link/link.scss
- src/storybook/components/paragraph/paragraph.jsx
- src/storybook/components/paragraph/paragraph.scss
- src/storybook/components/related-component/related-component.scss
- src/storybook/components/related-components/descriptions/tooltip-description.jsx
- src/storybook/components/related-components/related-components.scss
- src/storybook/components/section-name/section-name.scss
- src/storybook/components/title/title.scss
- src/storybook/components/usage-guidelines/usage-guideline.scss
- src/storybook/stand-alone-documentaion/other-contributors-list/other-contributors-list.jsx
- src/storybook/stand-alone-documentaion/other-contributors-list/other-contributors-list.scss
- src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.scss
- src/storybook/stand-alone-documentaion/welcome/ability-description/ability-description.scss
- src/storybook/stand-alone-documentaion/welcome/contributor/contributor.scss
- src/storybook/stand-alone-documentaion/welcome/principle/principle.scss
- src/storybook/stand-alone-documentaion/welcome/welcome-header/welcome-header.scss
- src/storybook/styles/content-spacing.scss
- src/storybook/styles/typography.scss
+ change spacing in the storybook infra and text size according to rotem notes.
+ fix in contributors container css
> Fix fonts and spacing according to rotem notes

- src/components/index.js
> fix: export Icon component

- src/components/Link/Link.jsx
- src/components/Link/__stories__/link-story.scss
- src/components/Link/__stories__/link.stories.js
In case we use a specific flag, we prevent opening a new tab with the default href flow.
https://user-images.githubusercontent.com/17691874/143771770-0095bc3c-b7cc-4d3e-9da0-33b24ebaa00b.mov
> support onclick without navigation

- src/components/index.js
- src/published-components.js
expose colors-utils so we could use storybook colors in monday repo
> expose colors-utils

- src/published-components.js
> Fix bug on color utils 

- src/components/index.js
> quick fix in the index of color utils

- src/components/VirtualizedList/VirtualizedList.jsx
> added classname to the virtualized list where scrollbars appears

- package.json
Add `sideEffects` to enable tree-shaking in the library.
> Tree-shake the library

- package-lock.json
- scripts/release.js
- src/components/ButtonGroup/ButtonGroup.jsx
- src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.js
- src/components/Link/Link.jsx
- src/components/Link/__tests__/__snapshots__/link-snapshot-tests.jest.js.snap
- src/components/Link/__tests__/link-snapshot-tests.jest.js
- src/components/RadioButton/RadioButton.jsx
- src/components/Toggle/__tests__/toggle-snapshot-tests.jest.js
change className props to consist naming #417
> change className props to consist naming

- src/components/VirtualizedList/VirtualizedList.jsx
- src/components/VirtualizedList/virtualized-list-service.js
Fix issue with virtualized list not reporting scrollbar visible correctly on init
> Fix virtualized list scrollbar visible issue

- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/Combobox/__tests__/combobox-tests.jest.js
> Fix combobox and dropdown docs

- src/components/Menu/MenuItem/MenuItem.jsx
> check that element is there

- src/components/Checkbox/__stories__/checkbox.stories.mdx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/Combobox/__stories__/combobox.stories.scss
- src/components/Divider/__stories__/Divider.stories.mdx
- src/components/Divider/__stories__/Divider.stories.module.scss
- src/components/IconButton/__stories__/IconButton.stories.mdx
- src/components/Menu/MenuDivider/__stories__/MenuDivider.stories.mdx
- src/components/RadioButton/__stories__/radioButton.stories.mdx
- src/components/SplitButton/__stories__/SplitButtonExampleDialog.jsx
- src/components/SplitButton/__stories__/splitButton.stories.mdx
- src/components/SplitButton/__stories__/splitButton.stories.scss
- src/storybook/components/related-components/descriptions/button-group-description.jsx
- src/storybook/components/related-components/descriptions/menu-description.jsx
> random story fixes

- src/components/Heading/__stories__/Heading.stories.mdx
- src/components/ListItem/__stories__/ListItem.stories.mdx
- src/components/RadioButton/RadioButton.jsx
- src/components/Tipseen/__stories__/tipseen.stories.jsx
- src/components/Tipseen/__stories__/tipseen.stories.mdx
- src/components/Tooltip/__stories__/tooltip.stories.mdx
- src/storybook/functions/create-component-story.js
- src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.jsx
> Fix stories errors and typos   

- src/components/EditableHeading/EditableHeading.jsx
Use clickable instead of useButton for editableHeading
> use button to clickable

- src/components/Dialog/Dialog.jsx
Allow dialog hideTriggerIgnoreClass prop to receive array
> Fix dialog hideTriggerIgnoreClass prop type to accept array

- webpack/published-components.js
> Fix icon button export

- src/components/Tabs/Tab/Tab.scss
- src/components/Tabs/TabList/TabList.jsx
- src/components/Tabs/TabPanel/TabPanel.jsx
- src/components/Tabs/TabPanels/TabPanels.jsx
- src/components/Tabs/TabPanels/__tests__/__snapshots__/tabPanels-snapshot-tests.jest.js.snap
- src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
Add a prop to allow rendering only the active tabs and not all of them
> Fix tabs rendering non active tabs

- src/components/EditableHeading/EditableHeading.jsx
- src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
- src/components/EditableHeading/__tests__/editableHeading.jest.js
- src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
[Task](https://monday.monday.com/boards/245345663/views/39363783/pulses/2181666993)
Fixed by applying @MosheZemah's  [suggestion](https://monday.slack.com/archives/C026UHQ8E92/p1642589755079800) :)
> Focus on editing editable header

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/__stories__/dropdown.stories.mdx
> feat: added 'onInputChange' property to Dropdown

- src/components/SplitButton/SplitButton.jsx
- src/components/SplitButton/__stories__/splitButton.stories.mdx
> Minor fixes in split button story

- src/components/ColorPicker/__stories__/ColorPicker.stories.js
- src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
Added missing story for ColorPicker shape prop
> Story for ColorPicker shape prop

- src/components/Slider/Slider.scss
- according to feedback from UI/UX
> fix(slider): change broken padding for slider prefix

- src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
- src/hooks/useGridKeyboardNavigation/__tests__/gridKeyboardNavigationHelper.jest.js
- src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
- src/hooks/useGridKeyboardNavigation/gridKeyboardNavigationHelper.js
- src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
[Task](https://monday.monday.com/boards/245345663/pulses/2205952071)
> Disabled indexes for keyboard nav

- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
- src/components/Dropdown/components/ValueContainer/ValueContainer.module.scss
1. Controlling the margin left when placeholder is/not present
2. Showing placeholder when no options selected and no input value is present
> Dropdown with multi - placeholder show condition fix

- src/components/AttentionBox/AttentionBox.scss
- src/components/Avatar/AvatarContent.scss
- src/components/Button/Button.scss
- src/components/FieldLabel/FieldLabel.scss
- src/components/FormattedNumber/FormattedNumber.scss
- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
- src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
- src/components/TextField/TextField.scss
- src/components/storybook-helpers/description-label/description-label.scss
- src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
- src/storybook/styles/typography.scss
- src/styles/typography.scss
Reverts mondaycom/monday-ui-react-core#482
> Revert " Add typography variables"

- src/components/VirtualizedList/VirtualizedList.jsx
- src/services/virtualized-service.js
Add virtualized list ref prop (ref to the react-window list)
> Add virtualized list ref

- src/components/Chips/Chips.jsx
- src/components/Chips/Chips.scss
- src/components/Chips/__stories__/chips.stories.mdx
> Add chips colors story

- src/components/Chips/__stories__/chips.stories.mdx
- src/components/Flex/Flex.jsx
- src/components/Flex/Flex.module.scss
- src/constants/positions.js
> Add chips colors story fixes

- .storybook/preview-head.html
> Fix font load

- package-lock.json
- package.json
- src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
- src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
- src/components/TextField/TextField.jsx
- src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
> remove react button

- src/components/Switch/hooks/useSwitchChecked.jsx
- src/components/Toggle/__tests__/toggle-tests.jest.js
> Fix toggle on change params

- src/components/Combobox/Combobox.jsx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/Combobox/__tests__/combobox-tests.jest.js
https://user-images.githubusercontent.com/25403067/154848317-33f3e5ff-4b30-4c03-9c5a-b2703ffa6630.mov
> combobox disable no result on loading

- src/components/Avatar/Avatar.jsx
- src/components/Avatar/Avatar.scss
- src/components/Avatar/AvatarBadge.scss
- src/components/Avatar/AvatarConstants.jsx
- src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.js.snap
- src/components/Chips/Chips.jsx
- src/components/Chips/Chips.scss
- src/components/Chips/__stories__/chips.stories.mdx
- src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
- src/components/Chips/__tests__/chips-snapshot-tests.jest.js
https://www.figma.com/file/V6mW7QxiNQgEpbBIRRzZLm/Chips?node-id=0%3A1
> Add support on avatar in chip component

- src/components/EditableHeading/EditableHeading.jsx
- src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
- src/components/Heading/Heading.jsx
- src/components/Heading/__stories__/Heading.stories.mdx
- src/components/TextWithHighlight/TextWithHighlight.jsx
- src/components/TextWithHighlight/TextWithHighlight.scss
- src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
- src/components/TextWithHighlight/__tests__/__snapshots__/textWithHighlight.jest.js.snap
Add highlight text support for Heading and Editable Heading
> Support Heading highlight text

- src/components/EditableHeading/EditableHeading.jsx
- src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
- src/components/EditableInput/EditableInput.jsx
- src/components/Heading/Heading.jsx
- src/hooks/useStyle.js
> Add color prop to Heading and Editable Heading

- src/components/EditableHeading/EditableHeading.jsx
- src/components/EditableInput/EditableInput.jsx
Callback for editable heading on blur ignore
> Editable heading callback on blur ignore

- src/components/Combobox/Combobox.jsx
Option to clear filter value on selection
> Clear filter on combobox selection

- src/components/Combobox/__stories__/combobox.stories.mdx
> Fix issue with combobox story

- src/__tests__/interactions-helper.js
- src/components/Menu/Menu/__stories__/Menu.stories.mdx
- src/components/Menu/Menu/__stories__/interactions.js
- src/components/Menu/Menu/__stories__/menu.stories.js
> Add menu tests

- src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
- src/components/GridKeyboardNavigationContext/__tests__/GridKeyboardNavigationContext.jest.js
- src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
- src/components/GridKeyboardNavigationContext/helper.js
- src/components/Menu/Menu/Menu.jsx
- src/components/Menu/Menu/hooks/__tests__/useLastNavigationDirection.jest.js
- src/components/Menu/Menu/hooks/useLastNavigationDirection.jsx
- src/components/Menu/MenuGridItem/__tests__/useFocusGridItemByActiveStatus.jest.js
- src/components/Menu/MenuGridItem/useFocusGridItemByActiveStatus.jsx
- src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
- src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js
> Fix menu grid item focus after keyboard nav

- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/Combobox/components/ComboboxRenderers/ComboboxRenderers.module.scss
https://user-images.githubusercontent.com/72390374/159163299-8847c632-00cb-43f0-9f0a-ed3a97842d79.mov
https://user-images.githubusercontent.com/72390374/159164156-e21ad52b-1acb-464e-970f-d109e15e73c3.mov
> fix dark mode issue, sticky issue and add categories story

- src/components/Slider/__tests__/Slider.interactions.js
- minor refactoring of prev tests
(change name and add some comments)
- add simple Thumbs drag interaction tests for Ranged Slider
- add Cross Start/End Thumbs tests
> test(slider): add Thumbs drag interaction tests for Ranged Slider

- src/components/Avatar/Avatar.jsx
Avatar - add custom background color prop
> Avatar custom background color

- src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
- src/components/Accordion/Accordion/__tests__/accordion.interactions.js
Add interaction tests for multi-active mode
- add interactions tests
- connect tests to storybook
Minor refactoring 
- improve interaction tests of single active
- split to helper/check functions
> test(accordion): add interaction tests for multi-active mode

- src/components/Combobox/Combobox.jsx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
- src/components/VirtualizedList/VirtualizedList.jsx
Add a new prop to combobox to limit numbers of visible options without scroll
> Combobox max options without scroll

- src/components/IconButton/IconButton.jsx
- src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
https://monday.monday.com/boards/245345663/pulses/2483483697
> # 💄 Change Icon Button Small variant shape size to 24px.

- src/components/Button/Button.jsx
https://monday.monday.com/boards/1812339248/pulses/2521169505
> fix icon size for small button

- src/components/Checkbox/Checkbox.js
> Fix bug: support press shift while click on checkbox on firefox browsers

- src/components/Chips/Chips.jsx
- src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
- src/components/List/VirtualizedListItems/VirtualizedListItems.jsx
> Undo "component" absolute path because it increase bundle size

- src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
> fix commit

- src/components/Checkbox/Checkbox.js
> Fix usage on useMergedRef in checkbox

- webpack/published-components.js
> Fix export of a11y list hook

- src/components/Combobox/components/ComboboxOption/ComboboxOption.scss
> Fix combobox with categories focus (css) bug

- src/components/Combobox/Combobox.jsx
> Update combobox docs 

- src/components/Combobox/Combobox.jsx
> Fix bug: remove "add new" button from not found empty state in combobox as default

- webpack/published-components.js
> fix use previous export

- package-lock.json
- package.json
https://monday.monday.com/boards/245345663/pulses/2800021581
* Feature: Stylelint
* Feature: shadow-xs
> * Update version "monday-ui-style": "0.1.118",

- src/components/RadioButton/RadioButton.jsx
- Added new prop - `retainChildClick`
> Fix: Add prop to preserve radio button on select behaviour with children

- src/components/Avatar/Avatar.jsx
- src/components/Avatar/Avatar.scss
- src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.js.snap
- src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
- src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap
Avatar size can be customized by passing className with height and width attributes
> Avatar custom size by classname

- jest.config.js
- package-lock.json
- package.json
- src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
- src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/components/Flex/__tests__/__snapshots__/flex-snapshot-tests.jest.js.snap
- src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
- src/components/Loader/__tests__/__snapshots__/loader-snapshots.jest.js.snap
- src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
- src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
- src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
This PR fix an issue with snapshot tests, where css-modules classes didn't show on the snapshots
> Jest snapshot css modules

- .storybook/preview.js
https://storybook.js.org/addons/storybook-addon-performance
> feat(storybook): enable storybook performance addon

- .storybook/main.js
- .storybook/preview.js
- package-lock.json
- package.json
- src/storybook/decorators/memory-stats.jsx
- src/storybook/functions/memory-stats/index.js
- src/storybook/functions/memory-stats/memory-stats-lib.js
- src/storybook/index.js
- add dependency storybook/addon-toolbars 
- add memory stats component (on base of https://github.com/paulirish/memory-stats.js)
- add memory stats decorator
- use memory-stats decorator 
- add to switcher to toolbar
> feat(storybook): memory stats for stories

- src/components/EditableHeading/EditableHeading.jsx
> add max length as a prop

- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
- src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
> adding leftIcon and leftAvatar to dropdown chips

- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- webpack/published-components.js
Avatar group added to published-components
> AvatarGroup component export

- src/components/IconButton/IconButton.jsx
- src/components/Link/Link.jsx
- src/components/Link/Link.scss
- src/components/Link/__stories__/Link.stories.mdx
- src/components/TextWithHighlight/TextWithHighlight.jsx
> Icon button fix and link alignment

- src/storybook/components/component-rule/component-rule.scss
- src/storybook/components/component-rules/component-rules.scss
- src/storybook/components/related-components/related-components.scss
- src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-example/shadow-example.scss
- src/storybook/stand-alone-documentaion/shadow/shadow-levels/shadow-levels.scss
- src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-component/spacing-component.scss
- src/storybook/stand-alone-documentaion/spacing/spacing-sizes/spacing-sizes.scss
- src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.scss
- src/storybook/stand-alone-documentaion/welcome/contributors/contributors.scss
- src/storybook/stand-alone-documentaion/welcome/principles/principles.scss
- src/styles/global-css-settings.scss
https://monday.monday.com/boards/2861766393/pulses/2940038376
> Feature/yonatan ari/storybook repsoinsive tweaks

- src/components/List/List.jsx
- src/components/List/__tests__/__snapshots__/list.jest.js.snap
- src/components/ListItem/ListItem.jsx
- src/components/ListItem/__tests__/__snapshots__/listItem.jest.js.snap
- src/components/ListTitle/ListTitle.jsx
- src/constants/KeyCodes.js
> Navigate in list with keyboard.

- src/hooks/useActiveDescendantListFocus/index.js
- src/hooks/useActiveDescendantListFocus/useActiveDescendantListFocusHooks.js
https://monday.monday.com/boards/245345663/pulses/2983087880
> removed hooks alias usage

- src/components/ExpandCollapse/ExpandCollapse.scss
https://monday.monday.com/boards/2861766393/pulses/2983776777
> Use motion tokens on ExpandCollapse.scss

- src/components/Checkbox/Checkbox.scss
https://monday.monday.com/boards/2861766393/pulses/2984099495
> Use motion tokens on Checkbox.scss

- src/components/Dropdown/Dropdown.scss
- src/components/Dropdown/components/menu/menu.scss
https://monday.monday.com/boards/2861766393/pulses/2990113012
> Use motion tokens on Dropdown.scss and dropdown/menu.scss

- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
https://monday.monday.com/boards/2861766393/pulses/2991338979
> Use motion tokens on StepIndicator.scss

- src/components/Chips/Chips.module.scss
https://monday.monday.com/boards/2861766393/pulses/2984523895
> Use motion tokens on Chips.module.scss

- src/components/EditableInput/EditableInput.jsx
- src/components/Heading/Heading.jsx
https://monday.monday.com/boards/2861766393/pulses/3015744283
> Fix h1 style gaps in Editable heading edit mode.

- src/components/Skeleton/Skeleton.scss
https://monday.monday.com/boards/2861766393/pulses/3016734446
> Use motion tokens on Skeleton.scss

- src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
https://monday.monday.com/boards/2861766393/pulses/2991430194
> Use motion tokens on LinearProgressBar.scss

- src/components/Tabs/Tab/Tab.scss
https://monday.monday.com/boards/2861766393/pulses/3015940349
> Use motion tokens on Tab.scss

- src/components/Label/Label.scss
https://monday.monday.com/boards/2861766393/pulses/2990443694
> Use motion tokens on Label.scss

- src/components/Tabs/TabPanels/TabPanels.scss
https://monday.monday.com/boards/2861766393/pulses/3016636700
> Use motion tokens on TabPanels.scss

- src/components/Toggle/Toggle.scss
https://monday.monday.com/boards/2861766393/pulses/3016305038
> Use motion tokens on Toggle.scss

- src/components/TextField/TextField.scss
https://monday.monday.com/boards/2861766393/pulses/3016064926
> Use motion tokens on TextField.scss

- src/components/Steps/Steps.scss
https://monday.monday.com/boards/2861766393/pulses/3012776294
> Use motion tokens on Steps.scss

- src/components/SplitButton/SplitButton.scss
https://monday.monday.com/boards/2861766393/pulses/3012765500
> Use motion tokens on SplitButton.scss

- src/components/Slider/SliderBase/SliderBase.scss
https://monday.monday.com/boards/2861766393/pulses/3012749866
> Use motion tokens on SliderBase.scss

- src/hooks/useActiveDescendantListFocus/index.js
> remove console.log

- src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.js
- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.jsx
https://monday.monday.com/boards/2861766393/pulses/2994796616
> Fix useKeyEvent imports

- src/components/Avatar/Avatar.jsx
https://monday.monday.com/boards/2861766393/pulses/2939479593
> Avatar: prevent default (scroll) on click via space

- src/components/Checkbox/Checkbox.scss
https://monday.monday.com/boards/2861766393/pulses/3086832055
* Add cursor not-allowed to checkbox
* Add cursor not-allowed to label
> Add Cursor not-allowed to disabled checkbox

- src/components/Button/Button.jsx
- src/components/Button/Button.scss
- src/components/Button/ButtonConstants.js
- src/components/IconButton/IconButton.jsx
- src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.js.snap
> Fix icon button size

- src/components/Box/__stories__/Box.stories.mdx
https://monday.monday.com/boards/2861766393/pulses/3086864423
> Add missing prop bind: marginBottom in Box story

- src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx
https://monday.monday.com/boards/2861766393/pulses/3107263860
> Update h1 example to Poppins

- src/components/Tooltip/Tooltip.jsx
> add support on pass class name to reference in tooltip

- src/components/IconButton/IconButton.jsx
https://monday.monday.com/boards/2861766393/pulses/3118525928
Tried to search for such use cases to keep consistent, but haven't found anything like it - @hadasfa if u know that it has a different name somewhere, pls tell me:)
> IconButton: add showTooltip prop

- src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.jsx
https://monday.monday.com/boards/2861766393/pulses/3118779705
> BreadcrumbContent: link and button roles are added

- src/utils/colors-utils.js
Exporting content colors vars names
> Export content color

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/Dropdown.styles.js
- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/Dropdown/components/menu/menu.jsx
- src/components/Dropdown/components/menu/menu.scss
> add support for menus inside a container which using transform function

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
- src/components/Dropdown/components/ValueContainer/ValueContainer.jsx
- src/components/Dropdown/dropdown-constants.js
Added the option to determine the color of the chips in dropdown with multi.
Added story + snapshot test for the case.
> Chip colors in dropdown with multi support

- src/components/Dropdown/dropdown-constants.js
Changed import of Chips to relative import to fix issue in version 1.62.0
> Fixing Chips import by changing to relative import

- src/components/AttentionBox/AttentionBox.jsx
https://monday.monday.com/boards/470024321/pulses/3239747416
> fix icon types import

- TYPESCRIPT_MIGRATION.md
> add readme for typescript migration process

- src/components/ListItem/ListItem.jsx
https://monday.monday.com/boards/2989954551/pulses/3238969539
> add on hover to list item

- src/components/List/VirtualizedListItems/VirtualizedListItems.jsx
- src/components/ListItem/ListItem.jsx
- src/components/ListItem/__tests__/__snapshots__/listItem.jest.js.snap
- src/components/ListTitle/ListTitle.jsx
> Fix for virtualized list items

- src/components/List/VirtualizedListItems/VirtualizedListItems.jsx
- src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
- src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
> Fix Virtualized list items

- src/components/Tooltip/Tooltip.scss
https://monday.monday.com/boards/2861766393/pulses/3270960235
> Tooltip: increase specifity of monday-style-arrow-${theme} classes

- src/styles/_keyframes.scss
https://monday.monday.com/boards/2861766393/pulses/3260921059
> fix import path from absolute to relative.

- src/components/ModalHeader/ModalHeader.module.scss
Fix `align-items: start` compatibility issue
> fix css issue

- src/components/Divider/Divider.tsx
- src/components/Divider/DividerConstants.js
- src/components/Divider/DividerConstants.ts
- src/components/Divider/__stories__/Divider.stories.mdx
- src/components/Divider/__tests__/divider.jest.tsx
Convert `Divider` in TypeScript.
Closes #896
> refactor: migrate Divider in typescript

- src/components/Modal/Modal.module.scss
- src/components/ModalHeader/ModalHeader.module.scss
https://monday.monday.com/boards/245345663/views/62248892/pulses/3356926427
> modal css fixes

- src/components/AttentionBox/AttentionBox.tsx
- src/components/AttentionBox/AttentionBoxConstants.ts
- src/components/AttentionBox/__stories__/attentionBox.stories.mdx
- src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
- src/components/AttentionBox/__tests__/attentionBox-snapshot-tests.jest.tsx
- webpack/published-js-components.js
- webpack/published-ts-components.js
> Fix attention box migration to ts

- src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.tsx.snap
- src/components/AvatarGroup/__tests__/__snapshots__/avatarGroup-snapshot-tests.jest.js.snap
- src/utils/colors-vars-map.ts
https://monday.monday.com/boards/2861766393/pulses/3413096663
> For "getElementColor" function return, add missing ')'.

- TYPESCRIPT_MIGRATION.md
> Add docs about change publish component files for every ts migration update

- src/components/Accordion/Accordion/Accordion.tsx
- src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
- src/components/Accordion/AccordionItem/AccordionItem.tsx
Refactoring after external PR https://github.com/mondaycom/monday-ui-react-core/commit/bfd519a1f20d3a818b6fb5a4ed6f0c472eebc62f
> Accordion: ts-migration - refactoring

- src/components/DatePicker/DatePicker.tsx
- src/components/DatePicker/__tests__/DatePicker.jest.tsx
> Fix DatePicker tests + refactor

- webpack/published-js-components.js
- webpack/published-ts-components.js
> fix accordion publish

- src/components/Tipseen/Tipseen.jsx
- src/components/Tooltip/Tooltip.tsx
added a "tip" property to the Tipseen component
> tipseen tip prop

- README.md
hello. I found a typo while reading Readmd.md and fixed it.
> fix typo correction

- src/components/Box/__stories__/Box.stories.mdx
> Fix storybook box overview code

- webpack.config.js
> add source maps

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/components/Dropdown/__tests__/driver.js
- src/components/Dropdown/__tests__/dropdown-snapshot-tests.jest.js
- src/components/Dropdown/components/Control/Control.jsx
> dropdown component tooltip

- package-lock.json
- package.json
* Update: team icon shape change.
https://monday.monday.com/boards/3532714909/pulses/3551037199
> Bump monday-ui-styles version to "0.1.144": team icon

- src/components/TextField/TextField.tsx
want to skip tab on textField
so passing a param to -1 its tab index
> support tab index for text field

- src/components/SplitButton/SplitButton.tsx
https://monday.monday.com/boards/3532714909/pulses/3563804766
> SplitButton temp fix - secondary button no click event

- src/components/Heading/Heading.scss
Remove letter spacing from non h1 headers
> fix letter spacing in non h1 headers

- src/components/Button/Button.tsx
- src/components/Icon/__tests__/all-icons-tests.jest.ts
- src/components/Slider/SelectionIndicator.tsx
- src/components/TextField/TextField.tsx
- src/helpers/key-of.ts
- src/types/ArrayLastElement.ts
- src/types/SplitString.ts
- src/utils/user-agent-utils.ts
- types/window.d.ts
Reduced count of ts-ignore in project. Added several TS hekpers `Split` and `LastArrayElement`
> TS-Migration: Reduced amount of ts-ignore

- src/components/Button/Button.tsx
- src/components/Icon/__tests__/all-icons-tests.jest.ts
- src/components/Slider/SelectionIndicator.tsx
https://monday.monday.com/boards/3532714909/pulses/3591084124
> Hot fix after external PR

- babel.config.js
- package-lock.json
- package.json
remove not needed packages from library
> remove not needed packages

- src/components/RadioButton/RadioButton.scss
- src/components/RadioButton/RadioButton.tsx
- src/components/RadioButton/__stories__/radioButton.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/3553912892
> RadioButton: add disabled-text-color

- src/components/Dropdown/Dropdown.jsx
> close while scrolling with in dialog/modal mode

- src/components/RadioButton/__stories__/interactions.js
- src/tests/interactions-utils.ts
https://monday.monday.com/boards/3532714909/pulses/3615683720
> Fix interactions-utils imports in RadioButton

- src/tests/readme.md
https://monday.monday.com/boards/3532714909/pulses/3580137995
> Test readme markdown fixes

- src/hooks/useKeyEvent/index.ts
https://monday.monday.com/boards/3532714909/pulses/3580225557
> Fix AvatarGroup tooltip keyboard navigation: fix checkWithoutModifierInEvent

- src/components/MenuButton/MenuButton.jsx
- src/components/MenuButton/__stories__/MenuButton.stories.mdx
- src/components/MenuButton/__tests__/__snapshots__/menuButton.jest.js.snap
- src/components/MenuButton/__tests__/menuButton.jest.js
> MenuButton: allow to specify position of an icon

- src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/3665549607
> Accessability story navigation fix

- src/components/Tooltip/Tooltip.tsx
https://monday.monday.com/boards/3532714909/pulses/3683884311
> Import react to prevent cypress tests (in docs team e.g.) from failing

- src/components/Tabs/TabList/TabList.tsx
https://monday.monday.com/boards/245345663/pulses/1069041783
> Fix TabList undefined error

- src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem-snapshot-tests.jest.js.snap
- src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
- src/components/EditableHeading/EditableHeading.jsx
- src/components/EditableHeading/EditableHeading.scss
- src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
- src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.js.snap
- src/components/Heading/Heading.scss
- src/components/Heading/Heading.tsx
- src/components/Heading/HeadingConstants.ts
- src/components/Heading/__stories__/Heading.stories.mdx
- src/components/Heading/__tests__/__snapshots__/heading.jest.js.snap
- src/components/TextWithHighlight/TextWithHighlight.tsx
- src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
- src/styles/typography.scss
Reverts mondaycom/monday-ui-react-core#1041 because it's creating this issue on prod:
> Revert "Heading Weights"

- src/components/Tipseen/Tipseen.module.scss
https://monday.monday.com/boards/3532714909/pulses/3710545603
Checked it on the monolith - it's working just fine
> Increase Tipseen styles specificity to override Tooltip styles

- src/components/AlertBanner/AlertBannerText/AlertBannerText.tsx
- src/components/ButtonGroup/ButtonGroup.tsx
- src/components/ButtonGroup/ButtonWrapper.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Heading/Heading.tsx
- src/components/IconButton/IconButton.tsx
- src/components/Menu/MenuItem/MenuItem.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.tsx
- src/components/MenuButton/MenuButton.tsx
- src/components/Slider/SliderBase/SliderThumb.tsx
- src/components/SplitButton/SplitButton.tsx
- src/components/TextWithHighlight/TextWithHighlight.tsx
- src/components/Tipseen/Tipseen.jsx
- src/components/Tooltip/Tooltip.tsx
- src/constants/positions.ts
- src/helpers/backwardCompatibilityForProperties.ts
https://monday.monday.com/boards/3532714909/pulses/3716374138
`IconButton` new prop `tooltipProps` + `DialogPosition` refactoring
Better review commit by commit
> Feature/sergeyro/icon button tooltipProps

- src/components/Chips/__stories__/chips.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/3758238678
> Clickable chips redesign story

- .storybook/manager-head.html
https://monday.monday.com/boards/3532714909/pulses/3710647491
> Revert "Fix storybook menu colors (#1050)"

- package.json
> Fix all icons

- src/components/AvatarGroup/__stories__/AvatarGroup.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/3796898745
Before:
After:
> AvatarGroup: teams use case fix

- package-lock.json
- package.json
https://monday.monday.com/boards/3532686451/views/80491565/pulses/3815266793
> move lodash-es from devDependencies to dependencies

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/Dropdown/components/menu/menu.jsx
- src/components/Dropdown/dropdown-constants.js
> fix dropdown with modal/dialog state (support scroll inside dropdown)

- src/components/Checkbox/Checkbox.jsx
https://monday.monday.com/boards/3532714909/pulses/3822719046
> Checkbox: checkbox and label className props

- src/components/Tipseen/TipseenContent.tsx
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
- src/components/Tipseen/__tests__/tipseen-tests.jest.js
> small tipseen test fix

- src/components/Accordion/AccordionItem/AccordionItem.tsx
- src/components/ExpandCollapse/ExpandCollapse.scss
- src/components/ExpandCollapse/ExpandCollapse.tsx
- src/components/ExpandCollapse/styles.module.scss
* Adding classnames to customize specific place in Expanable
* Improve CSS structure for Expandable
> AccordionItem and ExpandAble preparation for css modules transition

- src/components/RadioButton/RadioButton.tsx
> add class names to marker and description of radiobutton

- src/components/Skeleton/Skeleton.module.scss
- src/components/Skeleton/Skeleton.scss
- src/components/Skeleton/Skeleton.tsx
https://monday.monday.com/boards/3532714909/pulses/3889970261
> Skeleton - wrapperClassName and fullWidth props added

- .storybook/preview-head.html
- README.md
- package-lock.json
- package.json
- src/components/Heading/Heading.scss
- src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
- src/storybook/styles/typography.scss
Update core style library and core fonts to suite monday.com appearance
* Update Storybook appearance
* Update monday-ui-style version 
* Update letter spacing for heading components with new fonts
> update Figtree and Poppins

- src/components/Modal/Modal.module.scss
- src/components/Modal/Modal.tsx
https://monday.monday.com/boards/3015775582/pulses/3934480198
> Modal: Add zIndex prop

- src/components/Combobox/Combobox.jsx
- src/components/Combobox/Combobox.scss
- src/components/Combobox/ComboboxHelpers/ComboboxHelpers.jsx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/Combobox/__stories__/combobox.stories.scss
- src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
- src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
- src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
- src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
> Add support for combobox optionClassName & combobox dark mode fixes

- src/components/Search/Search.tsx
> fix: Search component onChange callback type

- src/components/Counter/Counter.scss
- src/components/Counter/Counter.tsx
- src/components/Counter/__tests__/__snapshots__/counter-snapshot-tests.jest.tsx.snap
- src/components/Counter/__tests__/counter-snapshot-tests.jest.tsx
https://monday.monday.com/boards/3532714909/pulses/3918610983
> Counter: counterClassName added

- src/components/ModalHeader/ModalHeader.module.scss
Update the modal font family to support recent font changes
> Fix modal title font family

- src/storybook/stand-alone-documentaion/welcome/other-contributors-list/contributors.tsx
- src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
- src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.scss
> Add founding designers to welcome page

- src/components/Avatar/Avatar.tsx
- src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.tsx
- src/components/Dropdown/components/Control/Control.jsx
- src/components/MenuButton/MenuButton.tsx
- src/components/Tooltip/Tooltip.tsx
https://monday.monday.com/boards/3532714909/pulses/3918004269
> Tooltip.hideShowTriggers - static property

- src/components/Chips/Chips.tsx
- src/components/Chips/__stories__/chips.stories.mdx
- src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
- src/components/Chips/__tests__/chips-tests.jest.tsx
- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
Set chips clickable behavior as default instead of extra prop for backward support and clearer API + tests
> Set chips clickable behavior as default instead of extra prop for backward support and clearer API 

- src/components/Tipseen/__stories__/tipseen.stories.mdx
- src/components/Tipseen/__stories__/tipseen.stories.scss
- src/storybook/components/component-rules/component-rules.jsx
- src/storybook/components/component-rules/component-rules.scss
- src/styles/global-css-settings.scss
Change min width of do/don't rule in stories
override default for tipseen (the examples are bigger there
> Fix responsive dos and dont's by change min width and fix tipseen story

- src/components/Button/Button.scss
- src/components/Button/__stories__/button.stories.mdx
- src/components/Checkbox/Checkbox.tsx
- src/components/Checkbox/__stories__/checkbox.stories.mdx
- src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.tsx
- src/components/Checkbox/__tests__/checkbox-tests.jest.tsx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/storybook/components/related-components/descriptions/checkbox-description.jsx
fix the disabled - look and feel of disabled on primary color
> Button on color disabled

- src/components/Dialog/Dialog.tsx
- src/components/Tooltip/Tooltip.tsx
https://monday.monday.com/boards/3532714909/pulses/3918057455
> Dialog/Tooltip showOnDialogEnter prop description

- src/components/RadioButton/RadioButton.tsx
> Radio Button Docs

- src/components/RadioButton/RadioButton.tsx
> add more docs

- src/components/Skeleton/Skeleton.scss
Skeleton "wave" animation effect seems to be stuck when there's also another heavy task on the browser (like loading the board), so this change is for the animation to use `transform`.
> skeleton animation use transform

- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/helpers/typesciptCssModulesHelper.ts
https://monday.monday.com/boards/3532714909/pulses/4047751841
Fixes issues like this one https://github.com/mondaycom/monday-ui-react-core/pull/1134/files#r1118148921
> Fix getStyle if no such style

- src/components/Tabs/Tab/Tab.tsx
- src/components/Tabs/TabList/TabList.scss
- src/components/Tabs/TabList/TabList.tsx
- src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
- src/components/Tabs/TabsContext/__tests__/__snapshots__/tabsContext-snapshot-tests.jest.js.snap
- src/components/Tabs/__stories__/tabs.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/4105590786
> Feature/sergeyro/tab remove inner css overrides - new prop

- .github/workflows/prerelease.yml
- package.json
- src/components/Chips/Chips.tsx
https://monday.monday.com/boards/3532714909/pulses/4092581602
> Rename prerelease flow

- src/components/EditableHeading/EditableHeading.tsx
- src/components/Heading/Heading.tsx
- src/constants/sizes.ts
> Fix Heading sizes type issue

- src/components/Combobox/Combobox.jsx
- src/components/Combobox/ComboboxHelpers/ComboboxHelpers.jsx
- src/components/Combobox/__tests__/combobox-tests.jest.js
- src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
> Fix combobox bug: trigger onclick event with the wrong option when categories and options not sorted

- src/components/index.js
- webpack/published-ts-components.js
> export list item avatar

- .github/workflows/prerelease.yml
https://monday.monday.com/boards/3532714909/pulses/4155295479
> Prerelease add trigger - workflow_dispatch

- .github/workflows/prerelease.yml
- scripts/prerelease.js
https://monday.monday.com/boards/3532714909/pulses/4155295479
> Prerelease workflow: add workflow_dispatch

- src/components/Menu/MenuItem/MenuItem.tsx
https://monday.monday.com/boards/3532714909/pulses/4169836156
> MenuItem: add iconWrapperClassName prop

- src/components/Modal/ModalHeader/ModalHeader.tsx
https://monday.monday.com/boards/3532714909/pulses/4190287931
> ModalHeader: JsxElement in description

- src/components/Tipseen/Tipseen.tsx
- src/components/Tipseen/TipseenBasicContent.tsx
- src/components/Tipseen/TipseenContent.tsx
- src/components/Tipseen/TipseenWizard.tsx
https://monday.monday.com/boards/3532714909/pulses/4204152904
> Add titleClassName props to customize TipseenTitle

- src/components/Toggle/MockToggle.tsx
- src/components/Toggle/Toggle.tsx
https://monday.monday.com/boards/3532714909/pulses/4204173913
> Toggle add toggleSelectedClassName

- src/components/EditableInput/EditableInput.tsx
- src/components/VirtualizedList/VirtualizedList.tsx
https://monday.monday.com/boards/3532714909/pulses/4229007279
> Fix/sergeyro/sentry errors (EditableInput, VirtualizedList)

- src/components/Accordion/Accordion/__tests__/__snapshots__/accordion-snapshot-tests.jest.js.snap
- src/components/Accordion/AccordionItem/__tests__/__snapshots__/accordionItem-snapshot-tests.jest.js.snap
- src/components/ExpandCollapse/ExpandCollapse.scss
- src/components/ExpandCollapse/ExpandCollapse.tsx
- src/components/ExpandCollapse/__tests__/__snapshots__/expandCollapse.jest.js.snap
- src/components/ExpandCollapse/styles.module.scss
> Fix hide border bug in expand collapse 

- src/components/MenuButton/MenuButton.scss
- src/components/MenuButton/MenuButton.tsx
> Support menu button controlled active state

- src/components/ExpandCollapse/ExpandCollapse.scss
- src/components/ExpandCollapse/styles.module.scss
- src/components/MenuButton/__stories__/MenuButton.stories.mdx
Fix bug: when prop hideBorder is true bottom border is still displayed
> fix expand collapse border bug

- src/components/SplitButton/SplitButton.tsx
> Fix bug on split button loading state

- src/components/Heading/Heading.tsx
- src/hooks/useIsOverflowing/useIsOverflowing.ts
- src/styles/typography.scss
https://monday.monday.com/boards/3532714909/pulses/4315538081
> Heading: replace padding changes with useIsOverflowing ignoreHeightOverflow prop

- src/components/Dialog/DialogContent/DialogContent.tsx
https://monday.monday.com/boards/3532714909/pulses/4191061674
> Css modules comment

- src/components/TextField/TextField.tsx
- src/components/TextField/TextFieldConstants.ts
> Add number type and onWheel prop to text field

- src/components/VirtualizedGrid/VirtualizedGrid.tsx
- src/components/VirtualizedGrid/__tests__/__snapshots__/virtualizedGrid.jest.js.snap
- src/components/VirtualizedGrid/__tests__/virtualizedGrid.jest.js
> Support scrollable class name for virtualized grid

- src/components/ColorPicker/ColorPicker.tsx
> ColorPicker - fix background incorrect setting on hover

- scripts/release.js
> Internal: Add change log result to log in case of failure in release process

- src/components/Link/Link.scss
- src/components/Link/__stories__/Link.stories.mdx
> Fix margin between link and is related icon

- src/components/EditableHeading/EditableHeading.tsx
- src/components/EditableHeading/__tests__/__snapshots__/editableHeading.jest.tsx.snap
https://monday.monday.com/boards/3532714909/pulses/4318543931
> EditableHeading - add data-testid

- src/components/Dropdown/Dropdown.jsx
https://monday.monday.com/boards/3532714909/pulses/4399836961
> Dropdown: customOnOptionRemove as a callback, not as a replacement for inner logic

- package-lock.json
- package.json
- src/components/AttentionBox/AttentionBox.scss
- src/components/AttentionBox/AttentionBox.tsx
- src/components/AttentionBox/AttentionBoxConstants.ts
- src/components/AttentionBox/__stories__/attentionBox.stories.mdx
- src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
- src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
- src/styles/theme-mixin.scss
- src/utils/colors-vars-map.ts
https://monday.monday.com/boards/3532714909/pulses/4332740500
> Css modules/sergeyro/attention box warning color + icons color + heading style fix

- .github/workflows/publish-storybook.yml
https://monday.monday.com/boards/3532714909/pulses/4416306702
> Publish-storybook on release completed

- src/components/Checkbox/__stories__/checkbox.stories.mdx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/FieldLabel/FieldLabel.scss
- src/components/Search/__stories__/Search.stories.scss
- src/components/TextField/TextField.scss
> Docs and craft updates in components

- .github/workflows/release-deprecated.yml
https://monday.monday.com/boards/3532714909/pulses/4470817114
> Release deprecated workflow

- .github/workflows/release-v1.yml
https://monday.monday.com/boards/3532714909/pulses/4470817114
> Release v1 workflow

- scripts/release.js
https://monday.monday.com/boards/3532714909/pulses/4470817114
> Release: breaking changes support

- src/components/Loader/Loader.tsx
- src/components/Loader/__tests__/__snapshots__/loader-snapshots.jest.js.snap
- src/components/Loader/__tests__/loader-snapshots.jest.js
> add wrapper class name to loader

- .github/workflows/release.yml
> Internal: release process - using package_version variables - test

- src/components/Button/Button.tsx
> patch: Dummy changes

- src/components/Button/Button.tsx
> Dummy change 5

- CHANGELOG.md
https://monday.monday.com/boards/3532714909/pulses/4470817114
> docs: Vibe 2.0 changelog

- src/components/ResponsiveList/ResponsiveList.jsx
https://monday.monday.com/boards/3532714909/pulses/4508138991
V1 - https://github.com/mondaycom/monday-ui-react-core/pull/1296
> feat: <ResponsiveList> add menuWrapperClassName prop

- src/components/ResponsiveList/ResponsiveList.jsx
https://monday.monday.com/boards/3532714909/pulses/4508138991
V2 - https://github.com/mondaycom/monday-ui-react-core/pull/1295
> V1 - feat: <ResponsiveList> add menuWrapperClassName prop

- src/components/IconButton/__stories__/IconButton.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/4511934567
> docs: <IconButton> fix size in one of the stories

- .github/workflows/update-icons.yml
https://monday.monday.com/boards/3532714909/pulses/4508436693
> Internal: update-icons workflow - change reviewer, change commit message, PR title

- src/components/ProgressBars/LinearProgressBar/Bar/Bar.tsx
- src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
- src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
- src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts
- src/components/ProgressBars/LinearProgressBar/__stories__/linearProgressBar.stories.mdx
- src/components/ProgressBars/LinearProgressBar/__tests__/__snapshots__/linearProgressBar-snapshot-tests.jest.js.snap
> [Version 1 support] - Progress bar full width variant

- .github/workflows/test-workflow.yml
https://monday.monday.com/boards/3532714909/pulses/4507814132
> Internal: run test-workflow on pull_request - for public forks

- src/components/MenuButton/MenuButton.tsx
> Version 1: Fix menu button TS bugs

- src/components/Skeleton/Skeleton.module.scss
Change skeleton animation
New
https://github.com/mondaycom/monday-ui-react-core/assets/88330692/5fa62dd0-dd07-4a34-9be5-8a07b472d2b4
Old
https://github.com/mondaycom/monday-ui-react-core/assets/88330692/73045258-a96b-432b-b239-b3e795fd92c2
> feat: change-skeleton-animation

- src/components/AvatarGroup/AvatarGroupCounterTooltipContentVirtualizedList.tsx
- src/types/ElementContent.ts
> Fix TS ElementContent type V1

- src/components/Tipseen/Tipseen.module.scss
- src/components/Tipseen/Tipseen.tsx
- src/components/Tipseen/TipseenConstants.ts
- src/components/Tipseen/__stories__/tipseen.stories.mdx
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
- src/components/Tipseen/__tests__/tipseen-tests.jest.js
- src/storybook/functions/createStoryMetaSettings.js
There is a special reason to add it also to v1? Or it's ok to add it only to V2?
> Add support on close button theme for tipseen (V2)

- src/components/Tipseen/Tipseen.module.scss
- src/components/Tipseen/Tipseen.tsx
- src/components/Tipseen/TipseenConstants.ts
- src/components/Tipseen/__stories__/tipseen.stories.mdx
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
- src/components/Tipseen/__tests__/tipseen-tests.jest.js
> v1: Feature/hadas/dark theme tipseen 

- src/components/Dialog/Dialog.tsx
- src/components/Dialog/DialogContent/DialogContent.tsx
- src/hooks/useDisableScroll/__stories__/useDisableScroll.stories.mdx
- src/hooks/useDisableScroll/__tests__/useDisableScroll.jest.ts
- src/hooks/useDisableScroll/index.ts
> Support disable scroll in dialog

- src/components/Skeleton/Skeleton.scss
> V1: Reverting skeleton animation changes due css classes conflicts and opacity issue

- src/components/Chips/__stories__/chips.stories.mdx
> Fix chips with background with the same color story

- src/components/Dialog/DialogContent/DialogContent.tsx
- src/hooks/useDisableScroll/__tests__/useDisableScroll.jest.ts
- src/hooks/useDisableScroll/index.ts
> Hotfix for not throw an error on dialog when disable scroll is false

- src/components/Dialog/DialogContent/DialogContent.tsx
- src/hooks/useDisableScroll/__tests__/useDisableScroll.jest.ts
- src/hooks/useDisableScroll/index.ts
> V1: hotfix for use disable scroll

- src/components/Tipseen/Tipseen.module.scss
- src/components/Tooltip/Tooltip.module.scss
https://monday.monday.com/boards/3532714909/pulses/4547079857
> fix: <Tipseen/> - override the <Tooltip/> styles by using dedicates CSS variables to prevent CSS order issue

- src/components/Chips/Chips.module.scss
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
https://monday.monday.com/boards/3532714909/pulses/4570977516
> fix: <Dropdown> multi fix <Chips> override with css variables

- src/components/Modal/ModalContent/ModalContent.module.scss
- src/components/Modal/ModalHeader/ModalHeader.module.scss
- src/components/Modal/ModalHeader/ModalHeader.tsx
- src/components/Modal/__stories__/Modal.stories.scss
- src/components/Modal/__stories__/helpers.js
- src/components/Modal/__stories__/modal.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/4556458677
> V1 - feat: <Modal> custom header title

- src/components/EditableHeading/EditableHeading.tsx
- src/components/Modal/ModalContent/ModalContent.module.scss
- src/components/Modal/ModalHeader/ModalHeader.module.scss
- src/components/Modal/ModalHeader/ModalHeader.tsx
- src/components/Modal/__stories__/Modal.stories.scss
- src/components/Modal/__stories__/helpers.js
- src/components/Modal/__stories__/modal.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/4556458677
Chromatic: https://62037c72e0e4d6004a9a450f-yiocueayfe.chromatic.com/?path=/docs/feedback-modal--modal-with-editable-title
V1 - https://github.com/mondaycom/monday-ui-react-core/pull/1335
> feat: <Modal> custom header title

- src/components/VirtualizedGrid/VirtualizedGrid.tsx
- src/components/VirtualizedList/VirtualizedList.tsx
> fix: AutoSizer TS issues

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/__tests__/dropdown-tests.jest.js
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
https://monday.monday.com/boards/3532714909/pulses/4571615283
> V1 - fix: <Dropdown> multi on option delete callback

- VERSION-2-MIGRATION.md
https://monday.monday.com/boards/3532714909/pulses/4587817551
> docs: Vibe 2 migration guide

- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.module.scss
https://monday.monday.com/boards/3532714909/pulses/4569744883
V1 - https://github.com/mondaycom/monday-ui-react-core/pull/1339
> feat: <StepIndicator> font-weight redesign + small padding fixes

- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.scss
https://monday.monday.com/boards/3532714909/pulses/4569744883
> V1 - feat: <StepIndicator> font-weight redesign + small padding fixes

- src/components/Dialog/Dialog.tsx
- src/components/Dialog/__stories__/Dialog.stories.mdx
Dialog overview story code before the change:
Dialog overview story code after the change:
> Fix dialog overview story + add come prop comments

- src/components/Tipseen/Tipseen.tsx
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
> Fix bug on Tipseen in dark mode

- src/components/Tipseen/TipseenTitle.module.scss
[item](https://monday.monday.com/boards/4565007308/views/102943730/pulses/4649248985)
> Remove redundant tipseen max-width property

- src/components/index.js
- webpack/published-js-components.js
https://monday.monday.com/boards/3532714909/pulses/4704022171
> feat: Publish <GridKeyboardNavigationContext>

- package.json
https://monday.monday.com/boards/3532714909/pulses/4633056724
> V1 - fix: icons, interactionsTests, testIds types exports

- src/components/Accordion/Accordion/__tests__/__snapshots__/accordion-snapshot-tests.jest.js.snap
- src/components/Accordion/Accordion/__tests__/accordion-snapshot-tests.jest.js
- src/components/Accordion/AccordionItem/AccordionItem.tsx
- src/components/ExpandCollapse/ExpandCollapse.tsx
I wasn't able to change the stories file to use this feature, therefore It's not ready to merge. 
@shlomitc can you take it from here?
> AccordionItem: add support for custom header.

- package-lock.json
- src/components/IconButton/IconButton.tsx
support ariaExpanded in IconButton
> feat: support ariaExpanded in <IconButton>

- src/components/Chips/Chips.tsx
- src/components/Chips/ChipsConstants.ts
Got there cause of external contribution
> fix: remove Chips.sizes

- README.md
https://monday.monday.com/boards/3532714909/pulses/4596797748
> Update browserslist in docs

- src/components/Slider/__tests__/__snapshots__/slider-non-ranged-tests.jest.js.snap
- src/components/Slider/__tests__/__snapshots__/slider-ranged-tests.jest.js.snap
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
- src/components/Tooltip/Tooltip.tsx
- src/components/Tooltip/__tests__/__snapshots__/tooltip-snapshot-tests.jest.tsx.snap
Reverts mondaycom/monday-ui-react-core#1391 - wasn't completely finished
> Revert "refactor: support aria a11y in Tooltip component"

- .storybook/preview.js
> docs: fix storybook light theme name

- src/components/Dialog/__tests__/Dialog.interactions.ts
- src/tests/interactions-utils.ts
- src/tests/readme.md
https://monday.monday.com/boards/3532714909/pulses/4729201760
> fix: InteractionsTest - fix types

- src/utils/colors-vars-map.ts
https://monday.monday.com/boards/3532714909/pulses/4793802819
> docs: change colors descriptions

- src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
- src/components/AttentionBox/__stories__/attentionBox.stories.mdx
- src/components/Combobox/components/ComboboxConstants.ts
- src/components/index.js
- webpack/published-ts-components.js
https://monday.monday.com/boards/3532714909/pulses/4794875901
https://monday.monday.com/boards/3532714909/pulses/4794876726
> Bug: Combobox component ts issues

- src/components/DatePicker/__stories__/datepicker.stories.mdx
this change is for Chromatic visual changes to be stable by making it dependent from today's date
> docs(DatePicker): set default selected days for stories

- src/components/Chips/__stories__/chips.stories.mdx
- src/constants/colors.json
- src/utils/colors-vars-map.ts
Add new color to the Chips component
> Chips: Add WARNING color

- API_GUIDELINES.MD
https://monday.monday.com/boards/3532714909/pulses/4818659218
> docs(API_GUIDELINES): add export instructions for type and interface

- src/components/Box/Box.tsx
- src/components/Box/BoxConstants.ts
- src/components/Box/__stories__/Box.stories.mdx
- src/types/ValueOf.ts
- src/types/index.ts
https://monday.monday.com/boards/3532714909/pulses/4874293393
> fix: <Box/> static props

- rollup/styleInject.ejs
Solve the errors thrown
https://github.com/mondaycom/monday-ui-react-core/issues/1203#issuecomment-1658912659
Errors that appeared before:
> chore: prevent from style injection to explode in server side rendering

- src/components/Heading/Heading.module.scss
> Fix letter spacing in legacy heading (temp until we will able to fix in monday ui style)

- src/components/Heading/Heading.tsx
> Update vibe version number manually 

- src/components/Chips/Chips.tsx
> Change vibe version number manually

- src/storybook/stand-alone-documentaion/shadow/shadow.stories.mdx
https://monday.monday.com/boards/1480902801/pulses/4923382457
> docs: fix Shadows page usage and examples

- src/components/Chips/Chips.tsx
> last manually change for update vibe version?

- package.json
https://monday.monday.com/boards/3532714909/pulses/4923523851
> package.json fix types exports for icons and root

- scripts/build-utils.js
https://monday.monday.com/boards/3532714909/pulses/4803909254
> fix: storybookComponents export - include styles

- package.json
- rollup.config.js
- rollup/styleInject.ejs
Fix an issue with multiple version of Vibe being loaded with the partially the same content
> Add version to class

- rollup.config.js
> fix version number as css selector

- src/components/Tipseen/TipseenTitle.tsx
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
- src/components/Tipseen/__tests__/tipseen-tests.jest.js
https://monday.monday.com/boards/3532714909/pulses/4956392883
> feat(Tipseen): allow tipseen title to have max 2 lines

- src/components/List/utils/ListUtils.ts
> add null check to List component for support undef children

- src/components/LegacyHeading/LegacyHeading.module.scss
> Fix h6 size in legacy heading

- src/components/ListItemAvatar/ListItemAvatar.tsx
- src/components/ListItemIcon/ListItemIcon.tsx
https://monday.monday.com/boards/3532714909/pulses/4966856064
Same prop as `ListItem` component have
> feat: <ListItemIcon>, <ListItemAvatar> component props

- src/components/List/List.tsx
- src/components/List/utils/ListUtils.ts
https://monday.monday.com/boards/3532714909/pulses/4999466126
Now run only once instead of running on each rerender
> fix: <List> id generation

- src/components/Switch/Switch.tsx
- src/components/Toggle/Toggle.tsx
https://monday.monday.com/boards/3532714909/pulses/5019982539
> feat: <Toggle>, <Switch> refForwarding

- src/components/TextField/TextField.tsx
https://monday.monday.com/boards/3532714909/pulses/5020888872
> fix: <TextField> debounce recreation bug

- PULL_REQUEST_TEMPLATE.md
https://monday.monday.com/boards/3532714909/pulses/5023740503
> docs: Update Pull request template

- plop/general/component-stories-mdx.txt
https://monday.monday.com/boards/3532714909/pulses/5031398507
> chore: Update stories plop

- src/components/Accordion/Accordion/__stories__/accordion.stories.mdx
- src/components/ExpandCollapse/ExpandCollapse.module.scss
https://monday.monday.com/boards/3532714909/pulses/5028746075
Task to revisit animation https://monday.monday.com/boards/3532714909/pulses/5042628555
> fix: <ExpandCollapse> flickering

- src/components/List/List.tsx
- src/components/List/utils/ListUtils.ts
https://monday.monday.com/boards/3532714909/pulses/4966695439
> fix: <List> keyboard focus only on list items

- src/components/Table/Table/Table.module.scss
- src/components/Table/Table/Table.tsx
- src/components/Table/Table/__stories__/helpers.js
- src/components/Table/Table/__stories__/table.stories.mdx
- src/components/Table/Table/__stories__/table.stories.scss
- src/components/Table/Table/__tests__/table.jest.tsx
- src/components/Table/Table/tableHelpers.ts
- src/components/Table/TableBody/TableBody.module.scss
- src/components/Table/TableBody/TableBody.tsx
- src/components/Table/TableCell/TableCell.module.scss
- src/components/Table/TableCell/TableCell.tsx
- src/components/Table/TableHeader/TableHeader.module.scss
- src/components/Table/TableHeader/TableHeader.tsx
- src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
- src/components/Table/TableHeaderCell/TableHeaderCell.tsx
- src/components/Table/TableRow/TableRow.module.scss
- src/components/Table/TableRow/TableRow.tsx
- src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
- src/tests/constants.ts
- webpack/published-ts-components.js
> feat: <Table/> - new component

- src/components/BreadcrumbsBar/BreadcrumbsBar.tsx
https://monday.monday.com/boards/3532714909/pulses/5100460435
> fix: <BreadcrumbsBar> type

- src/components/Tipseen/Tipseen.tsx
this ability is to achieve full positioning capabilities for Tipseen
> feat(Tipseen): allow withoutDialog for component

- .github/workflows/chromatic.yml
This reverts commit e4431fa976d71440ee0763cc47358e0ba3853557.
https://monday.monday.com/boards/3532714909/pulses/5105116886
> Revert "chore: fail chromatic action check in case has visual changes (#1392)

- src/components/Tipseen/Tipseen.module.scss
- src/components/Tipseen/Tipseen.tsx
- src/components/Tipseen/__stories__/tipseen.stories.mdx
- src/components/Tooltip/Tooltip.tsx
https://monday.monday.com/boards/3532714909/pulses/5100695395
> feat(Tipseen): add floating variation for Tipseen

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/Dropdown.styles.js
- src/storybook/patterns/dropdown-in-modals/ModalExampleContent.tsx
- src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.stories.mdx
- src/utils/dom-utils.ts
https://monday.monday.com/boards/3532714909/pulses/4990237068
> fix(Dropdown): when used inside overflowed container with transform, consider container scroll

- src/components/LegacyHeading/__stories__/LegacyHeading.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5070102183
> docs: Change <LegacyHeading> name in the story

- src/components/AttentionBox/AttentionBox.tsx
- src/components/Text/Text.tsx
- src/components/Text/__stories__/Text.stories.mdx
- src/components/Text/__tests__/__snapshots__/text-snapshot-tests.jest.js.snap
- src/components/Text/__tests__/text-snapshot-tests.jest.js
- src/components/Tipseen/Tipseen.tsx
https://monday.monday.com/boards/3532714909/pulses/5070117645
> feat(Text): remove paragraph prop (can be achieved with element="p")

- src/components/Table/Table/__stories__/table.stories.mdx
- src/components/Table/Table/tableHelpers.ts
- src/components/Table/TableHeader/TableHeader.module.scss
- src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
- src/components/Table/TableHeaderCell/TableHeaderCell.tsx
https://monday.monday.com/boards/3532714909/pulses/5064338802
- replace sort icon
- replace sort asc/desc icons
- border bottom of header row
- border-radius values should consider border width
- add table's subcomponents to storybook
> feat(Table): table leftovers phase 1

- src/components/Button/Button.tsx
- src/components/List/List.tsx
- src/components/ListItem/ListItem.tsx
https://monday.monday.com/boards/3532714909/pulses/5121462835
close #1527
> feat: add a11y arias props for `List`, `ListItem`, and `Button`

- src/components/Tipseen/Tipseen.tsx
- src/components/Tipseen/__stories__/tipseen.stories.mdx
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
- src/components/Tipseen/__tests__/tipseen-tests.jest.js
https://monday.monday.com/boards/3532714909/pulses/5121927498
> feat(Tipseen): in floating variation do not show tip, make docs for variation clearer

- package-lock.json
- package.json
https://monday.monday.com/boards/3532714909/pulses/5097839339
> chore(browserslist): Use browserslist-config-monday on Vibe

- src/components/AttentionBox/AttentionBox.module.scss
- src/components/AttentionBox/AttentionBox.tsx
- src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
https://monday.monday.com/boards/3532714909/pulses/5134907474
> <AttentionBox> withoutIcon remove padding

- src/components/Tipseen/TipseenTitle.tsx
- src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
https://monday.monday.com/boards/3532714909/pulses/5127607534
> fix(TipseenTitle): font size should be TEXT1 (16px)

- src/components/index.js
https://monday.monday.com/boards/3532714909/pulses/5097261912
> fix(Table): export table-related components

- src/components/ListItem/ListItem.tsx
https://monday.monday.com/boards/3532714909/pulses/5161250546
> fix: <ListItem> children type change to ElementContent

- webpack/published-ts-components.js
https://monday.monday.com/boards/3532714909/pulses/5184162952
> fix(TipseenMedia): fix import/export path

- src/components/Table/Table/Table.tsx
- src/components/Table/TableBody/TableBody.tsx
- src/components/Table/TableCell/TableCell.tsx
- src/components/Table/TableHeader/TableHeader.tsx
- src/components/Table/TableHeaderCell/TableHeaderCell.tsx
- src/components/Table/TableRow/TableRow.tsx
- src/tests/constants.ts
https://monday.monday.com/boards/3532714909/pulses/5153269876
> feat(Table): add vibe component props to all table-related components make components VibeComponent type - with forwardRef

- src/storybook/components/related-components/descriptions/clickable-description/clickable-description.jsx
- src/storybook/components/related-components/descriptions/colors-description/colors-description.jsx
- src/storybook/components/related-components/descriptions/shadow-description/shadow-description.jsx
- src/storybook/components/related-components/descriptions/spacing-description/spacing-description.jsx
- src/storybook/components/related-components/descriptions/typography-description/typography-description.jsx
https://monday.monday.com/boards/3532714909/pulses/4228663977
> docs: add missing up next links

- src/components/Dialog/__stories__/Dialog.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5096740132
> docs: <Dialog> - Dialog with tooltip story

- src/hooks/useKeyboardButtonPressedFunc.ts
https://monday.monday.com/boards/3532714909/pulses/5232028445
> fix: remove preventDefault from useKeyboardButtonPressedFunc.ts

- rollup.config.js
https://monday.monday.com/boards/3532714909/pulses/5242018217
> chore(rollup): export sourcemap with build

- src/components/Label/Label.tsx
- src/components/Label/__tests__/Label-tests.jest.tsx
https://monday.monday.com/boards/3532714909/pulses/5232208575
> fix(Label): apply preventDefault when calling onClick event

- src/storybook/components/component-name/component-name-decorator.scss
https://monday.monday.com/boards/3532714909/pulses/5253754106
> docs: component-name-decorator- text color = fixed-dark

- .storybook/preview-head.html
- package-lock.json
- package.json
- src/storybook/stand-alone-documentaion/typography-new/typography.stories.mdx
- src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5254165773
> Replace Rubik with Noto Sans Hebrew

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/__stories__/dropdown.stories.mdx
> feat(Dropdown): add tabSelectsValue support

- package-lock.json
- package.json
- src/components/Dialog/__stories__/Dialog.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5231616094
> docs: <Dialog> story improvements - UsageGuidelines, add links

- package-lock.json
- package.json
https://monday.monday.com/boards/3532714909/pulses/5191192698
> chore: set browserslist config to specific version to avoid breaking changes, update caniuse browserslist

- src/hooks/useActiveDescendantListFocus/index.ts
https://monday.monday.com/boards/3532714909/pulses/5145770332
> feat(useActiveDescendantListFocus): add option to ignoreDocumentFallback to prevent vibe from adding event listeners

- src/components/Chips/Chips.tsx
> feat: <Chips> - add closeButtonAriaLabel as a prop

- src/components/AttentionBox/AttentionBox.tsx
> feat: <AttentionBox> closeButton - add hideTooltip and closeButtonAriaLabel prop

- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/Menu/Menu/__stories__/menu.stories.js
- src/storybook/stand-alone-documentaion/typography-new/typography.stories.mdx
- src/storybook/stand-alone-documentaion/typography/typography.stories.mdx
Resolves https://github.com/mondaycom/monday-ui-react-core/issues/1583
> fix text in a few places

- src/components/Avatar/Avatar.tsx
- src/components/Avatar/__tests__/__snapshots__/avatar-snapshot-tests.jest.tsx.snap
- src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.tsx.snap
- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/components/ListItemAvatar/__tests__/__snapshots__/listItemAvatar.jest.js.snap
> fix: <Avatar> remove default tabIndex = 0

- .npmrc
- package-lock.json
- package.json
Reverts mondaycom/monday-ui-react-core#1596
Turns out it affects also consumers so reverting
> Revert "chore: enforce using npm"

- .github/workflows/chromatic.yml
https://monday.monday.com/boards/3532714909/pulses/4526273740
Allow running `chromatic` workflow on `pull_request` - for public forks after approval from the maintainers
> infra: allow running chromatic workflow on pull_request

- src/components/Label/Label.tsx
make <Label> a VibeComponent and add ref forwarding (https://github.com/mondaycom/monday-ui-react-core/issues/1588)
> feat: update label with VibeComponent

- src/components/Menu/Menu/__stories__/Menu.stories.mdx
> docs: added a link to Combobox on the Menu page 

- .github/workflows/chromatic.yml
- .github/workflows/test-workflow.yml
https://monday.monday.com/boards/3532714909/pulses/4909393748
> infra: Fix workflows running twice

- src/components/AttentionBox/AttentionBox.tsx
> feat: <AttentionBox> - update default icon for Primary type to Info icon

- src/components/Clickable/__stories__/Clickable.stories.mdx
- src/components/DatePicker/__stories__/datepicker.stories.mdx
- src/components/DialogContentContainer/__stories__/DialogContentContainer.stories.mdx
- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
- src/components/HiddenText/__stories__/HiddenText.stories.mdx
- src/components/Label/__stories__/label.stories.mdx
- src/components/Menu/MenuDivider/__stories__/MenuDivider.stories.mdx
- src/components/Menu/MenuGridItem/__stories__/MenuGridItem.stories.mdx
- src/components/Menu/MenuItem/__stories__/MenuItem.stories.mdx
- src/components/Menu/MenuItemButton/__stories__/MenuItemButton.stories.mdx
- src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.mdx
- src/components/MenuButton/__stories__/MenuButton.stories.mdx
- src/components/MultiStepIndicator/__stories__/multiStepIndicator.stories.mdx
- src/components/RadioButton/__stories__/radioButton.stories.mdx
- src/components/ResponsiveList/__stories__/ResponsiveList.stories.mdx
- src/components/Skeleton/__stories__/skeleton.stories.mdx
- src/components/Tabs/Tab/__stories__/tab.stories.mdx
- src/components/TextWithHighlight/__stories__/TextWithHighlight.stories.mdx
- src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
Issue #1587
Enabled controls for all the remaining stories.
> docs: enable controls for some of the stories

- package-lock.json
- package.json
- src/components/Badge/__stories__/Badge.stories.mdx
- src/components/DatePicker/__stories__/DatePicker.stories.jsx
- src/components/DatePicker/__stories__/datepicker.stories.mdx
- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/HiddenText/__stories__/HiddenText.stories.mdx
- src/components/MenuButton/__stories__/MenuButton.stories.mdx
- src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5280817443
> chore: cleanup in stories controls

- src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
- src/components/EditableHeading/__tests__/editable-heading-interactions.tsx
- src/tests/interactions-utils.ts
Update <EditableHeading> interaction tests (https://github.com/mondaycom/monday-ui-react-core/issues/1576)
> test: add editable heading interaction test

- src/storybook/stand-alone-documentaion/accessibility/accessibility.stories.mdx
Fixes #1580.
- Fix spacing.
- Fix size.
Attachments:
> docs: fix links

- src/components/Menu/MenuDivider/MenuDivider.module.scss
> fix: <MenuDivider/> - added necessary stylings

- src/components/Checkbox/__stories__/checkbox.stories.mdx
- src/components/Checkbox/__stories__/checkbox.stories.scss
- src/components/Menu/MenuDivider/MenuDivider.module.scss
> docs: <Checkbox> Usage guidelines - fix font #1577

- src/components/Counter/Counter.module.scss
https://monday.monday.com/boards/3532714909/pulses/4776199392
> fix: <Counter> use color - text-color-fixed-light

- src/components/AvatarGroup/AvatarGroupCounter.tsx
- src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.tsx
> chore: fix Github actions lint warnings - < AvatarGroup />

- src/components/Checkbox/__tests__/checkbox-tests.jest.tsx
Closes #1630 
Fix lint warnings in github actions for checkbox tests
> chore: fix github actions lint warnings - < Checkbox /> tests

- src/components/AlertBanner/AlertBanner.tsx
Closes #1632 
Fixed lint errors.
> chore: fix github actions lint warnings - <AlertBanner />

- src/components/ColorPicker/ColorPicker.tsx
- src/components/ColorPicker/components/ColorPickerContent/ColorPickerClearButton.tsx
- src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.tsx
- src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
> chore: fix Github actions lint warnings - < ColorPicker />

- src/components/Button/Button.tsx
- src/components/Button/ButtonConstants.ts
> chore: fix Github actions lint warnings - < Button />

- src/components/AvatarGroup/AvatarGroupCounter.tsx
- src/components/Table/TableHeaderCell/TableHeaderCell.tsx
> feat: provide props for ariaLabel - < AvatarGroupCounter />, < TableHeaderCell />

- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.tsx
- src/components/ProgressBars/LinearProgressBar/Bar/Bar.tsx
- src/components/Slider/SliderHelpers.ts
- src/components/Tabs/TabsContext/TabsContext.tsx
> Resolved lint warnings - < Slider />, < StepIndicator />, < Bar />, <TabsContext />

- src/utils/colors-vars-map.ts
https://monday.monday.com/boards/3532714909/pulses/4776198972
> docs: fix description of text-color-fixed-light and text-color-fixed-dark

- src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.tsx
Fixes #1655 
**before**
**now**
> fix: colorpicker indicator is dissapearing when color is selected

- .github/workflows/test-workflow.yml
https://monday.monday.com/boards/3532714909/pulses/5333932662
> infra: add build-test in test-workflow.yml

- src/components/AlertBanner/AlertBanner.module.scss
- src/components/AlertBanner/AlertBanner.tsx
- src/components/AlertBanner/AlertBannerConstants.ts
- src/components/AlertBanner/AlertBannerContext.ts
- src/components/AlertBanner/__stories__/alertBanner.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/4333987287
> feat(AlertBanner): add warning variation

- src/components/Menu/Menu/Menu.tsx
- src/components/Menu/Menu/MenuConstants.ts
- src/components/Menu/Menu/utils/utils.ts
- src/components/Menu/MenuItem/MenuItem.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.tsx
- src/components/MenuButton/MenuButton.tsx
> chore: resolve lint warnings - < Menu />

- package.json
- src/types/index.ts
- src/types/positions.ts
pre-step to export all types from vibe
https://monday.monday.com/boards/3532714909/pulses/5342878337
> feat(types): export general types

- package-lock.json
- package.json
https://monday.monday.com/boards/3532714909/pulses/5348385312
> Update vibe-storybook-components version, @babel/core version

- package.json
https://monday.monday.com/boards/3532714909/pulses/5342878337
> fix(types): fix unknown path '/types'

- src/components/AlertBanner/__stories__/alertBanner.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/4333987287/posts/2480699422
> docs(AlertBanner): fix documentation

- src/components/Tipseen/Tipseen.tsx
https://monday.monday.com/boards/3532714909/pulses/5356049559
> feat: < Tipseen /> export hideShowTriggers

- src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx
https://monday.monday.com/boards/3532714909/pulses/5356019696
Before
Now
> docs: fix contributors list to include all contributors

- src/components/AlertBanner/AlertBanner.tsx
- src/components/Button/Button.tsx
- src/components/Chips/Chips.tsx
- src/components/Clickable/Clickable.tsx
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
- src/components/EditableHeading/EditableHeading.tsx
- src/components/EditableHeading/__tests__/editableHeading.jest.tsx
- src/components/IconButton/IconButton.tsx
- src/components/Modal/__stories__/helpers.js
- src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.tsx
- src/components/Steps/StepsCommand.tsx
- src/components/TextField/TextField.tsx
- src/components/Toast/ToastButton/ToastButton.tsx
- src/components/Tooltip/__tests__/tooltip-tests.jest.tsx
- src/hooks/useClickableProps/useClickableProps.ts
https://monday.monday.com/boards/3532714909/pulses/3565998932
> Add mising data-testid, replace dataTestId (not breaking)

- src/components/AttentionBox/AttentionBox.tsx
- src/components/Avatar/Avatar.tsx
- src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.tsx
- src/components/ButtonGroup/ButtonGroup.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Dialog/Dialog.tsx
- src/components/Divider/Divider.tsx
- src/components/Label/Label.tsx
- src/components/Link/Link.tsx
- src/components/Loader/Loader.tsx
- src/components/Menu/Menu/Menu.tsx
- src/components/Menu/MenuDivider/MenuDivider.tsx
- src/components/Menu/MenuItem/MenuItem.tsx
- src/components/Menu/MenuItemButton/MenuItemButton.tsx
- src/components/Menu/MenuTitle/MenuTitle.tsx
- src/components/MenuButton/MenuButton.tsx
- src/components/RadioButton/RadioButton.tsx
- src/components/TextField/TextField.tsx
- src/components/Tipseen/Tipseen.tsx
- src/components/Tipseen/TipseenConstants.ts
- src/components/Tipseen/TipseenContent.tsx
- src/components/Toggle/Toggle.tsx
https://monday.monday.com/boards/3532714909/pulses/5356966348
> chore: add @deprecated comments where backwardCompatibilityForProperties is being used

- src/components/Toast/Toast.tsx
- src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
> fix: <Toast /> close button - replace <Button /> and <Icon /> with <IconButton />
