mondaycom/vibe

- src/components/EditableInput/EditableInput.tsx
https://monday.monday.com/boards/3532714909/pulses/5370039801
> feat(EditableInput): expose inputType

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/__stories__/dropdown.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5370505249
> fix: <Dropdown> controlled multi fix option remove

- src/hooks/index.js
- webpack/published-ts-components.js
Export useElementsOverflowingIndex
> export useElementsOverflowingIndex hook

- src/components/AvatarGroup/AvatarGroup.module.scss
- src/components/AvatarGroup/AvatarGroup.tsx
> feat: < AvatarGroup /> - added new prop to remove padding (#1674)

- src/components/FieldLabel/FieldLabel.module.scss
- src/components/FieldLabel/FieldLabel.tsx
- src/components/TextField/TextField.tsx
- src/components/TextField/__stories__/TextField.stories.mdx
> feat: < TextField /> add red asterisks(*) when required=true

- src/components/Combobox/Combobox.tsx
- src/components/Combobox/ComboboxHelpers/ComboboxHelpers.tsx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
- src/components/Combobox/components/ComboboxItems/ComboboxItems.tsx
> fix: < ComboBox / > - change stickyCategories to not be the default behavior

- src/components/Dialog/Dialog.tsx
> feat: < Dialog /> should throw console.error if containerSelector is not found

- src/components/Button/Button.module.scss
- src/components/Button/Button.tsx
- src/components/Button/__stories__/button.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5350721960
> fix(Button): adjust loading state to initial button size

- src/components/MenuButton/MenuButton.module.scss
- src/components/MenuButton/MenuButton.tsx
https://monday.monday.com/boards/3532714909/pulses/5399048319
> fix: <MenuButton> change moveBy <Dialog> and active state text color

- src/components/Text/Text.tsx
https://monday.monday.com/boards/3532714909/pulses/5070129086
> chore: cleanup - lint issue

- src/components/AttentionBox/AttentionBox.module.scss
- src/components/AttentionBox/AttentionBox.tsx
- src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
https://monday.monday.com/boards/3532714909/pulses/5382954488
> fix(AttentionBox): fix title overflow behavior

- src/components/Tipseen/Tipseen.tsx
- src/components/Tooltip/Tooltip.tsx
- src/components/Typography/TypographyHooks.tsx
- src/components/VirtualizedGrid/VirtualizedGrid.tsx
- src/components/VirtualizedList/VirtualizedList.tsx
Closes #1650 
Fix lint warnings in  - < Tipseen />, < Tooltip />, < TypographyHooks />, < VirtualizedList />, < VirtualizedGrid />
> chore: fix lint warnings

- src/components/ThemeProvider/__stories__/ThemeProvider.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5065724987
> docs: ThemeProvider alpha tag instead of beta

- src/components/Dropdown/Dropdown.jsx
https://monday.monday.com/boards/3532714909/pulses/5457990824
Provides ability to override default filterOption behaviour - https://react-select.com/advanced#custom-filter-logic
> feat: <Dropdown> add filterOption prop for custom filter

- DEPRECATED_IMPORTS.md
- README.md
https://monday.monday.com/boards/3532714909/pulses/5343837406
Corresponding PR in Atmosphere https://github.com/DaPulse/monday-npm-packages/pull/4250
> docs: improve readme files on how to import css - mention storybook

- .storybook/preview-head.html
- .storybook/preview.js
https://monday.monday.com/boards/3532714909/pulses/5484481728
> docs: remove hacker theme from storybook

- src/components/Dropdown/__stories__/dropdown.stories.mdx
- src/components/Dropdown/__tests__/Dropdown.interactions.js
- src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
https://monday.monday.com/boards/3532714909/pulses/5392143623
> fix(MultiValueContainer): align items vertically

- src/components/ThemeProvider/ThemeProviderConstants.ts
- src/components/ThemeProvider/__stories__/ThemeProvider.stories.mdx
- src/components/ThemeProvider/__stories__/ThemeProvider.stories.tsx
- src/components/ThemeProvider/__tests__/themeProvider-tests.jest.js
https://monday.monday.com/boards/3532714909/pulses/5484524498
> fix: <ThemeProvider> remove Hacker theme from eligible for overrides

- src/components/Button/__stories__/button.stories.mdx
- src/components/ButtonGroup/__stories__/buttonGroup.stories.mdx
- src/components/Combobox/__stories__/combobox.stories.mdx
- src/components/IconButton/__stories__/IconButton.stories.mdx
- src/components/Menu/Menu/__stories__/Menu.stories.mdx
- src/components/SplitButton/__stories__/splitButton.stories.mdx
- src/storybook/components/related-components/descriptions/button-group-description.jsx
- src/storybook/components/related-components/descriptions/icon-button-description.jsx
- src/storybook/components/related-components/descriptions/split-button-description.jsx
https://monday.monday.com/boards/3532714909/pulses/5507683216
> docs: rename stories names to be in pascal case

- src/components/Checkbox/Checkbox.tsx
https://monday.monday.com/boards/3532714909/pulses/5515731903
> feat(Checkbox): add a tabIndex prop

- src/components/List/__stories__/List.stories.mdx
https://monday.monday.com/boards/1480902801/pulses/5440268265
> docs: fix typo

- src/components/Button/Button.tsx
https://monday.monday.com/boards/3532714909/pulses/5554571502
> fix(Button): include entire content for width placeholder

- .storybook/preview.js
This fixes all the flakiness
https://monday.monday.com/boards/3532714909/pulses/5264715596
> test(Chromatic): wait for font loading before taking a snapshot

- src/components/Table/Table/__stories__/table.stories.mdx
https://monday.monday.com/boards/3532714909/pulses/5561733547
> docs(Table): Scroll story should have same length as other stories

- src/components/Toast/ToastHelpers.tsx
- src/components/Toast/__tests__/__snapshots__/toast-snapshot-tests.jest.js.snap
https://monday.monday.com/boards/3532714909/pulses/5554310832
> fix(Toast): description icon should be 20px

- src/storybook/components/related-components/component-description-map.tsx
- src/storybook/components/related-components/descriptions/color-picker-description.tsx
https://monday.monday.com/boards/3532714909/pulses/5506784841
> docs: RelatedComponents - add <ColorPicker> component

- .github/workflows/update-icons.yml
https://monday.monday.com/boards/3532714909/pulses/5574910459
> infra: disable cron for update monday-ui-style version workflow

- package-lock.json
- package.json
- src/components/AlertBanner/AlertBanner.module.scss
- src/components/Button/Button.module.scss
- src/components/Counter/Counter.module.scss
- src/components/Toast/Toast.module.scss
- src/components/Typography/Typography.module.scss
- src/storybook/stand-alone-documentaion/colors/colors-description/colors-description.jsx
- src/storybook/stand-alone-documentaion/colors/semantic-colors/semantic-colors.jsx
- src/storybook/stand-alone-documentaion/colors/text-colors/text-colors.jsx
- src/utils/colors-vars-map.ts
https://monday.monday.com/boards/3532714909/pulses/5557143080
> fix: replace deprecated text-fixed-color tokens with identical color tokens

- src/storybook/components/related-components/component-description-map.tsx
- src/storybook/components/related-components/descriptions/virtualized-list-description/virtualized-list-description.jsx
- src/storybook/components/related-components/descriptions/virtualized-list-description/virtualizedList.module.scss
https://monday.monday.com/boards/3532714909/pulses/5506803160
> docs: RelatedComponents - add <VirtualizedList> component description example

- src/components/Table/TableRow/TableRow.tsx
> Support className in TableRow

- src/components/EditableText/__tests__/editableText-tests.jest.tsx
- src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/5635890437
> feat(EditableTypography): add onClick event

- src/components/Toggle/ToggleText.tsx
- src/components/Toggle/__tests__/__snapshots__/toggle-snapshot-tests.jest.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/5456354686
> fix: changed toggle typography

- PULL_REQUEST_TEMPLATE.md
- src/storybook/components/related-components/descriptions/colors-description/colors-description.jsx
- src/storybook/components/related-components/descriptions/shadow-description/shadow-description.jsx
- src/storybook/components/related-components/descriptions/spacing-description/spacing-description.jsx
- src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.jsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/5644789481
> docs: fix broken docs links

- src/hooks/useIsOverflowing/__stories__/useIsOverflowing.stories.js
https://monday.monday.com/boards/3532714909/pulses/5643741446
> docs: useIsOverflowing.stories.js - remove maintenance warning

- src/components/Table/Table/__stories__/table.stories.js
- src/components/Table/Table/__tests__/table.jest.tsx
- src/components/Table/TableBody/TableBody.tsx
https://monday.monday.com/boards/3532714909/pulses/5657990031
> fix(Table): table does not render empty state if children are empty array

- src/components/Table/Table/Table.tsx
- src/components/Table/Table/__stories__/table.stories.js
https://monday.monday.com/boards/3532714909/pulses/5658306962
> fix: export Table.sizes enum

- src/components/Dropdown/__stories__/dropdown.stories.js
https://monday.monday.com/boards/3532714909/pulses/5645963341
> docs(Dropdown): fix menuPosition & menuPlacement props in argsTable controls

- src/components/Menu/MenuItem/MenuItem.tsx
https://monday.monday.com/boards/3532714909/pulses/5668502162
> chore(MenuItem): fix circular dependency with IconButton's import

- rollup.config.js
https://monday.monday.com/boards/3532714909/pulses/5668670716
> build(Rollup): fail build if circular dependency detected

- src/components/Avatar/__stories__/avatar.mdx
- src/components/AvatarGroup/__stories__/AvatarGroup.mdx
- src/components/Button/__stories__/button.mdx
- src/components/Link/__stories__/Link.mdx
- src/storybook/components/related-components/component-description-map.tsx
- src/storybook/components/related-components/descriptions/badge-description.jsx
> docs(badge): add badge description on catelog page

- src/components/Tipseen/TipseenImage.tsx
https://monday.monday.com/boards/3532714909/pulses/5677193556
> feat: <TipseenImage> add tipseenMediaClassName

- src/components/IconButton/__stories__/IconButton.mdx
- src/storybook/components/related-components/component-description-map.tsx
- src/storybook/components/related-components/descriptions/icon-description.jsx
> docs(icon): add icon description on catalog page

- src/components/Toast/Toast.module.scss
- src/components/Toast/ToastConstants.ts
- src/components/Toast/__stories__/toast.mdx
- src/components/Toast/__stories__/toast.stories.js
https://monday.monday.com/boards/3532714909/pulses/4788061467
> feat: Add Toast dark variation

- README.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/5684800655?userId=52132154
> docs: remove release section from readme

- package-lock.json
- package.json
https://monday.monday.com/boards/3532714909/pulses/5686586370
> chore: update monday-ui-style

- src/storybook/components/related-components/component-description-map.tsx
- src/storybook/components/related-components/descriptions/slider-description.jsx
> docs(slider): add slider description on catalog page

- src/components/AttentionBox/AttentionBox.module.scss
- src/components/AttentionBox/AttentionBox.tsx
- src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.tsx.snap
Design request
https://monday.monday.com/boards/3532714909/pulses/5661772248
> fix(AttentionBox): fix layout and typography

- src/storybook/components/related-components/descriptions/virtualized-list-description/virtualized-list-description.jsx
https://monday.monday.com/boards/3532714909/pulses/5699041314
> docs: virtualized-list-description - fix import

- src/components/Chips/Chips.tsx
- src/components/Chips/__stories__/chips.stories.js
not removing for the meantime from `Chips.colors` as it is a breaking change
https://monday.monday.com/boards/3532714909/pulses/5581617323
> docs(Chips): remove colors which we don't want devs to use from docs

- src/components/Checkbox/Checkbox.module.scss
- src/components/Dropdown/Dropdown.styles.js
- src/components/RadioButton/RadioButton.module.scss
- src/components/TextField/TextField.module.scss
https://monday.monday.com/boards/3532714909/pulses/5668714684
> fix: add background color to form components

- src/storybook/components/related-components/descriptions/split-button-description.jsx
> fix: align <SplitButton> options in Catalog with overview example

- src/storybook/components/related-components/descriptions/icons-description.jsx
https://monday.monday.com/boards/3532714909/pulses/5699038497
> docs: RelatedComponents - fix icons-description.jsx href

- src/components/Box/Box.module.scss
- src/components/Box/Box.tsx
https://monday.monday.com/boards/3532714909/pulses/5713244678
> feat(Box): add a scrollable prop

- .storybook/main.ts
- .storybook/preview.tsx
- package-lock.json
- package.json
- src/storybook/stand-alone-documentaion/playground/Playground.stories.ts
https://monday.monday.com/boards/3532714909/pulses/5710798442
> docs: add playground addon for vibe's storybook

- src/components/Menu/Menu/Menu.tsx
https://monday.monday.com/boards/4317577777/views/98288257/pulses/5698952308
> type: change menu children type

- src/components/Box/Box.tsx
- src/components/Menu/Menu/Menu.tsx
https://monday.monday.com/boards/3532714909/pulses/5720753483
> fix: change Box/Menu children types to ElementContent

- src/storybook/components/related-components/component-description-map.tsx
- src/storybook/components/related-components/descriptions/box-description.jsx
> docs(box): add box description on catalog page

- .github/workflows/monorepo-prerelease.yml
https://monday.monday.com/boards/3532714909/pulses/5561513517
> infra: monorepo-prerelease.yml workflow

- src/storybook/components/related-components/descriptions/steps-description.jsx
- src/storybook/components/related-components/descriptions/tipseen-description.jsx
Updated the ```<Steps/>``` and ```<Tipseen/>``` component, made the button clickable.
Fixes : #1849 
[screen-capture.webm](https://github.com/mondaycom/monday-ui-react-core/assets/107350270/b578ea01-fb0a-4c5c-ab86-8a009c8ba27d)
> docs: Related components: fix < Steps />, < Tipseen /> - make examples clickable

- src/components/Dropdown/Dropdown.jsx
https://monday.monday.com/boards/3532714909/pulses/5739543914
> feat: <Dropdown> closeMenuOnScroll prop

- src/components/Dropdown/components/ChildrenContent/ChildrenContent.jsx
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
https://monday.monday.com/boards/3532714909/pulses/5740970821
> feat: <Dropdown> leftRenderer prop

- src/components/MenuButton/MenuButton.module.scss
https://monday.monday.com/boards/3532714909/pulses/4590288789
> fix: trigger scaling for menuButton only while clicking

- .github/workflows/check-pr-semantic-title.yml
https://monday.monday.com/boards/3532714909/pulses/5561513517
So we can start already getting used to semantic titles in the PRs :)
> ci: check-pr-semantic-title.yml workflow

- src/components/DatePicker/__tests__/DatePicker.jest.tsx
https://monday.monday.com/boards/3532714909/pulses/5762946414
> test(DatePicker): make tests more deterministic

- src/components/Accordion/Accordion/__stories__/accordion.mdx
- src/components/ExpandCollapse/__stories__/ExpandCollapse.mdx
- src/components/Modal/__stories__/modal.mdx
- src/components/Table/Table/__stories__/table.mdx
- src/storybook/components/related-components/component-description-map.tsx
- src/storybook/components/related-components/descriptions/table-description.tsx
https://monday.monday.com/boards/3532714909/pulses/5506774395
> docs: RelatedComponents - table-description.tsx

- src/components/Table/Table/Table.module.scss
- src/components/Table/Table/Table.tsx
- src/components/Table/Table/__stories__/table.mdx
- src/components/Table/Table/__stories__/table.stories.helpers.js
- src/components/Table/Table/__stories__/table.stories.js
- src/components/Table/Table/__stories__/table.stories.module.scss
https://monday.monday.com/boards/3532714909/pulses/5761975221
> feat(Table): add no border variant

- src/storybook/components/related-components/descriptions/menu-description.jsx
> docs: fix <Menu> link in catalog

- src/components/Table/Table/Table.tsx
- src/components/Table/Table/__tests__/tableHelpers.jest.tsx
- src/components/Table/Table/tableHelpers.ts
https://monday.monday.com/boards/3532714909/pulses/5788972371
> feat(Table): add option to supply %, fr, px as width for table

- src/components/Menu/MenuItem/MenuItem.module.scss
- src/components/Menu/MenuItem/MenuItem.tsx
https://monday.monday.com/boards/3532714909/pulses/5779094503
> feat(Label): add a disabled state to submenu button

- src/components/Label/Label.module.scss
- src/components/Label/__stories__/label.stories.js
- src/storybook/stand-alone-documentaion/catalog/catalog.stories.js
https://monday.monday.com/boards/3532714909/pulses/5778953616
> fix(Label): change padding according to design

- src/components/Dialog/__stories__/Dialog.stories.js
- src/components/ThemeProvider/__stories__/ThemeProvider.stories.js
https://monday.monday.com/boards/3532714909/pulses/5805122842
> docs: change sidebar organization

- src/components/EditableTypography/EditableTypography.tsx
Due to requests, to make it controlled, approved by designers
https://monday.monday.com/boards/3532714909/pulses/5804938292
> feat(EditableText): add isEditMode prop

- src/components/EditableTypography/EditableTypography.module.scss
- src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/5820510052
> feat(EditableTypography): expose mode change event

- src/storybook/stand-alone-documentaion/typography/typography.mdx
> docs: fix font weights in typography examples' mixin

- src/components/Table/TableCellSkeleton/TableCellSkeleton.tsx
https://monday.monday.com/boards/3532714909/pulses/5819198449
> fix(TableCellSkeleton): circle and rectangle loading types are broken (have width 0)

- src/components/Label/__stories__/label.mdx
- src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.tsx
#1879 
1. **Typo Fix**: Corrected a typographical error within the Label Component.
2. **Key Prop Warning Fixed**: Resolved the warning related to the missing unique `key` props within the Label Component, ensuring each child component has a unique identifier for improved rendering performance and management.
Resolved the following issue:
1. **Nested `<p>` Tag Warning**: Eliminated the warning indicating that a `<p>` tag cannot appear as a descendant of another `<p>` tag within the OtherContributorsList Component. The code was refactored to ensure proper HTML structure, resolving the nesting problem. This improvement ensures a more compliant and logical HTML structure within the component, addressing the warning related to incorrect `<p>` tag nesting.
> docs: fix typo in Label and and warning in OtherContributorsList

- package-lock.json
- package.json
- src/components/AttentionBox/AttentionBox.module.scss
- src/components/AvatarGroup/AvatarGroupCounter.module.scss
- src/components/Counter/Counter.module.scss
- src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
- src/components/Loader/Loader.module.scss
- src/components/ProgressBars/LinearProgressBar/LinearProgressBar.module.scss
- src/components/Skeleton/Skeleton.module.scss
- src/components/Tabs/Tab/Tab.module.scss
https://monday.monday.com/boards/3532714909/pulses/5804841496
> fix: replace primary-background-hover color in non-hover

- src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.module.scss
- src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
- src/components/AttentionBox/__stories__/attentionBox.stories.js
- src/components/Typography/Typography.module.scss
https://monday.monday.com/boards/3532714909/pulses/5835997259
> feat(AttentionBoxLink): use link component

- src/components/Avatar/AvatarBadge.tsx
https://monday.monday.com/boards/3532714909/pulses/5853663163
> feat(AvatarBadge): add an icon prop

- .gitignore
- package.json
https://monday.monday.com/boards/3532714909/pulses/5883381568
> chore(chromatic): add a command to run chromatic locally

- src/components/Menu/MenuItem/MenuItem.tsx
- src/components/MenuButton/MenuButton.tsx
https://monday.monday.com/boards/3532714909/pulses/5856465782
> feat: add tooltip props

- src/storybook/components/related-components/descriptions/editable-text-description.tsx
- src/storybook/components/related-components/descriptions/menu-button-description.jsx
https://monday.monday.com/boards/3532714909/pulses/5738081137
https://monday.monday.com/boards/3532714909/pulses/5740463166
> docs: Realated components fixes - editable text and menu button titles

- src/components/EditableTypography/EditableTypography.tsx
- src/components/Menu/MenuItem/MenuItem.tsx
- src/components/MenuButton/MenuButton.tsx
https://monday.monday.com/boards/3532714909/pulses/5898381159
> feat: add tooltip props to components

- src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
https://monday.monday.com/boards/3532714909/pulses/5882871307
> feat(TableVirtualizedBody): pass onScroll event

- src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/5898381159
> fix(EditableTypography): don't spread tooltipProps

- src/components/Tabs/TabList/TabList.module.scss
- src/components/Tabs/TabList/TabList.tsx
- src/components/Tabs/TabList/__tests__/__snapshots__/tabList-snapshot-tests.jest.js.snap
- src/components/Tabs/TabList/__tests__/tabList-snapshot-tests.jest.js
https://monday.monday.com/boards/3532714909/pulses/5919343286
> feat(TabList): add opt-out for default padding

- src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/5930813865
> fix: fix animation for menu with editable typography

- src/components/Menu/MenuItem/hooks/useMenuItemKeyboardEvents.ts
- src/components/MenuButton/MenuButton.tsx
https://monday.monday.com/boards/3532714909/pulses/5859293525
> fix(MenuButton): fix dialog close behavior

- src/components/Avatar/AvatarConstants.scss
https://monday.monday.com/boards/5820948294/pulses/5997371398
> fix(Avatar): changed medium avatar size

- src/components/Dropdown/Dropdown.jsx
- src/components/Dropdown/Dropdown.styles.js
- src/components/Dropdown/__stories__/dropdown.stories.js
https://monday.monday.com/boards/5820948294/pulses/5997344886
> feat(Dropdown): add withReadOnlyStyle prop

- src/components/EditableText/EditableText.tsx
- src/components/EditableText/__tests__/editableText-tests.jest.tsx
- src/components/EditableTypography/EditableTypography.module.scss
- src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/5994129551
> feat(EditableText): show placeholder when empty

- src/components/MenuButton/MenuButton.tsx
- src/components/MenuButton/__tests__/__snapshots__/menuButton.jest.js.snap
- src/components/MenuButton/__tests__/menuButton.jest.js
https://monday.monday.com/boards/3532714909/pulses/3539968129
> fix(MenuButton): tooltip should only appear on trigger element hover, not on dialog hover

- src/components/Label/Label.tsx
- src/components/Label/__tests__/__snapshots__/label-snapshot-tests.jest.tsx.snap
- src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
- src/components/Typography/Typography.module.scss
- src/components/Typography/TypographyConstants.ts
Hackathon - https://monday.monday.com/boards/5820948294/pulses/5998165794
Vibe board - https://monday.monday.com/boards/3532714909/pulses/5998705310
> feat(Label): support ellipsis

- src/components/MenuButton/MenuButton.tsx
https://monday.monday.com/boards/3532714909/pulses/6007072055
> fix(MenuButton): fix component type

- src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/6007451118
> feat(EditableTypography): send onEditModeChange when entering edit mode

- src/components/EditableText/__tests__/editableText-tests.jest.tsx
- src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/6009864338
> fix(EditableTypography): should call onChange with empty string when placeholder is used

- src/components/TextField/TextField.tsx
https://monday.monday.com/boards/3532714909/pulses/6016944708
> fix(TextField): avoid failing to cleanup on unmount, avoid inputRef is undefined

- src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
https://monday.monday.com/boards/3532714909/pulses/6018090488
> fix(TableVirtualizedBody): handle empty state when no items or items is an empty array

- src/components/Menu/MenuItem/MenuItem.tsx
https://monday.monday.com/boards/3532714909/pulses/6027956948
> fix(MenuItem): change condition of ariaLabel

- src/components/Badge/Badge.module.scss
https://monday.monday.com/boards/3532714909/pulses/6041668872
> feat(Badge): remove border on OUTSIDE alignment, remove translate on OUTSIDE alignment

- src/components/IconButton/IconButton.tsx
- src/components/IconButton/__tests__/iconButton-tests.jest.tsx
https://monday.monday.com/boards/3532714909/pulses/6025208860
> feat(IconButton): add aria-hidden prop

- src/components/Button/Button.tsx
- src/components/Button/__tests__/button.jest.js
- src/components/IconButton/IconButton.tsx
- src/components/IconButton/__tests__/iconButton-tests.jest.tsx
https://monday.monday.com/boards/3532714909/pulses/6025209249
> feat(Button): add aria-hidden prop

- .github/workflows/ci.yml
> ci(ci): name the job run with a readable, cleaner one

- packages/core/src/components/AlertBanner/AlertBanner.tsx
https://monday.monday.com/boards/3532714909/pulses/6071653631
> fix(AlertBanner): fix children type

- packages/core/src/components/EditableText/__tests__/editableText-tests.jest.tsx
- packages/core/src/components/EditableTypography/EditableTypography.tsx
https://monday.monday.com/boards/3532714909/pulses/6086211430
> fix(EditableTypography): react to value prop change

- packages/core/src/components/Tipseen/Tipseen.module.scss
- packages/core/src/components/Tipseen/TipseenTitle.module.scss
- packages/core/src/components/Tipseen/TipseenTitle.tsx
- packages/core/src/components/Tipseen/__tests__/__snapshots__/tipseen-tests.jest.js.snap
https://monday.monday.com/boards/3532714909/pulses/6086203642
> fix(Tipseen): add gap between title and close button

- package.json
- packages/core/.storybook/main.ts
https://monday.monday.com/boards/3532714909/pulses/6090984610
> chore: local monorepo env

- .github/workflows/publish-storybook.yml
- .gitignore
https://monday.monday.com/boards/3532714909/pulses/6085919277
> ci: storybooks publish

- packages/core/src/components/Button/Button.module.scss
- packages/core/src/components/Button/ButtonConstants.ts
https://monday.monday.com/boards/3532714909/pulses/6044871004
> feat(button): add inverted color to button

- packages/style/src/config/tokens/themes/basic/keys/_keys.scss
- packages/style/src/config/tokens/themes/black/keys/_black-theme-keys.scss
- packages/style/src/config/tokens/themes/dark/keys/_dark-theme-keys.scss
https://monday.monday.com/boards/3532714909/pulses/5201142530
Replacing https://github.com/mondaycom/monday-ui-style/pull/249 due to monorepo
> feat(colors): change primary-background-hover-color for all themes

- packages/core/src/components/Flex/Flex.module.scss
- packages/core/src/components/Flex/FlexConstants.ts
> feat(Flex): new align's value - baseline

- .github/workflows/publish-storybook.yml
https://monday.monday.com/boards/3532714909/pulses/6194209188
> ci(publish-storybook): build should always run

- packages/core/src/components/Button/Button.tsx
https://monday.monday.com/boards/3532714909/pulses/6194425851
reference:
https://dequeuniversity.com/rules/axe/4.8/aria-hidden-focus
> feat(Button): when aria-hidden is true, button should behave as disabled (solves a11y issue)

- packages/core/src/components/Button/__tests__/__snapshots__/button-snapshot-tests.jest.js.snap
https://monday.monday.com/boards/3532714909/pulses/6227910900
> test: update snapshot

- packages/core/src/components/AvatarGroup/AvatarGroup.tsx
- packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
https://monday.monday.com/boards/3532714909/pulses/6234996352
> feat(AvatarGroupCounter): pass noAnimation prop

- README.md
> docs: repo renaming announcement

- packages/core/package.json
- yarn.lock
https://monday.monday.com/boards/3532714909/pulses/6302785169
> chore: upgrade playground addon

- packages/core/src/components/MultiStepIndicator/MultiStepIndicator.module.scss
Fixes #2001 
https://monday.monday.com/boards/3532714909/pulses/6288517251
> fix(MultiStepIndicator): nest divider style

- packages/storybook-blocks/package.json
- packages/storybook-blocks/rollup.config.js
https://monday.monday.com/boards/3532714909/pulses/6318081724
> fix(build): dist

- packages/core/src/components/EditableHeading/__stories__/EditableHeading.mdx
https://monday.monday.com/boards/3532714909/pulses/6086130105
> docs(EditableHeading): add import documentation

- packages/core/src/components/Label/Label.module.scss
- packages/core/src/components/Label/Label.tsx
https://monday.monday.com/boards/3532714909/pulses/6390981883
> fix(Label): changes selectors

- packages/core/CONTRIBUTING.md
- packages/core/README.md
- packages/core/TESTING_README.md
- packages/storybook-blocks/CONTRIBUTING.md
- packages/storybook-blocks/README.md
- packages/style/README.md
https://monday.monday.com/boards/3532714909/pulses/6409895591
> docs: change npm to yarn

- packages/core/src/storybook/components/related-components/descriptions/dialog-description/dialog-description.tsx
https://monday.monday.com/boards/3532714909/pulses/6426535031
> docs: fix related components link

- packages/core/src/components/ExpandCollapse/ExpandCollapse.module.scss
https://monday.monday.com/boards/3532714909/pulses/6303695186
> fix(ExpandCollapse): remove no-longer-needed css scale workaround

- packages/core/src/storybook/decorators/withLiveEdit/withLiveEdit.tsx
https://monday.monday.com/boards/3532714909/pulses/6461983625
> chore(withLiveEdit): should not throw errors on stories that do not include LiveEdit

- packages/core/src/components/AttentionBox/__stories__/attentionBox.stories.js
- packages/core/src/components/BaseInput/BaseInput.module.scss
- packages/core/src/components/Chips/__stories__/chips.stories.js
- packages/core/src/components/Combobox/Combobox.module.scss
- packages/core/src/components/Combobox/Combobox.tsx
- packages/core/src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
- packages/core/src/components/Combobox/__tests__/combobox-interactions.js
- packages/core/src/components/Heading/__stories__/Heading.stories.js
- packages/core/src/components/Icon/__stories__/IconsList.tsx
- packages/core/src/components/LegacyHeading/__stories__/LegacyHeading.stories.tsx
- packages/core/src/components/LegacySearch/__stories__/LegacySearch.stories.tsx
- packages/core/src/components/Menu/Menu/__stories__/Menu.stories.helpers.tsx
- packages/core/src/components/ResponsiveList/__stories__/ResponsiveList.stories.js
- packages/core/src/components/Search/Search.module.scss
- packages/core/src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.stories.js
- packages/core/src/hooks/useActiveDescendantListFocus/__tests__/useActiveDescendantListFocus.interactions.js
- packages/core/src/storybook/components/related-components/descriptions/search-description.jsx
- packages/core/src/storybook/stand-alone-documentaion/catalog/Catalog/Catalog.stories.templates.module.scss
- packages/core/src/storybook/stand-alone-documentaion/catalog/Catalog/Catalog.stories.templates.tsx
https://monday.monday.com/boards/3532714909/pulses/6450989453
> feat: migrate usages of LegacySearch to new Search

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- README.md
- packages/core/CONTRIBUTING.md
- packages/core/package.json
- packages/core/src/storybook/stand-alone-documentaion/welcome/abilities-description/abilities-description.jsx
- packages/core/src/storybook/stand-alone-documentaion/welcome/welcome.mdx
- packages/storybook-blocks/CONTRIBUTING.md
- packages/storybook-blocks/README.md
- packages/storybook-blocks/package.json
- packages/style/package.json
To be merged after the actual rename
https://monday.monday.com/boards/3532714909/pulses/6062841042
> chore: rename references to vibe repo

- packages/core/src/components/Dialog/Dialog.tsx
https://monday.monday.com/boards/3532714909/pulses/6514184411
> fix(Dialog): prevent default for contextmenu event

- packages/core/src/next/next.ts
https://monday.monday.com/boards/3532714909/pulses/6461983625
> fix: export Search from next

- packages/core/src/components/Button/Button.module.scss
- packages/core/src/components/SplitButton/SplitButton.module.scss
https://monday.monday.com/boards/3532714909/pulses/6044021804
> feat(Button): add active-hover state to buttons

- .github/workflows/chromatic.yml
https://monday.monday.com/boards/3532714909/pulses/6479539903
> ci(chromatic): exit action when upload is done - as we're using the github<->chromatic integration

- .gitignore
- packages/core/rollup.config.js
https://monday.monday.com/boards/3532714909/pulses/6494898327
> chore: remove unused files from dist

- packages/core/src/components/Menu/MenuItem/MenuItem.tsx
- packages/core/src/components/Menu/MenuItem/__tests__/MenuItem.jest.js
https://monday.monday.com/boards/3532714909/pulses/6481701216
> fix(MenuItem): disabled item should not show its submenu

- packages/core/src/components/Avatar/Avatar.tsx
complete this task so it's possible to pass only some of TooltipProps to the Avatar component.
https://github.com/mondaycom/vibe/issues/2083
> types: change tooltipProps type to Partial<TooltipProps>

- packages/core/src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
- packages/core/src/components/Menu/MenuItem/MenuItem.tsx
- packages/core/src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/MenuItemSubMenu.tsx
- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/MenuItemSubMenu.types.ts
- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/__tests__/MenuItemSubMenu.jest.tsx
- packages/core/src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/splitButtonMenu-snapshot-tests.jest.tsx.snap
https://monday.monday.com/boards/3532715121/pulses/6584581926
> refactor(MenuItem): separate SubMenu logic from MenuItem

- packages/core/src/components/TextWithHighlight/TextWithHighlight.tsx
https://monday.monday.com/boards/3532714909/pulses/6608291661
> fix(TextWIthHighlight): escape regex

- packages/core/src/components/ResponsiveList/__stories__/ResponsiveList.mdx
https://monday.monday.com/boards/3532714909/pulses/6549360614
> fix(Storybook Docs): typo

- packages/core/src/components/Typography/Typography.module.scss
https://monday.monday.com/boards/3532714909/pulses/6610893363
> fix(Typography): make anchor style apply only to direct child

- packages/core/src/components/AlertBanner/AlertBanner.tsx
- packages/core/src/components/AlertBanner/__tests__/__snapshots__/AlertBanner-snapshots.test.js.snap
- packages/core/src/components/AlertBanner/__tests__/__snapshots__/alertBanner-snapshot-tests.test.js.snap
https://monday.monday.com/boards/3532714909/views/113186840/pulses/5414954008
> fix(AlertBanner): replace Button & Icon with IconButton

- packages/core/src/components/Tabs/TabsContext/TabsContext.tsx
https://monday.monday.com/boards/3532714909/pulses/6652721498
> fix(TabsContext): use onTabChange from child props

- packages/core/src/components/TextArea/TextArea.module.scss
https://monday.monday.com/boards/3532714909/pulses/6672646525
> fix(TextArea): add background color and text for dark mode

- packages/core/package.json
- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.mdx
- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.js
- yarn.lock
- also upgrades storybook-addon-playground on-the-way
https://monday.monday.com/boards/3532715121/pulses/6669367694
> docs(AvatarGroup): enable live edit

- .github/actions/git-creds/action.yml
- .github/workflows/release.yml
> Revert "ci: use VIBE_GITHUB_TOKEN"

- packages/core/src/components/Box/Box.tsx
https://monday.monday.com/boards/3532714909/pulses/6726141912
> feat(Box): add style prop

- packages/core/src/next/next.ts
https://monday.monday.com/boards/3532714909/pulses/6086045892
> fix: export next components types

- packages/core/src/components/ResponsiveList/ResponsiveList.tsx
- packages/core/webpack/published-js-components.js
- packages/core/webpack/published-ts-components.js
https://monday.monday.com/boards/3532714909/pulses/6757149277
> fix(ResponsiveList): add static props for backwards

- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
- packages/core/src/tests/constants.ts
https://monday.monday.com/boards/3532714909/pulses/6717711482
> feat(Table): apply vibe component props in TableVirtualizedBody

- packages/core/src/components/Icon/__stories__/IconsList.tsx
- packages/style/src/Icons/iconsMetaData.js
https://monday.monday.com/boards/3532714909/pulses/6842873441
> docs(Icons): remove Upgrade from catalog

- packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/core/src/components/TextField/index.ts
- packages/core/src/hooks/useSetFocus/__stories__/useSetFocus.stories.tsx
https://monday.monday.com/boards/6010627825/pulses/6471336100
> chore: remove InputField [BREAKING]

- packages/core/src/components/Link/Link.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6891175104
> fix(link): hover color should inherit from link color

- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
https://monday.monday.com/boards/3532714909/pulses/6277634529
>  fix(dropdown): Dropdown multi size "small" style and behavior is broken

- packages/core/src/components/Button/Button.module.scss
https://monday.monday.com/boards/3532714909/pulses/6900393385
Before:
After:
> fix(Button): fix text placeholder dimensions in loading state

- packages/core/src/components/TextArea/TextArea.module.scss
- packages/core/src/components/TextArea/TextArea.tsx
- packages/core/src/components/TextArea/TextArea.types.ts
https://monday.monday.com/boards/3532714909/pulses/6899262204
> feat(TextArea): be able to disable resize

- packages/storybook-blocks/package.json
https://monday.monday.com/boards/3532714909/pulses/6900442174
> chore: add build step postinstall for vibe-storybook-components

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Tooltip/Tooltip.tsx
- packages/core/src/components/Tooltip/TooltipConstants.ts
- packages/core/src/components/Tooltip/__tests__/Tooltip.snapshot.test.tsx
- packages/core/src/components/Tooltip/__tests__/__snapshots__/Tooltip.snapshot.test.tsx.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6890238631
> chore(tooltip): remove arrowPosition

- packages/core/CHANGELOG.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6907911155
> docs(changelog): add missing pr

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Slider/__tests__/__snapshots__/Slider-non-ranged.test.js.snap
- packages/core/src/components/Slider/__tests__/__snapshots__/Slider-ranged.test.js.snap
- packages/core/src/components/Tipseen/Tipseen.tsx
- packages/core/src/components/Tipseen/__tests__/__snapshots__/Tipseen.test.js.snap
- packages/core/src/components/Tooltip/Tooltip.tsx
- packages/core/src/components/Tooltip/__tests__/Tooltip.snapshot.test.tsx
- packages/core/src/components/Tooltip/__tests__/__snapshots__/Tooltip.snapshot.test.tsx.snap
- packages/core/src/constants/dialog.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6890236950
> chore(tooltip): remove justify prop

- packages/core/src/components/Table/Table/Table.tsx
- packages/core/src/components/Table/Table/TableRoot.module.scss
- packages/core/src/components/Table/Table/TableRoot.tsx
- packages/core/src/components/Table/Table/__stories__/Table.stories.helpers.tsx
- packages/core/src/components/Table/Table/__tests__/Table.test.tsx
- packages/core/src/components/Table/TableCell/TableCell.module.scss
- packages/core/src/components/Table/TableCell/TableCell.tsx
- packages/core/src/components/Table/TableHeader/TableHeader.module.scss
- packages/core/src/components/Table/TableHeader/TableHeader.tsx
- packages/core/src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
- packages/core/src/components/Table/TableHeaderCell/TableHeaderCell.tsx
- packages/core/src/components/Table/TableRow/TableRow.module.scss
- packages/core/src/components/Table/TableRow/TableRow.tsx
- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
- packages/core/src/components/Table/context/TableContext/TableContext.tsx
- packages/core/src/components/Table/context/TableContext/TableContext.types.ts
- packages/core/src/components/Table/index.ts
Works for both non and virtualized tables
https://monday.monday.com/boards/3532714909/pulses/6717612609
https://github.com/mondaycom/vibe/assets/30905362/081eefb3-028f-48c1-8a0c-ef88b006487a
> feat(Table): add sticky column capabilities

- packages/core/src/components/Toast/ToastLink/ToastLink.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6891175104
> fix(ToastLink): hover color should inherit from link color

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Box/Box.module.scss
- packages/core/src/components/Box/Box.tsx
- packages/core/src/components/Box/__tests__/__snapshots__/Box.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6887644042
> chore(Box): make scrollable default true

- packages/core/src/components/ExpandCollapse/ExpandCollapse.module.scss
https://monday.monday.com/boards/3532714909/pulses/6937929380
> fix(ExpandCollapse): component gets to 95% scale when active

- packages/core/src/components/Table/Table/Table.module.scss
- packages/core/src/components/Table/TableHeaderCell/TableHeaderCell.module.scss
- packages/core/src/components/Table/TableRow/TableRow.module.scss
https://monday.monday.com/boards/3532714909/pulses/6934229625
Before:
> fix(Table): sticky cell is seen-through when hovered

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Menu/MenuItem/MenuItem.tsx
- packages/core/src/components/Modal/Modal.tsx
- packages/core/src/components/Modal/__tests__/Modal.test.js
https://monday.monday.com/boards/3532714909/pulses/6887875560
> chore(Modal): remove unmountOnClose and make default behavior

- packages/core/src/components/Accordion/AccordionItem/AccordionItem.tsx
- packages/core/src/components/ExpandCollapse/ExpandCollapse.tsx
- packages/core/src/components/ExpandCollapse/__tests__/__snapshots__/ExpandCollapse.test.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6947522708
> feat(AccordionItem): add option for onClick instead of onClickCapture

- package.json
https://monday.monday.com/boards/3532714909/pulses/6900442174
> chore: build storybook-components package on monorepo install

- packages/core/src/components/AlertBanner/__stories__/AlertBanner.mdx
- packages/core/src/components/Checkbox/__stories__/Checkbox.mdx
- packages/core/src/storybook/stand-alone-documentaion/accessibility/accessibility.mdx
https://monday.monday.com/boards/3532714909/pulses/6958852313
> docs: fix typos

- packages/core/src/components/Combobox/components/ComboboxItems/ComboboxItems.module.scss
https://monday.monday.com/boards/3532714909/pulses/7004499070
> fix(Combobox): spacings in categories

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Tipseen/TipseenConstants.ts
- packages/core/src/components/Tipseen/TipseenContent.tsx
https://monday.monday.com/boards/3532714909/pulses/6965588862
> chore(Tipseen): remove deprecated props [breaking]

- packages/core/src/components/TextField/TextField.tsx
https://monday.monday.com/boards/3532714909/pulses/7035581219
> feat(TextField): send native event if applicable in onChange

- packages/core/src/components/Menu/Menu/Menu.tsx
> feat(Menu): add on focus to menu

- packages/core/src/components/TextWithHighlight/TextWithHighlight.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7064834387
> fix(textWithHighlight): Fix ellipsis when no breaks in string

- packages/core/src/components/TextWithHighlight/TextWithHighlight.tsx
https://monday.monday.com/boards/3532714909/views/80492480
> fix(textWithHighlight): Fix linesToClamp not working properly

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/Dropdown.types.ts
- packages/core/src/components/Dropdown/__tests__/Dropdown.snapshot.test.js
https://monday.monday.com/boards/3532714909/pulses/7049284408
> chore(Dropdown): remove size property

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/ColorPicker/__tests__/__snapshots__/ColorPicker.test.tsx.snap
- packages/core/src/components/DialogContentContainer/DialogContentContainer.module.scss
- packages/core/src/components/DialogContentContainer/DialogContentContainer.tsx
- packages/core/src/components/DialogContentContainer/__tests__/__snapshots__/DialogContentContainer.test.tsx.snap
https://monday.monday.com/boards/3532714909/pulses/7020937327
> fix(DialogContentContainer): fix size medium spacing

- packages/codemod/src/utils/report-utils.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/chips-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/chips-component-migration.ts
https://monday.monday.com/boards/3532714909/pulses/6958116561
> chore(Chips): codemod for migration of Chips from core - v2 to v3

- packages/core/src/components/DatePicker/DatePicker.tsx
- packages/core/src/components/DatePicker/external_datepicker.scss
https://monday.monday.com/boards/4400799549/pulses/6799260682
> fix: fix style linter

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
- packages/core/src/components/Link/Link.tsx
- packages/core/src/components/Link/__tests__/Link.test.tsx
https://monday.monday.com/boards/3532714909/pulses/7049281390
> chore: remove Link.target static prop

- packages/core/src/components/Dropdown/Dropdown.styles.js
https://monday.monday.com/boards/3532714909/views/80492480/pulses/6959583810
> fix(dropdown): fix blur border color

- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
- packages/core/src/components/Dropdown/components/ChildrenContent/ChildrenContent.jsx
- packages/core/src/components/Dropdown/components/ChildrenContent/ChildrenContent.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7031893214
> fix(dropdown): Fix ellipsis not to working for simple text dropdown

- packages/core/package.json
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/__tests__/Dropdown.snapshot.test.js
- packages/core/src/components/Dropdown/dropdownUtils.ts
- yarn.lock
There seems to be an [issue](https://github.com/ai/nanoid/issues/462) with nanoid v3 in jest. I used something more simple for now, the probability is still extremely low, definitely for this use case
> fix: replace nanoid

- packages/core/src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.helpers.tsx
https://monday.monday.com/boards/3532714909/pulses/7093468949
> docs: fix story

- packages/core/src/components/Combobox/Combobox.tsx
> feat: add `filterValue` prop to Combobox

- packages/core/src/components/AvatarGroup/AvatarGroup.tsx
- packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.js
- packages/core/src/components/Badge/Badge.tsx
- packages/core/src/components/Counter/Counter.tsx
- packages/core/src/components/Counter/Counter.types.ts
- packages/core/src/components/Counter/CounterConstants.ts
- packages/core/src/components/Counter/__stories__/Counter.stories.tsx
- packages/core/src/components/Counter/__tests__/Counter.snapshot.test.tsx
- packages/core/src/components/Counter/index.ts
- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021049229
> chore(Counter): deprecate enums

- packages/core/src/components/AttentionBox/AttentionBoxLink/AttentionBoxLink.tsx
- packages/core/src/components/Badge/__stories__/Badge.stories.tsx
- packages/core/src/components/Link/Link.tsx
- packages/core/src/components/Link/Link.types.ts
- packages/core/src/components/Link/LinkConsts.ts
- packages/core/src/components/Link/__stories__/Link.mdx
- packages/core/src/components/Link/__stories__/Link.stories.tsx
- packages/core/src/components/Link/__tests__/Link.snapshot.test.tsx
- packages/core/src/components/Link/__tests__/Link.test.tsx
- packages/core/src/components/Link/index.ts
- packages/core/src/storybook/components/related-components/descriptions/link-description.jsx
- packages/core/src/storybook/stand-alone-documentaion/typography/typography-migration-guide.mdx
- packages/core/src/storybook/stand-alone-documentaion/welcome/contributor/contributor.jsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021050590
> chore(Link): deprecate enums

- packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/core/src/components/Label/Label.tsx
- packages/core/src/components/Label/Label.types.ts
- packages/core/src/components/Label/LabelConstants.ts
- packages/core/src/components/Label/__stories__/Label.mdx
- packages/core/src/components/Label/__stories__/Label.stories.tsx
- packages/core/src/components/Label/__tests__/Label.snapshot.test.tsx
- packages/core/src/components/Label/index.ts
- packages/core/src/components/Menu/MenuItem/MenuItem.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021050514
> chore(Label): deprecate enums

- packages/core/src/components/ProgressBars/LinearProgressBar/Bar/Bar.tsx
- packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
- packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBar.types.ts
- packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBarConstants.ts
- packages/core/src/components/ProgressBars/LinearProgressBar/__stories__/LinearProgressBar.stories.tsx
- packages/core/src/components/ProgressBars/LinearProgressBar/__tests__/LinearProgressBar.snapshot.test.js
- packages/core/src/components/ProgressBars/index.ts
- packages/core/src/components/Tabs/Tab/__tests__/Tab.test.tsx
https://monday.monday.com/boards/3532714909/pulses/7021051282
> chore(LinearProgressBar): deprecate enums

- packages/core/.storybook/main.ts
- packages/core/package.json
- yarn.lock
https://monday.monday.com/boards/3532714909/pulses/7109392719
Better than nothing
> docs: add storysource addon

- packages/core/src/components/ThemeProvider/ThemeProvider.tsx
- packages/core/src/components/ThemeProvider/ThemeProvider.types.ts
- packages/core/src/components/ThemeProvider/ThemeProviderConstants.ts
- packages/core/src/components/ThemeProvider/ThemeProviderUtils.ts
- packages/core/src/components/ThemeProvider/__stories__/ThemeProvider.stories.helpers.tsx
- packages/core/src/components/ThemeProvider/__stories__/ThemeProvider.stories.tsx
- packages/core/src/components/ThemeProvider/index.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021052137
> chore(ThemeProvider): deprecate enums

- packages/core/src/components/Menu/MenuTitle/MenuTitle.tsx
- packages/core/src/components/Menu/MenuTitle/MenuTitle.type.ts
- packages/core/src/components/Menu/MenuTitle/MenuTitleConstants.ts
- packages/core/src/components/Menu/MenuTitle/__stories__/MenuTitle.stories.tsx
- packages/core/src/components/Menu/index.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021050850
> chore(Menu): deprecate enums

- packages/core/src/components/TextArea/TextArea.tsx
- packages/core/src/components/TextArea/TextArea.types.ts
> feat: added placeholder to textarea

- packages/core/src/components/Menu/MenuItem/MenuItem.Types.ts
- packages/core/src/components/Menu/MenuItem/MenuItem.tsx
- packages/core/src/components/Menu/MenuItem/__tests__/MenuItem.test.js
- packages/core/src/components/Menu/MenuItem/components/BaseMenuItem/BaseMenuItem.tsx
- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/MenuItemSubMenu.tsx
- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/MenuItemSubMenu.types.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7110141799
> feat(Menu): allow setting submenu position to left

- packages/core/babel.config.js
- packages/core/jest.init.js
https://monday.monday.com/boards/3532714909/pulses/7142037428
> build: remove targets - it should inherit the ones from browserslist in package.json

- packages/core/src/components/Badge/Badge.tsx
- packages/core/src/components/Badge/Badge.types.ts
- packages/core/src/components/Badge/BadgeConstants.ts
- packages/core/src/components/Badge/Indicator/Indicator.tsx
- packages/core/src/components/Badge/Indicator/Indicator.types.ts
- packages/core/src/components/Badge/Indicator/IndicatorConstants.ts
- packages/core/src/components/Badge/__stories__/Badge.mdx
- packages/core/src/components/Badge/__stories__/Badge.stories.tsx
- packages/core/src/components/Badge/__tests__/Badge.snapshot.test.tsx
- packages/core/src/components/Badge/__tests__/__snapshots__/Badge.snapshot.test.tsx.snap
- packages/core/src/components/Badge/index.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021048191
> chore(Badge): deprecate enums

- packages/core/COMPONENTS_DOCUMENTATION_GUIDELINES.md
- packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/core/src/components/Loader/Loader.tsx
- packages/core/src/components/Loader/Loader.types.ts
- packages/core/src/components/Loader/LoaderConstants.ts
- packages/core/src/components/Loader/__stories__/Loader.mdx
- packages/core/src/components/Loader/__stories__/Loader.stories.tsx
- packages/core/src/components/Loader/__tests__/Loader.snapshot.test.js
- packages/core/src/components/Loader/index.ts
- packages/core/src/components/Search/Search.tsx
- packages/core/src/components/Toast/Toast.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021050773
> chore(Loader): deprecate enums

- packages/core/src/components/Modal/Modal.tsx
- packages/core/src/components/Modal/Modal.types.ts
- packages/core/src/components/Modal/ModalHelper.ts
- packages/core/src/components/Modal/__stories__/Modal.stories.helpers.tsx
- packages/core/src/components/Modal/__stories__/Modal.stories.tsx
- packages/core/src/components/Modal/__tests__/Modal.snapshot.test.js
- packages/core/src/components/Modal/__tests__/__snapshots__/Modal.snapshot.test.js.snap
- packages/core/src/components/Modal/index.ts
https://monday.monday.com/boards/3532714909/pulses/7021051002
> chore(Modal): deprecate enums

- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/Dropdown.types.ts
- packages/core/src/components/Dropdown/DropdownConstants.ts
- packages/core/src/components/Dropdown/__stories__/Dropdown.mdx
- packages/core/src/components/Dropdown/__stories__/Dropdown.stories.js
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021050216
> chore(Dropdown): deprecate enums

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/Dropdown.types.ts
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/pulses/7139919911
> feat(Dropdown): remove xxs and xs sizes

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Tipseen/Tipseen.tsx
https://monday.monday.com/boards/3532714909/pulses/7049282971
> types(Tipseen): make content required

- packages/core/src/components/Table/Table/Table.tsx
- packages/core/src/components/Table/Table/Table.types.ts
- packages/core/src/components/Table/Table/TableConsts.ts
- packages/core/src/components/Table/Table/TableRoot.tsx
- packages/core/src/components/Table/Table/__stories__/Table.stories.helpers.tsx
- packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
- packages/core/src/components/Table/Table/__tests__/Table.test.tsx
- packages/core/src/components/Table/Table/__tests__/tableTestUtils.tsx
- packages/core/src/components/Table/Table/tableHelpers.ts
- packages/core/src/components/Table/TableBody/TableBody.tsx
- packages/core/src/components/Table/TableCell/TableCell.tsx
- packages/core/src/components/Table/TableHeader/TableHeader.tsx
- packages/core/src/components/Table/TableHeaderCell/TableHeaderCell.tsx
- packages/core/src/components/Table/TableRow/TableRow.tsx
- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
- packages/core/src/components/Table/context/TableContainerContext/TableContainerContext.tsx
- packages/core/src/components/Table/context/TableContainerContext/TableContainerContext.types.ts
- packages/core/src/components/Table/context/TableContext/TableContext.tsx
- packages/core/src/components/Table/context/TableContext/TableContext.types.ts
- packages/core/src/components/Table/context/TableRowMenuContext/TableRowMenuContext.tsx
- packages/core/src/components/Table/context/TableRowMenuContext/TableRowMenuContext.types.ts
- packages/core/src/components/Table/index.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021051695
> chore(Table): deprecate enums

- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.js
- packages/core/src/components/Slider/SelectionIndicator.tsx
- packages/core/src/components/Slider/Slider.tsx
- packages/core/src/components/Slider/Slider.types.ts
- packages/core/src/components/Slider/SliderBase/SliderFilledTrack.tsx
- packages/core/src/components/Slider/SliderBase/SliderRail.tsx
- packages/core/src/components/Slider/SliderBase/SliderThumb.tsx
- packages/core/src/components/Slider/SliderBase/SliderTrack.tsx
- packages/core/src/components/Slider/SliderConstants.ts
- packages/core/src/components/Slider/SliderInfixHooks.tsx
- packages/core/src/components/Slider/__stories__/Slider.stories.tsx
- packages/core/src/components/Slider/__tests__/Slider.snapshot.test.js
- packages/core/src/components/Slider/index.ts
https://monday.monday.com/boards/3532714909/pulses/7021051485
> chore(Slider): deprecate enums

- packages/core/src/components/Combobox/Combobox.tsx
- packages/core/src/components/Combobox/Combobox.types.ts
- packages/core/src/components/Combobox/__stories__/Combobox.stories.tsx
- packages/core/src/components/Combobox/__tests__/Combobox.snapshot.test.js
- packages/core/src/components/Combobox/components/ComboboxConstants.ts
- packages/core/src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx
- packages/core/src/components/Combobox/index.ts
- packages/core/src/components/Search/__stories__/Search.stories.tsx
- packages/core/src/storybook/components/related-components/descriptions/combobox-description.jsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021048959
> chore(Combobox): deprecate enums

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Tabs/TabList/TabList.module.scss
- packages/core/src/components/Tabs/TabList/TabList.tsx
- packages/core/src/components/Tabs/TabList/__tests__/TabList.snapshot.test.js
- packages/core/src/components/Tabs/TabList/__tests__/__snapshots__/TabList.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/pulses/7157049424
> feat(TabList): remove noPadding prop

- packages/core/src/components/Avatar/Avatar.tsx
- packages/core/src/components/Avatar/__stories__/Avatar.stories.tsx
- packages/core/src/components/Chips/__stories__/Chips.stories.tsx
- packages/core/src/components/Counter/__stories__/Counter.stories.tsx
- packages/core/src/components/List/__stories__/List.stories.tsx
- packages/core/src/components/Table/Table/__stories__/Table.stories.helpers.tsx
- packages/core/src/storybook/stand-alone-documentaion/playground/react-docgen-output.json
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021048070
> chore(Avatar): deprecate color enums

- packages/core/docs/vibe-3-changelog.md
- packages/style/src/files/colors.json
https://monday.monday.com/boards/3532714909/pulses/7157053449
> chore: remove color-warning

- packages/core/src/components/Menu/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
- packages/core/src/components/Menu/MenuItem/MenuItem.tsx
- packages/core/src/components/Menu/MenuItem/__tests__/MenuItem.test.js
- packages/core/src/components/Menu/MenuItem/__tests__/__snapshots__/MenuItem.snapshot.test.tsx.snap
- packages/core/src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/SplitButtonMenu.snapshot.test.tsx.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7077366107
> feat(MenuItem): Add all label capabilities to menu item

- packages/core/src/components/Combobox/Combobox.tsx
https://monday.monday.com/boards/3532714909/pulses/7041131964
> feat(combobox): Add render action to combobox

- packages/core/src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.module.scss
- packages/core/src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.tsx
- packages/core/src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.tsx
https://monday.monday.com/boards/3532714909/pulses/7064472617
> feat(Breadcrumbs): be able to show only the icon

- packages/core/src/components/List/List.module.scss
https://monday.monday.com/boards/3532714909/pulses/7170736155
> fix(List): add font smoothing

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/hooks/useSwitch/__tests__/useSwitch.test.ts
- packages/core/src/hooks/useSwitch/index.ts
https://monday.monday.com/boards/3532714909/pulses/7177916854
> chore(useSwitch): change type

- packages/core/src/components/ResponsiveList/ResponsiveList.tsx
- packages/core/src/components/Tipseen/Tipseen.tsx
- packages/core/src/components/Tooltip/Tooltip.tsx
- packages/core/src/utils/warn-deprecated.ts
https://monday.monday.com/boards/3532714909/pulses/7049313425
> chore: add deprecation warnings

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Counter/Counter.tsx
- packages/core/src/components/Counter/CounterConstants.ts
- packages/core/src/components/TextField/TextField.tsx
- packages/core/src/components/TextField/TextFieldConstants.ts
https://monday.monday.com/boards/3532714909/pulses/7202857183
> chore: remove backwards sizes support

- packages/core/babel.config.js
- packages/core/jest.init.js
> fix: targets for storybook

- packages/core/src/components/Modal/Modal.tsx
https://monday.monday.com/boards/3532714909/pulses/7202868372
> chore(Modal): warn about unmountOnClose

- packages/core/src/components/Tipseen/Tipseen.tsx
- packages/core/src/components/Tooltip/Tooltip.tsx
https://monday.monday.com/boards/3532714909/pulses/7202884541
> chore: remove deprecation warnings

- packages/core/src/components/Table/Table/__stories__/Table.mdx
- packages/core/src/components/Table/Table/__stories__/Table.stories.helpers.tsx
- packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/7222994760
> docs(Table): add a sticky story

- packages/codemod/transformations/core/v2-to-v3/__tests__/counter-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/counter-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232289370
> chore(Counter): codemod for migration of props

- packages/codemod/transformations/core/v2-to-v3/__tests__/divider-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/divider-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232165551
> chore(Divider): codemod for migration of props

- packages/codemod/transformations/core/v2-to-v3/__tests__/breadcrumb-item-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/breadcrumb-item-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232187169
> chore(BreadcrumbItem): codemod for migration of props

- packages/core/src/components/Chips/Chips.module.scss
- packages/core/src/components/Chips/Chips.tsx
- packages/core/src/components/Chips/__tests__/__snapshots__/Chips.snapshot.test.tsx.snap
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/pulses/7093079940
> feat(Chips): change chips spacing and size

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Box/Box.tsx
- packages/core/src/components/Box/Box.types.ts
- packages/core/src/components/Box/BoxConstants.ts
- packages/core/src/components/Box/__stories__/Box.stories.tsx
- packages/core/src/components/Box/__tests__/Box.snapshot.test.tsx
- packages/core/src/components/Box/__tests__/__snapshots__/Box.snapshot.test.tsx.snap
- packages/core/src/components/Box/index.ts
- packages/core/src/components/Dropdown/__stories__/Dropdown.stories.js
- packages/core/src/components/Tabs/__stories__/Tabs.stories.tsx
- packages/core/src/storybook/components/related-components/descriptions/box-description.jsx
- packages/core/src/storybook/patterns/dropdown-in-modals/dropdown-in-modals.stories.js
- packages/core/src/types/ValueOf.ts
- packages/core/src/types/index.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7225220262
> chore(Box): deprecate enums

- packages/core/src/components/AvatarGroup/AvatarGroup.tsx
- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.tsx
> docs(AvatarGroup): migrate story into typescript

- packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
- packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipContainer.tsx
https://monday.monday.com/boards/3532714909/pulses/7246894940
> fix(AvatarGroup): be able to use some tooltip props

- packages/codemod/transformations/core/v2-to-v3/__tests__/loader-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/loader-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232297931
> chore(Loader): codemod for migration of props

- packages/codemod/transformations/core/v2-to-v3/__tests__/menu-button-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/menu-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/menu-divider-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/menu-item-button-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/menu-item-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/menu-title-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/menu-button-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/menu-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/menu-divider-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/menu-item-button-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/menu-item-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/menu-title-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7246930656
> chore(Menu): codemod for migration of props

- packages/core/docs/vibe-3-changelog.md
- packages/core/src/components/Menu/MenuItem/MenuItem.tsx
- packages/core/src/components/Menu/MenuItemButton/MenuItemButton.tsx
- packages/core/src/components/SplitButton/SplitButton.tsx
- packages/core/src/components/Tipseen/Tipseen.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7203148935
> Bring back static props that were deleted

- packages/codemod/transformations/core/v2-to-v3/__tests__/tab-list-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/tab-panels-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/tab-list-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/tab-panels-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232299473
> chore(TabList & TabPanels): codemod for migration of props

- packages/codemod/transformations/core/v2-to-v3/__tests__/avatar-group-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/checkbox-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/clickable-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/icon-button-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/label-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/avatar-group-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/checkbox-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/clickable-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/icon-button-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/label-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232286000
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232290268
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232294078
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232295848
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7232297229
> Codemods label/avatar/checkbox/clickable/iconButton

- packages/codemod/transformations/core/v2-to-v3/__tests__/modal-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/modal-header-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/modal-component-migration.ts
- packages/codemod/transformations/core/v2-to-v3/modal-header-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/pulses/7291698357
> chore: Modal and ModalHeader codemods

- packages/core/src/components/Combobox/Combobox.module.scss
- packages/core/src/components/Combobox/Combobox.tsx
- packages/core/src/components/Combobox/__tests__/__snapshots__/Combobox.snapshot.test.tsx.snap
> fix(Combobox): render comboboxItems only when hasResults is true

- packages/core/src/components/Dropdown/__stories__/Dropdown.stories.js
I've noticed that the dropdown isn't filtering by it's own when we're on async options, which is a very weird behavior by react-select IMO..
https://monday.monday.com/boards/3532714909/pulses/7303258099
> docs(Dropdown): fix async options story filtering

- packages/core/src/components/Table/Table/Table.types.ts
https://monday.monday.com/boards/3532714909/pulses/7315877344
> chore(Table): add small size

- packages/codemod/src/consts/vibe-import-paths.ts
- packages/codemod/src/utils/import-utils.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/type-imports-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/type-imports-migration.ts
- packages/codemod/types/index.ts
- packages/codemod/types/paths.types.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/pulses/7303260067
> chore: codemods for /types entry

- packages/codemod/transformations/core/v2-to-v3/__tests__/icon-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/icon-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7321490374?userId=59970142
> Chore(Icon): Codemod for removing clickable when it is false

- packages/codemod/transformations/core/v2-to-v3/__tests__/text-field-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/text-field-component-migration.ts
- packages/core/docs/vibe-3-changelog.md
https://monday.monday.com/boards/3532714909/pulses/7291769998
> chore: TextField codemods

- packages/core/src/components/Toast/Toast.module.scss
https://monday.monday.com/boards/3532714909/pulses/7157061407
> fix(Toast): make type style stronger

- packages/core/src/components/DatePicker/DatePicker.tsx
- packages/core/src/components/Dropdown/Dropdown.styles.js
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
- packages/core/types/packages.d.ts
https://monday.monday.com/boards/3532714909/pulses/7347964066
> fix: alpha fixes

- packages/codemod/src/utils/__tests__/prop-utils.test.ts
- packages/codemod/src/utils/prop-utils.ts
- packages/codemod/src/utils/wrap-transformation.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/button-component-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/packages-rename-migration.ts
- packages/codemod/transformations/core/v2-to-v3/type-imports-migration.ts
- packages/codemod/transformations/core/v2-to-v3/use-clickable-props-hook-migration.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7359123505
>  chore: change codemod to use tsx parser

- packages/core/src/components/Dropdown/components/ChildrenContent/ChildrenContent.jsx
- packages/core/src/components/Dropdown/components/ChildrenContent/ChildrenContent.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7368182162
> fix(Dropdown): left icon shrinking with long text

- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/__tests__/Dropdown.interactions.js
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
- packages/core/src/components/Dropdown/components/Control/Control.jsx
- packages/core/src/components/Dropdown/components/option/option.jsx
https://monday.monday.com/boards/3532714909/pulses/7291366863
> feat(Dropdown): Add A11y props to dropdown

- packages/core/src/components/Dropdown/Dropdown.styles.js
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/Dropdown.types.ts
- packages/core/src/components/Dropdown/__stories__/Dropdown.mdx
- packages/core/src/components/Dropdown/__stories__/Dropdown.stories.js
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7178692867
Adding option for divider in dropdown
> feat(Dropdown): add option for divider in dropdown

- packages/core/src/components/ModalNew/Modal/Modal.module.scss
- packages/core/src/components/ModalNew/Modal/Modal.tsx
- packages/core/src/components/ModalNew/Modal/__tests__/Modal.test.tsx
https://monday.monday.com/boards/3532715121/pulses/7360732026
> feat(Modal): implement size prop and responsiveness

- packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.tsx
https://monday.monday.com/boards/3532715121/pulses/7407965750
> feat(ModalTopActions): use CloseMedium instead of CloseSmall icon

- packages/core/src/components/DialogContentContainer/DialogContentContainer.module.scss
- packages/core/src/components/Dropdown/Dropdown.styles.js
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7202438764
> fix: keep current drop shadow with stroke on dark theme

- packages/core/src/components/ColorPicker/components/ColorPickerContent/ColorPickerClearButton.tsx
https://monday.monday.com/boards/3532714909/pulses/7586227545
> fix(ColorPickerClearButton): button isn't clickable inside MenuItem

- packages/core/src/components/ModalNew/ModalHeader/ModalHeader.tsx
- packages/core/src/components/ModalNew/ModalHeader/__tests__/ModalHeader.test.tsx
https://monday.monday.com/boards/3532715121/pulses/7371680810
> feat(ModalHeader): set titleId and descriptionId for Modal

- packages/core/rollup/styleInject.ejs
https://monday.monday.com/boards/4400799549/pulses/6799260682
> Support SSR injected styles

- packages/core/README.md
- packages/core/rollup/styleInject.ejs
https://monday.monday.com/boards/4400799549/pulses/6799260682
> Support SSR injected styles readme

- packages/core/package.json
- packages/core/src/components/Icon/CustomSvgIcon/CustomSvgIcon.tsx
- packages/core/src/components/Typography/Typography.tsx
- packages/core/src/components/Typography/TypographyHooks.tsx
- yarn.lock
https://monday.monday.com/boards/4400799549/pulses/7510834798
> fix: Fix ellipsis clamp lines for SSR [prerelease]

- packages/core/chromatic.config.json
Enable Chromatic's turbosnap
https://monday.monday.com/boards/3532714909/pulses/7597417248
> ci(chromatic): ui regression only for changed files (turbosnap)

- packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.scss
- packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.tsx
Change container width size for:
[AttentionBox with link](https://vibe.monday.com/?path=/docs/feedback-attentionbox--attention-box-with-link): to 350px
[Dismissible AttentionBox](https://style.monday.com/?path=/docs/feedback-attentionbox--dismissable): to 274px
Add a class name and give correct size
> docs: change container size

- packages/core/src/storybook/components/related-components/descriptions/menu-grid-item-description.tsx
https://monday.monday.com/boards/3532714909/pulses/7600767525
> chore: lint

- .github/PULL_REQUEST_TEMPLATE.md
https://monday.monday.com/boards/3532714909/pulses/7623619264
> chore: add resolve to pr template

- packages/core/src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.helpers.js
- packages/core/src/storybook/components/related-components/descriptions/virtualized-list-description/virtualized-list-description.jsx
Changes made:
Replaced the div inside the VirtualizedList catalog component with the Text component.
Resolves #2504 #2505
> docs: VirtualizedList and VirtualizedGrid related components should use Text instead of inline string

- packages/core/src/components/Button/__stories__/Button.stories.tsx
> docs(Button): onColorStates story should use Text instead of inline string

- packages/core/src/storybook/stand-alone-documentaion/colors/content-color-row/content-color-row.jsx
- packages/core/src/storybook/stand-alone-documentaion/colors/content-colors/content-colors.jsx
[Issue link](https://github.com/mondaycom/vibe/issues/2509#issue-2583857830)
-  [x] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.
Resolves #2509
> docs(Colors): replace inline strings with Vibe's Text component

- packages/core/src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.tsx
Converted useGridKeyboardNavigation stories file to tsx format. And Resolved type issues wherever required
Resolves #2521
> docs: Converted useGridKeyboardNavigation stories file to ts

- packages/core/src/components/ModalNew/footers/ModalFooterWizard/ModalFooterWizard.module.scss
- packages/core/src/components/ModalNew/footers/ModalFooterWizard/ModalFooterWizard.tsx
- packages/core/src/components/Steps/StepsGalleryHeader.tsx
https://monday.monday.com/boards/3532714909/pulses/7360993682
> feat(ModalFooterWizard): wizard modal footer

- packages/core/src/components/Toast/__stories__/Toast.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/7598655120
> docs: pause animation at first frame

- .github/workflows/chromatic.yml
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7599661375
> infra: Run Chromatic only on PR events, not Push event

- packages/style/src/Icons/iconsMetaData.js
https://monday.monday.com/boards/3532714909/pulses/7721397764
> feat(Wand): add "Template" tag to icon

- packages/core/src/components/Table/TableHeaderCell/TableHeaderCell.tsx
https://monday.monday.com/boards/3532714909/pulses/7622774928
> feat(TableHeaderCell): allow passing title as component

- packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipContent.module.scss
- packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7784427659
> fix(AvatarGroup): avatar shrinking in counter tooltip

- packages/core/src/components/Box/BoxConstants.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7786570098
> fix(Box): fix enums

- packages/testkit/__TESTS__/dropdown.spec.js
https://monday.monday.com/boards/3532714909/pulses/7801264936
> test: add a delay for dropdown

- packages/icons/README.md
- packages/icons/scripts/generate-lazy-icons.js
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7802963361
> fix: lazy loading icons name

- packages/core/src/components/Text/__stories__/Text.stories.tsx
- packages/core/src/components/Tooltip/Tooltip.tsx
- packages/core/src/components/Typography/TypographyHooks.tsx
https://monday.monday.com/boards/3532663354/pulses/5486951126
> Fix tooltip of Text component with array of children

- packages/codemod/bin/vibe-codemod.ts
- packages/codemod/transformations/core/v2-to-v3/__tests__/next-imports-migration.test.ts
- packages/codemod/transformations/core/v2-to-v3/next-imports-migration.ts
Decided to go for it anyway
https://monday.monday.com/boards/3532714909/pulses/7852782672
> feat(codmods): add /next codemod

- packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
https://monday.monday.com/boards/3532714909/pulses/7868133766
was requested in support channel
> feat(AvatarGroupCounter): add option to render MenuButton on a container

- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7867495094
> fix(table): horizontal scroll on react 18

- packages/core/src/components/AvatarGroup/AvatarGroup.tsx
- packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
https://monday.monday.com/boards/3532714909/pulses/7868133766
> fix(AvatarGroup): pass dialogContainerSelector from AvatarGroup to AvatarGroupCounter

- packages/core/src/components/Steps/__stories__/Steps.mdx
https://monday.monday.com/boards/3532714909/pulses/7850222558
> docs: remove guidelines

- packages/testkit/BaseElement.ts
> feat(BaseElement): add isVisible method

- packages/core/src/components/Table/Table/__stories__/Table.stories.helpers.tsx
- packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
- packages/core/src/components/Table/TableHeader/TableHeader.module.scss
- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.module.scss
- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7963926689
> fix(table): fix scroll delay in header on virtualized table

- packages/core/src/components/TextField/TextField.tsx
https://monday.monday.com/boards/6965884836/pulses/7973351248
> feat(TextField): add dir prop

- packages/core/src/components/Button/Button.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7801661751
> fix(Button): fix secondary disabled border color

- packages/core/src/components/ModalNew/Modal/Modal.tsx
- packages/core/src/components/ModalNew/Modal/Modal.types.tsx
- packages/core/src/components/ModalNew/ModalHeader/ModalHeader.tsx
- packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.tsx
- packages/core/src/components/ModalNew/footers/ModalFooterBase/ModalFooterBase.tsx
- packages/core/src/components/ModalNew/footers/ModalFooterBase/ModalFooterBase.types.ts
- packages/core/src/components/ModalNew/footers/ModalFooterWizard/ModalFooterWizard.tsx
- packages/core/src/components/ModalNew/layouts/ModalBasicLayout/ModalBasicLayout.module.scss
- packages/core/src/components/ModalNew/layouts/ModalBasicLayout/ModalBasicLayout.tsx
- packages/core/src/components/ModalNew/layouts/ModalFooterShadow.module.scss
- packages/core/src/components/ModalNew/layouts/ModalFooterShadow.tsx
- packages/core/src/components/ModalNew/layouts/ModalFooterShadow.types.ts
- packages/core/src/components/ModalNew/layouts/ModalMedia.tsx
- packages/core/src/components/ModalNew/layouts/ModalMediaLayout/ModalMediaLayout.module.scss
- packages/core/src/components/ModalNew/layouts/ModalMediaLayout/ModalMediaLayout.tsx
- packages/core/src/components/ModalNew/layouts/ModalSideBySideLayout/ModalSideBySideLayout.tsx
- packages/core/src/components/Typography/Typography.module.scss
- packages/core/src/components/Typography/Typography.tsx
- packages/core/src/components/Typography/Typography.types.ts
- packages/core/src/components/Typography/TypographyConstants.ts
https://monday.monday.com/boards/3532714909/pulses/7742176612
> feat(Modal): animation enhancements and general fixes and enhancements

- packages/core/src/components/Table/TableRowMenu/TableRowMenu.tsx
- packages/core/src/components/Table/context/TableRowMenuContext/TableRowMenuContext.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/7889513842
> fix(table): avoid unnecessary re-rendering if TableRowMenu doesn't exist

- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.tsx
> docs(AvatarGroup): fix disabled story example

- packages/core/src/components/List/List.tsx
- packages/core/src/components/List/__tests__/__snapshots__/List.test.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8011242971
> fix(List): getting wrong tabIndex on initialization

- packages/core/src/components/ButtonGroup/ButtonGroup.module.scss
https://monday.monday.com/boards/3532714909/pulses/8038771953
> fix(ButtonGroup): remove z-index from active button

- packages/core/src/components/Icon/CustomSvgIcon/CustomSvgIcon.tsx
https://monday.monday.com/boards/4400799549/pulses/7929489828
> Fix importing inlinesvg esm issue

- packages/core/src/components/Icon/CustomSvgIcon/CustomSvgIcon.tsx
https://monday.monday.com/boards/4400799549/pulses/7929489828
> fix: load inlinesvg with esm

- packages/core/src/components/Skeleton/__stories__/Skeleton.stories.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8066717152
> docs(Skeleton): fix complex example

- packages/core/package.json
https://monday.monday.com/boards/4400799549/pulses/7929489828
> Add export for package json for trident toolkit

- packages/core/src/components/VirtualizedGrid/VirtualizedGrid.tsx
https://monday.monday.com/boards/3532714909/pulses/8104618394
> fix(VirtualizedGrid): fix onItemsRendered params

- packages/icons/src/iconsMetaData.ts
- packages/icons/src/svg/WarningFull.svg
https://monday.monday.com/boards/3532714909/pulses/8108480304
> feat(icons): add WarningFull icon

- packages/core/src/components/Tipseen/Tipseen.tsx
Support event in tipseen onClose props
> feat(Tipseen): add event in Tipseen onClose prop

- packages/core/src/components/Button/Button.tsx
- packages/core/src/components/Button/__tests__/Button.test.js
https://monday.monday.com/boards/3532714909/pulses/8124747909
> fix(Button): ensure icons className is not added when children are non-renderable

- packages/core/src/components/Tipseen/Tipseen.tsx
https://monday.monday.com/boards/3532714909/pulses/8125394511
> fix(Tipseen): showDelay of 0 causes component to auto-close when mouse leave

- packages/core/.storybook/manager-head.html
https://monday.monday.com/boards/3532714909/pulses/8087429099
> docs(Modal): when clicking on Modal folder, automatically go to docs page

- packages/core/src/components/EditableTypography/EditableTypography.tsx
this affects both EditableText and EditableHeading as well
https://monday.monday.com/boards/3532714909/pulses/8130792768
> feat(EditableTypography): allow autoselect of text when going into edit mode

- packages/core/src/components/Dropdown/Dropdown.styles.js
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/__tests__/Dropdown.test.js
- packages/core/src/components/Dropdown/__tests__/driver.js
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8085299898
> fix(Dropdown): fix a11y props when searchable is false

- packages/core/src/components/EditableTypography/EditableTypography.tsx
the use case that helped catch it is that a confirmation modal that should pop-up after changing the editable value is automatically gets clicked on its primary button
https://monday.monday.com/boards/3532714909/pulses/8135488477
a reproducible code for the Playground:
```
() => {
const [mainModalVisible, setMainModalVisible] = useState(true);
const [confirmModalVisible, setConfirmModalVisible] = useState(false);
const [textValue, setTextValue] = useState("Editable Text");
const [newTextValue, setNewTextValue] = useState<string | null>(null);
const handleEditableTextChange = (newValue: string) => {
setNewTextValue(newValue);
setConfirmModalVisible(true);
};
const handleConfirmChange = () => {
if (newTextValue !== null) {
setTextValue(newTextValue);
}
setConfirmModalVisible(false); …
```
> fix(EditableTypography): Enter click to end edit mode is bubbling to other places afterwards

- packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/core/src/components/Modal/layouts/ModalBasicLayout/__stories__/ModalBasicLayout.stories.tsx
- packages/core/src/components/Modal/layouts/ModalMediaLayout/__stories__/ModalMediaLayout.stories.tsx
- packages/core/src/components/Modal/layouts/ModalSideBySideLayout/__stories__/ModalSideBySideLayout.stories.tsx
- packages/core/src/components/TransitionView/TransitionView.types.ts
- packages/core/src/components/TransitionView/index.ts
- packages/core/src/components/index.ts
Resolve #2695 
https://monday.monday.com/boards/3532714909/pulses/8138240178
> feat(TransitionView): export component to be used publicly

- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/MenuItemSubMenuIcon.module.scss
- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/MenuItemSubMenuIcon.tsx
- packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/MenuItemSubMenuIcon.types.ts
https://monday.monday.com/boards/3532714909/pulses/8111942496
> fix(MenuItem): fix disabled submenu arrow button

- packages/core/src/components/Icon/__stories__/IconsList.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8329411779
> docs: allow search icon by name

- packages/core/src/components/Search/Search.tsx
- packages/core/src/components/Search/Search.types.ts
- packages/core/src/components/Search/__tests__/Search.test.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8190214567
> feat(Search): add prop for hiding clear icon

- packages/core/src/components/Slider/Slider.module.scss
- packages/core/src/components/Slider/Slider.tsx
- packages/core/src/components/Slider/__tests__/__snapshots__/Slider-non-ranged.test.js.snap
- packages/core/src/components/Slider/__tests__/__snapshots__/Slider-ranged.test.js.snap
- packages/core/src/components/Slider/__tests__/__snapshots__/Slider.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8350762534
> fix(Slider): margin on slider wrapper based on valueLabelPosition prop

- .github/workflows/release.yml
- lerna.json
https://monday.monday.com/boards/3532714909/pulses/8360336024
> ci: lerna publish github release

- packages/core/src/components/TextArea/TextArea.types.ts
https://monday.monday.com/boards/6965884836/pulses/8380055982
> docs(TextArea): add disabled and readonly to component interface

- packages/core/src/components/Dropdown/Dropdown.styles.js
- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/Dropdown.types.ts
https://monday.monday.com/boards/3532714909/pulses/8326192363
> feat(Dropdown): allow ellipsis for component's placeholder

- packages/core/src/components/Tabs/Tab/Tab.tsx
- packages/core/src/components/Tabs/Tab/__stories__/Tab.stories.tsx
- packages/core/src/components/Tabs/Tab/__tests__/Tab.test.tsx
> feat(Tab): add tooltipProps prop

- packages/core/src/components/Modal/footers/ModalFooter/ModalFooter.tsx
- packages/core/src/components/Modal/footers/ModalFooterBase/ModalFooterBase.tsx
- packages/core/src/components/Modal/footers/ModalFooterBase/ModalFooterBase.types.ts
- packages/core/src/components/Modal/footers/ModalFooterWizard/ModalFooterWizard.tsx
- packages/core/src/components/Modal/footers/utils/__tests__/getPropsForButton.test.ts
- packages/core/src/components/Modal/footers/utils/getPropsForButton.ts
https://monday.monday.com/boards/3532714909/pulses/8401165563
> feat(ModalFooter): allow tooltip for the modal footer's buttons

- packages/testkit/components/Tab.ts
- packages/testkit/components/TabList.ts
- packages/testkit/package.json
This is in order to avoid playwright versions conflicts.
Anyone who require testkit, should requiring it as a peerDependency
> feat: testkit - playwright should be a peer dependency

- packages/core/src/components/DialogContentContainer/DialogContentContainer.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8473096309
> fix(Dialog): ensure event handlers are properly forwarded in DialogContentContainer

- packages/icons/src/iconsMetaData.ts
- packages/icons/src/react/MinusSmall.tsx
- packages/icons/src/react/index.ts
- packages/icons/src/svg/MinusSmall.svg
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8436040503
> feat(Icons): Add MinusSmall

- packages/testkit/__tests__/button.test.js
- packages/testkit/__tests__/buttonGroup.test.js
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8473096309
> test: temporarily skip failing test

- packages/core/src/components/Label/Label.tsx
- packages/core/src/components/Label/Label.types.ts
- packages/core/src/components/Label/LabelConstants.ts
https://monday.monday.com/boards/3532714909/pulses/8222602622
> feat(Label): Add content colors

- packages/core/src/components/VirtualizedList/VirtualizedList.tsx
https://monday.monday.com/boards/3532714909/views/113184182/pulses/8510096252
> fix(VirtualizedList): sync scroll position to handle React 18 batching

- packages/core/src/components/List/List.tsx
- packages/core/src/components/List/__tests__/List.test.js
- packages/core/src/components/List/utils/ListContext.ts
- packages/core/src/components/List/utils/ListUtils.ts
- packages/core/src/components/ListItem/ListItem.tsx
Example:
```
<List role="list">
<ListItem role="listitem" />
</List>  
``` 
https://monday.monday.com/boards/3532714909/pulses/8109543863
> feat(List): add role props

- packages/core/src/components/Avatar/__stories__/Avatar.mdx
- packages/core/src/components/Avatar/__stories__/Avatar.stories.tsx
- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.module.scss
- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.tsx
https://monday.monday.com/boards/7538077190/views/182204244/pulses/7538089702
> docs(Avatar + AvatarGroup): uplift stories

- packages/core/src/storybook/stand-alone-documentaion/welcome/Abilities/Abilities.tsx
Resolves https://github.com/mondaycom/vibe/issues/2776
> docs: fix broken links

- packages/core/src/components/AlertBanner/__stories__/AlertBanner.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/8618185935
> docs(AlertBanner): document the subcomponents in props table

- packages/core/src/components/Table/index.ts
https://monday.monday.com/boards/3532714909/pulses/8617187347
> feat(types): export TableColumn type

- packages/core/src/components/SplitButton/SplitButton.tsx
https://monday.monday.com/boards/3532714909/pulses/8617187347
> feat(types): allow dialogPaddingSize to accept inline string values (in addition to the enum)

- packages/core/src/components/Button/Button.module.scss
- packages/core/src/components/Button/Button.types.ts
- packages/core/src/components/Button/ButtonConstants.ts
- packages/core/src/components/Button/__tests__/__snapshots__/Button.snapshot.test.tsx.snap
- packages/core/src/components/Modal/ModalTopActions/ModalTopActions.tsx
- packages/core/src/components/Modal/ModalTopActions/ModalTopActions.types.ts
- packages/core/src/components/Modal/ModalTopActions/__tests__/ModalTopActions.test.tsx
https://monday.monday.com/boards/6965884836/views/151260495
> fix(Modal): closeButtonTheme fixed color

- packages/core/src/components/Button/Button.tsx
- packages/core/src/components/Button/ButtonConstants.ts
- packages/core/src/components/IconButton/IconButton.tsx
- packages/core/src/components/MenuButton/MenuButton.tsx
https://monday.monday.com/boards/3532714909/pulses/8561024765
> fix(Button): change icon size in small variant to 16px

- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.module.scss
https://monday.monday.com/boards/3532714909/views/113184182/pulses/8688956564
> fix(Table): fix virtualized table overflow

- packages/core/src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.helpers.tsx
- packages/core/src/components/VirtualizedGrid/__stories__/VirtualizedGrid.stories.tsx
- packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.stories.helpers.tsx
- packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.stories.tsx
- packages/core/src/hooks/useClickableProps/__stories__/useClickableProps.stories.tsx
- packages/core/src/storybook/components/related-components/descriptions/virtualized-list-description/virtualized-list-description.jsx
https://monday.monday.com/boards/3532714909/pulses/7623433691
https://monday.monday.com/boards/3532714909/pulses/7601091903
https://monday.monday.com/boards/3532714909/pulses/7623509485
https://monday.monday.com/boards/3532714909/pulses/7623517272
https://monday.monday.com/boards/3532714909/pulses/7623449853
> docs: convert stories to TS

- packages/core/src/hooks/usePopover.ts
https://monday.monday.com/boards/3532714909/views/113184182/pulses/8711977674
> feat: usePopover add offset prop

- packages/core/src/components/Tipseen/TipseenContent.tsx
https://monday.monday.com/boards/3532714909/pulses/8729751543
> feat(Tipseen): add submitButtonIcon prop

- packages/core/src/components/BaseList/BaseList.tsx
- packages/core/src/components/BaseList/BaseList.types.ts
- packages/core/src/components/DropdownNew/Dropdown.tsx
- packages/core/src/components/DropdownNew/Dropdown.types.ts
- packages/core/src/components/DropdownNew/__tests__/Dropdown.test.tsx
- packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
https://monday.monday.com/boards/3532714909/views/113184182/pulses/8687640350
> chore(DropdownNew): add events

- README.md
- packages/core/package.json
> Revert "deps: limit react/react-dom to <v18.3"

- packages/testkit/components/Menu.ts
- packages/testkit/package.json
Update method to filter using regex with exact word instead of partial
> feat(Menu): update selectItem method to be more strict

- packages/testkit/components/Menu.ts
https://monday.monday.com/boards/5374157346/pulses/8653237533
> feat(Menu): change locator handling

- packages/core/src/hooks/usePopover.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8773662592
> feat(usePopover): add fallbackPlacements prop

- packages/testkit/components/Menu.ts
Fixing menu Item selectItem function
> fix(testkit): Fixing selectItem function

- packages/core/src/components/Dropdown/Dropdown.tsx
- packages/core/src/components/Dropdown/Dropdown.types.ts
- packages/core/src/components/Modal/layouts/ModalSideBySideLayout/__stories__/ModalSideBySideLayout.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/8794876358
> feat(Dropdown): use layer context for the dropdown in case used inside Dialog or Modal

- packages/style/src/config/maps/themes/basic/keys/_keys.scss
- packages/style/src/config/maps/themes/basic/palette/_palette.scss
- packages/style/src/config/maps/themes/black/keys/_black-theme-keys.scss
- packages/style/src/config/maps/themes/dark/keys/_dark-theme-keys.scss
- packages/style/src/config/tokens/themes/basic/keys/_keys.scss
- packages/style/src/config/tokens/themes/black/keys/_black-theme-keys.scss
- packages/style/src/config/tokens/themes/dark/keys/_dark-theme-keys.scss
- packages/style/src/config/tokens/themes/dark/palette/_dark-theme-palette.scss
https://monday.monday.com/boards/3532714909/pulses/7246827447
> feat(colors): define color-surface in dark and black themes, add backdrop-color token for all themes

- packages/core/src/components/Typography/Typography.module.scss
- packages/core/src/components/Typography/Typography.types.ts
- packages/core/src/components/Typography/TypographyConstants.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8830567066
> feat(Text): add error color

- packages/core/src/components/EmptyState/EmptyState.tsx
https://monday.monday.com/boards/3532714909/pulses/8869136936
> fix(EmptyState): description should always be text2

- packages/icons/package.json
https://monday.monday.com/boards/3532714909/pulses/8869954574
> fix(icons): correct path for lazy types definition in package.json

- packages/core/src/components/Menu/MenuTitle/MenuTitle.tsx
https://monday.monday.com/boards/3532714909/pulses/8869281367
> feat(MenuTitle): be able to provide a ReactNode

- packages/core/src/components/Box/Box.tsx
- packages/core/src/components/Box/__tests__/Box.snapshot.test.tsx
- packages/core/src/components/Box/__tests__/__snapshots__/Box.snapshot.test.tsx.snap
- packages/core/src/tests/constants.ts
Added missing data-testid to Box component
Resolves # https://monday.monday.com/boards/6965884836/pulses/8818397254
> feat: add data-testid to Box

- packages/core/src/components/TextField/TextField.tsx
https://monday.monday.com/boards/3532714909/views/113184182/pulses/8895851378
> feat(TextField): validationText can be a ReactNode

- packages/core/src/components/index.ts
https://monday.monday.com/boards/3532714909/views/113184182/pulses/8690016083
> types: export typography types

- packages/core/src/components/Flex/Flex.tsx
- packages/core/src/components/Flex/Flex.types.ts
- packages/core/src/components/Flex/__stories__/Flex.mdx
- packages/core/src/components/Flex/__stories__/Flex.stories.tsx
- packages/core/src/components/Flex/__tests__/Flex.snapshot.test.tsx
- packages/core/src/components/Flex/__tests__/__snapshots__/Flex.snapshot.test.tsx.snap
it's based on the discussion in this thread: https://monday.slack.com/archives/C034VLARPJS/p1738148927052189
> feat(Flex): introduced flex prop

- packages/core/src/components/TextField/TextField.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8690060763
> fix(TextField): Don't display subTextContainer when no requiredErrorText

- packages/core/.eslintrc.cjs
- packages/core/src/components/Combobox/components/ComboboxConstants.ts
https://monday.monday.com/boards/3532714909/pulses/8975685665
> fix(Combobox): update scrollRef type to MutableRefObject

- packages/core/src/components/Menu/Menu/Menu.tsx
- packages/core/src/components/Menu/Menu/hooks/useCloseMenuOnKeyEvent.tsx
- packages/core/src/components/Menu/Menu/hooks/useMenuKeyboardNavigation.tsx
- packages/core/src/components/MenuButton/MenuButton.tsx
- packages/core/src/hooks/useFullKeyboardListeners.ts
Added: 
* Tab closes the menu and returns focus to menu button
* Home/End button move focus to first/last element in the menu
* aria-controls for menu button
Resolves #
> feat(Menu): accessibility impovments

- packages/core/src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8999734508
> fix(Combobox): Hide option tooltip when scrolled

- packages/core/src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9017586302
> fix(ColorPicker): fix icon alignment in color

- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
https://monday.monday.com/boards/3532714909/pulses/9028881455
> fix(Dropdown): prevent the MultiValueContainer gaps from triggering open of menu

- packages/core/src/components/MenuButton/MenuButton.tsx
https://monday.monday.com/boards/3532714909/pulses/9030963387
> feat(MenuButton): allow passing multiple values to dialog ignore classes

- packages/core/src/components/Skeleton/Skeleton.module.scss
https://monday.monday.com/boards/3532714909/pulses/8965375876
> chore(Skeleton): change animation opacity to 40%

- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9091862544
> fix(Dropdown): add support for rightRenderer in multi dropdown

- packages/core/src/components/Dialog/modifiers/observeReferenceResizeModifier.ts
- packages/core/src/hooks/usePopover.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9090664407
> feat: add observeReferenceResizeModifier for dynamic reference resizing

- packages/core/src/components/Chips/Chips.module.scss
- packages/core/src/components/Chips/Chips.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9097213871
> feat(Chips): add noMargin prop to remove default margin from chips

- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9101718458
> fix(Dropdown): Fix dropdown chip width issue

- packages/core/src/storybook/components/related-components/descriptions/editable-heading-description.tsx
- packages/core/src/storybook/components/related-components/descriptions/editable-text-description.tsx
https://monday.monday.com/boards/3532714909/pulses/5740467028
Resolves https://github.com/mondaycom/vibe/issues/2471
> docs: make editable stories not overflow

- packages/core/src/components/Tipseen/__stories__/Tipseen.stories.scss
- packages/core/src/components/Tipseen/__stories__/Tipseen.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/6978695918
https://monday.monday.com/boards/3532714909/pulses/7867844447
> docs: remove hideDismiss from template

- packages/core/src/components/Modal/Modal/__stories__/Modal.mdx
https://monday.monday.com/boards/3532714909/pulses/8162119233
> docs(Modal): add a11y instructions for complex ModalHeader usage

- packages/core/src/components/DropdownNew/Dropdown.types.ts
- packages/core/src/components/DropdownNew/__tests__/Dropdown.test.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9116167582
> chore(DropdownNew): Improve type safety with conditional props for multi select

- packages/core/src/components/DropdownNew/Dropdown.tsx
- packages/core/src/components/DropdownNew/Dropdown.types.ts
- packages/core/src/components/DropdownNew/__tests__/Dropdown.test.tsx
- packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownFiltering.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
- packages/core/src/components/DropdownNew/utils/dropdownUtils.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9116167582
> chore(DropdownNew): added filterOption prop

- packages/core/src/components/DropdownNew/Dropdown.tsx
- packages/core/src/components/DropdownNew/Dropdown.types.ts
- packages/core/src/components/DropdownNew/__tests__/Dropdown.test.tsx
- packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownFiltering.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
- packages/core/src/components/DropdownNew/utils/dropdownUtils.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9116167582
> chore(DropdownNew): add showSelectedOptions prop

- packages/core/src/scripts/generate-metadata.ts
https://monday.monday.com/boards/3532714909/pulses/9176848126
> fix: enhance props handling by filtering unnecessary properties to shorten the json

- packages/core/src/components/Dialog/Dialog.tsx
https://monday.monday.com/boards/3532714909/pulses/9179348742
> fix(Dialog): clear timeouts on component unmount

- packages/core/src/components/AttentionBox/AttentionBox.tsx
- packages/core/src/components/Avatar/Avatar.tsx
- packages/core/src/components/Avatar/AvatarBadge.tsx
- packages/core/src/components/Avatar/AvatarContent.tsx
- packages/core/src/components/Badge/Indicator/Indicator.tsx
- packages/core/src/components/BreadcrumbsBar/BreadcrumbsBar.tsx
- packages/core/src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx
- packages/core/src/components/Counter/Counter.tsx
- packages/core/src/components/Divider/Divider.tsx
- packages/core/src/components/LegacyModal/LegacyModal.tsx
- packages/core/src/components/Menu/MenuItemButton/MenuItemButton.tsx
- packages/core/src/components/Menu/MenuTitle/MenuTitle.tsx
- packages/core/src/components/Skeleton/Skeleton.tsx
- packages/core/src/components/Slider/SliderInfix.tsx
- packages/core/src/components/SplitButton/SplitButton.tsx
- packages/core/src/components/TextField/TextField.tsx
- packages/core/src/components/ThemeProvider/ThemeProvider.tsx
- packages/core/src/components/Toast/Toast.tsx
- packages/core/src/types/withStaticProps.ts
https://monday.monday.com/boards/3532714909/pulses/9176786627
> fix: metadata did not include components with static props because of docgen and typescript issues

- packages/mcp/package.json
- packages/mcp/src/server/index.ts
- packages/mcp/src/server/tools/get-vibe-component-metadata.ts
- packages/mcp/src/server/tools/list-vibe-public-components.ts
> fix(mcp): fix tool call structure, fix bin for npx

- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx
- packages/core/src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.module.scss
https://monday.monday.com/boards/3532714909/pulses/9209033502
> feat(Dropdown): add hover and active states to counter in MultiValueContainer

- packages/mcp/README.md
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9256658050
> fix(mcp): readme

- packages/mcp/README.md
- packages/mcp/src/index.ts
- packages/mcp/src/server/tools/v3-migration.ts
https://monday.monday.com/boards/3532714909/pulses/9274325667
> feat(mcp): add v3 migration tool

- packages/core/src/components/Tabs/Tab/Tab.module.scss
- packages/core/src/components/Tabs/Tab/Tab.tsx
- packages/core/src/components/Tabs/TabList/TabList.module.scss
- packages/core/src/components/Tabs/TabList/TabList.tsx
- packages/core/src/components/Tabs/TabList/__tests__/TabList.snapshot.test.js
- packages/core/src/components/Tabs/TabList/__tests__/__snapshots__/TabList.snapshot.test.js.snap
- packages/core/src/components/Tabs/__stories__/Tabs.mdx
- packages/core/src/components/Tabs/__stories__/Tabs.stories.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/8297159370
> feat(tabs): added stretchedUnderline prop

- packages/core/src/components/Chips/Chips.tsx
- packages/core/src/components/Chips/__tests__/__snapshots__/Chips.snapshot.test.tsx.snap
- packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9191891177
> fix(Chips): fix hover state

- .cursor/rules/new-component-implementation.mdc
https://monday.monday.com/boards/3532714909/pulses/9327905967
> docs: new cursor rule for new component implementation

- packages/core/src/components/Flex/__stories__/Flex.stories.module.scss
- packages/core/src/components/Flex/__stories__/Flex.stories.tsx
- packages/core/src/storybook/components/related-components/descriptions/flex-description.tsx
https://monday.monday.com/boards/3532714909/pulses/5506750873
> docs: change flex catalog example

- packages/core/src/components/ButtonGroup/ButtonGroup.module.scss
- packages/core/src/components/ButtonGroup/ButtonGroup.tsx
- packages/core/src/components/ButtonGroup/ButtonWrapper.tsx
- packages/core/src/components/ButtonGroup/__tests__/ButtonGroup.test.tsx
- packages/core/src/components/ButtonGroup/__tests__/__snapshots__/ButtonGroup.test.tsx.snap
https://monday.monday.com/boards/3532714909/pulses/9360158512
> fix(ButtonGroup): fix tooltips in fullWidth layout

- packages/testkit/components/Steps.ts
- packages/testkit/components/index.ts
https://monday.monday.com/boards/5374157346/pulses/9396388628
> feat: Add steps component to testkit

- packages/core/package.json
- packages/core/src/scripts/generate-metadata.ts
- yarn.lock
https://monday.monday.com/boards/3532714909/pulses/9426811119
> chore: 'build:metadata' script not working with node20

- packages/core/src/components/HiddenText/__stories__/HiddenText.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/9426149945
> docs(HiddenText): simplify story rendering

- packages/core/src/components/MenuButton/__stories__/MenuButton.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/9426151117
> docs(MenuButton): update story structure and typings for improved clarity

- packages/core/package.json
- packages/core/rollup.config.js
- packages/core/types/tokens.d.ts
https://monday.monday.com/boards/3532714909/pulses/9502099672
___
Bug fix
___
- Fix TypeScript import error for `@vibe/core/tokens`
- Add TypeScript declaration file for tokens module
- Update package.json exports to include types
- Configure build to copy TypeScript declarations
___
```mermaid
flowchart LR
A["tokens.d.ts"] --> B["rollup.config.js"]
B --> C["package.json exports"]
C --> D["TypeScript support"]
```
<tr>
<td>
<details>
<summary><strong>tokens.d.ts</strong><dd><code>Add TypeScript module declaration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: fix @vibe/core/tokens import ts error

- packages/core/src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.module.scss
- packages/core/src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9426149868
___
Documentation
___
- Remove unused SCSS module and template helper
- Replace template-based stories with inline render functions
- Add consistent inline styling for component width
- Clean up unused imports and dependencies
___
```mermaid
flowchart LR
A["Template-based stories"] --> B["Inline render functions"]
C["SCSS module styling"] --> D["Inline style objects"]
E["createComponentTemplate"] --> F["Direct component usage"]
```
<tr>
<td>
<details>
<summary><strong>ExpandCollapse.stories.module.scss</strong><dd><code>Rem …
> docs(ExpandCollapse): cleanup stories

- packages/core/src/components/BaseList/BaseList.module.scss
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9668029121
___
Bug fix
___
- Replace hard-coded padding with design system spacing tokens
- Update background color to use secondary background token
___
```mermaid
flowchart LR
A["Hard-coded values"] --> B["Design system tokens"]
B --> C["Consistent styling"]
```
<tr>
<td>
<details>
<summary><strong>BaseList.module.scss</strong><dd><code>Replace hard-coded styles with design tokens</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> fix(BaseList): update background color to use secondary background token

- packages/core/vite.config.ts
- packages/core/vitest.config.ts
https://monday.monday.com/boards/3532714909/pulses/9679195163
___
Documentation
___
- Add Vite configuration for build tooling
- Update Vitest config with type reference
- Remove unused path import from test config
___
```mermaid
flowchart LR
A["New vite.config.ts"] --> B["React Plugin Setup"]
C["vitest.config.ts"] --> D["Add Type Reference"]
C --> E["Remove Path Import"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>vite.config.ts</strong><dd><code>Add Vite configuration with React plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> docs: add vite config

- packages/core/src/components/Dialog/__stories__/Dialog.stories.tsx
- packages/core/src/components/ExpandCollapse/__stories__/ExpandCollapse.stories.tsx
- packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
- packages/core/src/components/Tabs/__stories__/Tabs.stories.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9426149389
___
Documentation
___
- Fix story props typing in Storybook components
- Add proper TypeScript props to render functions
- Import component prop types for type safety
- Enable args spreading in story templates
___
```mermaid
flowchart LR
A["Story render functions"] --> B["Add TypeScript props"]
B --> C["Import component types"]
C --> D["Spread args to components"]
```
<tr>
<td>
<details>
<summary><strong>Dialog.stories.tsx</strong><dd><code>Add DialogProps typing to story</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> docs: fix story props

- packages/core/src/storybook/stand-alone-documentaion/welcome/hero/Hero.tsx
https://monday.monday.com/boards/3532714909/pulses/9662235215
___
Documentation
___
- Update Figma resource link in Hero component
___
```mermaid
flowchart LR
A["Hero Component"] -- "update href" --> B["New Figma Community Link"]
```
<tr>
<td>
<details>
<summary><strong>Hero.tsx</strong><dd><code>Update Figma resource link</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> docs: change figma link

- packages/testkit/__tests__/Button.test.ts
- packages/testkit/__tests__/ButtonGroup.test.ts
- packages/testkit/__tests__/Checkbox.test.ts
- packages/testkit/__tests__/ColorPicker.test.ts
- packages/testkit/__tests__/Combobox.test.ts
- packages/testkit/__tests__/Dropdown.test.ts
- packages/testkit/__tests__/ExpandCollapse.test.ts
- packages/testkit/__tests__/IconButton.test.ts
- packages/testkit/__tests__/Link.test.ts
- packages/testkit/__tests__/List.test.ts
- packages/testkit/__tests__/ListItem.test.ts
- packages/testkit/__tests__/Loader.test.ts
- packages/testkit/__tests__/Menu.test.ts
- packages/testkit/__tests__/MenuButton.test.ts
- packages/testkit/__tests__/MenuItem.test.ts
- packages/testkit/__tests__/Modal.test.ts
- packages/testkit/__tests__/RadioButton.test.ts
- packages/testkit/__tests__/Search.test.ts
- packages/testkit/__tests__/SplitButton.test.ts
- packages/testkit/__tests__/Steps.test.ts
- packages/testkit/__tests__/TabList.test.ts
- packages/testkit/__tests__/Text.test.ts
- packages/testkit/__tests__/TextArea.test.ts
- packages/testkit/__tests__/TextField.test.ts
- packages/testkit/__tests__/Toast.test.ts
- packages/testkit/__tests__/Toggle.test.ts
- packages/testkit/components/Text.ts
- packages/testkit/components/TextArea.ts
- packages/testkit/scripts/run-changed-tests.js
Resolves #
https://monday.monday.com/boards/5374157346/views/118501143/pulses/9679438921
___
Tests, Bug fix
___
- Updated test attribute assertions to use semantic attributes
- Fixed test locators and element targeting
- Enhanced test script to monitor testkit component changes
- Removed problematic test case for Text component
___
```mermaid
flowchart LR
A["Test Files"] --> B["Updated Attribute Tests"]
B --> C["Semantic Attributes"]
A --> D["Fixed Locators"]
E["Test Script"] --> F["Enhanced Monitoring"]
G["TextArea Component"] --> H["Removed clearText Call"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>26 files</summary><table>
<tr> …
> fix(testkit): improvements + fix for unit tests

- packages/mcp/README.md
Documentation
___
- Remove experimental status from MCP package documentation
___
<tr>
<td>
<details>
<summary><strong>README.md</strong><dd><code>Remove experimental status declaration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/mcp/README.md
<ul><li>Removed "Status" section declaring package as experimental<br> <li> Deleted warning about API changes during active development</ul>
</details>
</td>
<td><a href="https://github.com/mondaycom/vibe/pull/3021/files#diff-ba5dea79fe8 …
> docs: remove experimental from mcp

- packages/core/src/components/EditableHeading/__stories__/EditableHeading.mdx
- packages/core/src/components/EditableHeading/__stories__/EditableHeading.stories.tsx
- packages/core/src/components/EditableText/__stories__/EditableText.mdx
- packages/core/src/components/EditableText/__stories__/EditableText.stories.tsx
https://monday.monday.com/boards/3532714909/pulses/8053010169
___
Documentation
___
- Add placeholder stories for EditableHeading and EditableText components
- Include new documentation sections showing placeholder functionality
- Demonstrate placeholder behavior in Storybook examples
___
```mermaid
flowchart LR
A["EditableHeading stories"] --> B["Add WithPlaceholder story"]
C["EditableText stories"] --> D["Add WithPlaceholder story"]
E["Documentation files"] --> F["Add placeholder sections"]
```
<tr>
<td>
<details>
<summary><strong>EditableHeading.mdx</strong><dd><code>Add placeholder …
> docs: add placeholder stories to EditableHeading, EditableText

- packages/mcp/src/server/tools/token-metadata-service.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9745528848
___
Enhancement
___
- Replace local file parsing with remote CSS fetching from unpkg
- Add retry logic with fetch and curl fallback for corporate networks
- Implement automatic token categorization based on naming patterns
- Add comprehensive error handling and logging
___
```mermaid
flowchart LR
A["Local SCSS Files"] --> B["Remote CSS URL"]
B --> C["Fetch with Retry"]
C --> D["Parse CSS Content"]
D --> E["Categorize Tokens"]
C --> F["Curl Fallback"]
F --> D
```
<tr>
<td>
<details> …
> feat(mcp): implement token fetching with retry logic and categorize tokens

- packages/core/src/__tests__/__snapshots__/exports.test.ts.snap
- packages/core/src/__tests__/exports.test.ts
Tests
___
- Add snapshot test for hooks exports validation
___
```mermaid
flowchart LR
A["Import hooks module"] --> B["Add snapshot test"] --> C["Validate hooks exports"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>exports.test.ts</strong><dd><code>Add hooks exports snapshot test</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/core/src/__tests__/exports.test.ts
<ul><li>Import hooks module from parent directory<br> <li> Add new test case for …
> test: add snapshot tests for hooks exports

- packages/core/src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.mdx
- packages/core/src/hooks/useActiveDescendantListFocus/__stories__/useActiveDescendantListFocus.mdx
- packages/core/src/hooks/useAfterFirstRender/__stories__/useAfterFirstRender.mdx
- packages/core/src/hooks/useClickOutside/__stories__/useClickOutside.mdx
- packages/core/src/hooks/useClickableProps/__stories__/useClickableProps.mdx
- packages/core/src/hooks/useDebounceEvent/__stories__/useDebounceEvent.mdx
- packages/core/src/hooks/useDisableScroll/__stories__/useDisableScroll.mdx
- packages/core/src/hooks/useEventListener/__stories__/useEventListener.mdx
- packages/core/src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.mdx
- packages/core/src/hooks/useHover/__stories__/useHover.mdx
- packages/core/src/hooks/useIsOverflowing/__stories__/useIsOverflowing.mdx
- packages/core/src/hooks/useKeyEvent/__stories__/useKeyEvent.mdx
- packages/core/src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.mdx
- packages/core/src/hooks/useMediaQuery/__stories__/useMediaQuery.mdx
- packages/core/src/hooks/usePrevious/__stories__/usePrevious.mdx
- packages/core/src/hooks/useSetFocus/__stories__/useSetFocus.mdx
- packages/core/src/hooks/useSwitch/__stories__/useSwitch.mdx
- packages/core/src/hooks/useTimeout/__stories__/useTimeout.mdx
- packages/core/src/hooks/useVibeMediaQuery/__stories__/useVibeMediaQuery.mdx
Documentation
___
- Update import paths in hook documentation files
- Change from `@vibe/core/hooks` to `@vibe/core` imports
- Standardize import statements across 19 hook MDX files
___
```mermaid
flowchart LR
A["Hook Documentation Files"] -- "Update import paths" --> B["Standardized @vibe/core imports"]
B -- "Remove /hooks suffix" --> C["Consistent import statements"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><details><summary>19 files</summary><table>
<tr>
<td><strong>useGridKeyboardNavigationContext.mdx</strong><dd><code>Update import path for useGridKeyboardNavigationContext</code>&nbsp; &nbsp; </dd></td>
<td><a …
> docs: fix import paths

- scripts/bundle-check/compare-bundles.js
Other
___
- Update bundle size change detection thresholds
- Changes under 1KB now treated as unchanged
- Significant changes threshold increased to 5KB
- Bold highlighting only for changes over 5KB
___
```mermaid
flowchart LR
A["Bundle Size Change"] --> B{"Size >= 1KB?"}
B -->|No| C["Treat as Unchanged"]
B -->|Yes| D{"Size >= 5KB?"}
D -->|No| E["Show Normal"]
D -->|Yes| F["Bold Highlight"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>compare-bundles.js</strong><dd><code>Update bundle size change thresholds</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> ci(bundle-check): update minimum change threshold to 1KB

- packages/core/src/components/Toggle/MockToggle.module.scss
- packages/core/src/components/Toggle/MockToggle.tsx
- packages/core/src/components/Toggle/Toggle.tsx
https://monday.monday.com/boards/3532714909/pulses/9798571029
___
Enhancement
___
- Add `noSpacing` prop to Toggle component
- Remove horizontal margins when enabled
- Update TypeScript interfaces and styling
___
```mermaid
flowchart LR
A["Toggle Props"] --> B["noSpacing prop"]
B --> C["MockToggle"]
C --> D["CSS styling"]
D --> E["Zero margins"]
```
<tr>
<td>
<details>
<summary><strong>MockToggle.module.scss</strong><dd><code>Add noSpacing CSS class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat(Toggle): add noSpacing prop to remove horizontal spacing

- .github/workflows/release-v2.yml
- .github/workflows/release.yml
https://monday.monday.com/boards/3532714909/pulses/9810597341
___
Enhancement
___
- Add Slack notifications for release workflow starts
- Configure notifications to continue on error
- Include actor information in notification messages
___
```mermaid
flowchart LR
A["Workflow Dispatch"] --> B["Notify Slack Job"]
B --> C["Send Slack Notification"]
C --> D["Continue to Release Job"]
B -.-> E["Continue on Error"]
```
<tr>
<td>
<details>
<summary><strong>release-v2.yml</strong><dd><code>Add Slack notification for V2 release</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> ci(release): add Slack notification for release start in workflows

- packages/core/src/components/Table/Table/Table.module.scss
- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.module.scss
- packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
https://monday.monday.com/boards/3532714909/pulses/9683972348
___
Enhancement
___
- Add custom scrollbar styling to Table components
- Import monday-ui-style mixins for consistent scrollbar appearance
- Apply 6px scrollbar dimensions to table and virtualized body
___
```mermaid
flowchart LR
A["Import mixins"] --> B["Apply scroller mixin"]
B --> C["Table component"]
B --> D["VirtualizedBody component"]
C --> E["6px custom scrollbar"]
D --> E
```
<tr>
<td>
<details>
<summary><strong>Table.module.scss</strong><dd><code>Add custom scrollbar to main table</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat(Table): use custom scrollbar

- packages/core/src/storybook/stand-alone-documentaion/mcp/mcp.mdx
- packages/mcp/README.md
https://monday.monday.com/boards/3532714909/pulses/9800176975
___
Documentation
___
- Updated Cursor MCP installation links in documentation
- Added `/en/` path and `-y` flag to installation URLs
___
```mermaid
flowchart LR
A["Old Cursor Links"] --> B["Updated Links"]
B --> C["Added /en/ path"]
B --> D["Added -y flag"]
```
<tr>
<td>
<details>
<summary><strong>mcp.mdx</strong><dd><code>Update Storybook MCP installation link</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> docs: update link in Storybook for auto-add MCP to Cursor

- .github/workflows/release-v2.yml
- .github/workflows/release.yml
https://monday.monday.com/boards/3532714909/pulses/9810597341
___
Other
___
- Replace Slack notification action with HTTP request action
- Switch from rtCamp/action-slack-notify to fjogeleit/http-request-action
- Add structured JSON payload with workflow metadata
- Include commit URLs and run URLs in notifications
___
```mermaid
flowchart LR
A["rtCamp/action-slack-notify@v2"] -- "replaced with" --> B["fjogeleit/http-request-action@v1"]
B --> C["Structured JSON payload"]
C --> D["Enhanced metadata"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>release-v2.yml</strong><dd><code>Update v2 release …
> ci: fix send slack notification

- packages/core/src/storybook/stand-alone-documentaion/mcp/mcp.mdx
- packages/mcp/README.md
- packages/mcp/package.json
- packages/mcp/scripts/extract-accessibility.js
- packages/mcp/src/index.ts
- packages/mcp/src/server/tools/get-vibe-component-accessibility.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9833472630
___
Enhancement
___
- Add new accessibility tool for Vibe components
- Extract accessibility requirements from component documentation
- Update build process to generate accessibility files
- Integrate tool into MCP server and documentation
___
```mermaid
flowchart LR
A["MDX Files"] --> B["Extract Script"]
B --> C["Accessibility Files"]
C --> D["MCP Tool"]
D --> E["AI Assistant"]
```
<tr>
<td>
<details>
<summary><strong>index.ts</strong><dd><code>Register accessibility tool in MCP server</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> feat: add getVibeComponentAccessibility tool to retrieve a11y requirements

- packages/core/src/components/AlertBanner/__stories__/AlertBanner.mdx
- packages/core/src/components/AttentionBox/__stories__/AttentionBox.mdx
- packages/core/src/components/Avatar/__stories__/Avatar.mdx
- packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.mdx
- packages/core/src/components/Button/__stories__/Button.mdx
- packages/core/src/components/ButtonGroup/__stories__/ButtonGroup.mdx
- packages/core/src/components/IconButton/__stories__/IconButton.mdx
- packages/core/src/components/Link/__stories__/Link.mdx
- packages/core/src/components/Menu/Menu/__stories__/Menu.mdx
- packages/core/src/components/Menu/MenuItem/__stories__/MenuItem.mdx
- packages/core/src/components/MenuButton/__stories__/MenuButton.mdx
- packages/core/src/components/Tabs/__stories__/Tabs.mdx
- packages/core/src/components/Toast/__stories__/Toast.mdx
- packages/core/src/components/Tooltip/__stories__/Tooltip.mdx
- packages/core/src/components/Tooltip/__stories__/Tooltip.stories.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9949065403
___
Documentation
___
- Add comprehensive accessibility guidelines for 13 UI components
- Enhance Tooltip stories with hideWhenReferenceHidden prop
- Improve Button accessibility documentation clarity
- Standardize accessibility section structure across components
___
```mermaid
flowchart LR
A["Component Documentation"] --> B["Accessibility Guidelines"]
B --> C["ARIA Props Usage"]
B --> D["Screen Reader Support"]
B --> E["Keyboard Navigation"]
F["Tooltip Stories"] --> G["hideWhenReferenceHidden Prop"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><details><summary>14 …
> docs: added accessibility sections

- packages/core/src/components/DropdownNew/Dropdown.types.ts
- packages/core/src/components/DropdownNew/components/Trigger/TriggerActions.tsx
- packages/core/src/components/DropdownNew/context/DropdownContext.types.ts
- packages/core/src/components/DropdownNew/modes/DropdownComboboxController.tsx
- packages/core/src/components/DropdownNew/modes/DropdownMultiComboboxController.tsx
- packages/core/src/components/DropdownNew/modes/DropdownMultiSelectController.tsx
- packages/core/src/components/DropdownNew/modes/DropdownSelectController.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9989991597
___
Enhancement
___
- Add loading state support to Dropdown component
- Display loading indicator in dropdown controls
- Update all dropdown controller modes
- Extend type definitions and context
___
```mermaid
flowchart LR
A["Dropdown Types"] --> B["Context Types"]
B --> C["Controller Modes"]
C --> D["Trigger Actions"]
D --> E["Loading Indicator"]
```
<tr>
<td>
<details>
<summary><strong>Dropdown.types.ts</strong><dd><code>Add loading prop to dropdown types</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> feat(Dropdown): add loading state

- packages/core/src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
- packages/core/src/components/Combobox/Combobox.tsx
- packages/core/src/components/DatePicker/date-picker-utils.ts
- packages/core/src/components/Dialog/Dialog.tsx
- packages/core/src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts
- packages/core/src/components/Slider/SelectionIndicator.tsx
- packages/core/src/components/Steps/StepsGalleryHeader.tsx
- packages/core/src/components/Tooltip/Tooltip.tsx
- packages/core/src/hooks/useDebounceEvent/index.ts
- packages/core/src/hooks/useElementsOverflowingIndex.ts
- packages/core/src/hooks/useResizeObserver.ts
- packages/core/src/hooks/useStyle.ts
- packages/core/src/hooks/useThrottledCallback.ts
- packages/core/src/utils/dom-utils.ts
- packages/core/src/utils/function-utils.ts
Other
___
- Replace es-toolkit/compat imports with es-toolkit
- Implement custom utility functions for removed compat functions
- Update function call signatures to match es-toolkit API
- Remove dependency on es-toolkit compat module
___
```mermaid
flowchart LR
A["es-toolkit/compat imports"] --> B["es-toolkit imports"]
A --> C["Custom utility implementations"]
D["compat function calls"] --> E["Updated API calls"]
C --> F["Inline utility functions"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>15 files</summary><table>
<tr>
<td><strong>date-picker-utils.ts</strong><dd><code>Replace times compat with custom …
> chore: remove compat from es-toolkit functions

- packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9960021405
___
Bug fix
___
- Fixed controlled multi-select dropdown item selection logic
- Simplified item toggle mechanism using existing downshift methods
- Added proper reset functionality for controlled components
- Ensured consistent state management between controlled and uncontrolled modes
___
```mermaid
flowchart LR
A["Item Selection"] --> B["Check if exists"]
B --> C["Remove if exists"]
B --> D["Add if new"]
C --> E["Update state"]
D --> E
E --> F["Reset functionality"]
```
<tr>
<td>
<details> …
> fix(DropdownNew): Searchable controlled multi dropdown item selection

- packages/core/src/components/DropdownNew/Dropdown.types.ts
- packages/core/src/components/DropdownNew/__stories__/Dropdown.mdx
- packages/core/src/components/DropdownNew/__stories__/Dropdown.stories.tsx
- packages/core/src/components/DropdownNew/components/Menu/Menu.tsx
- packages/core/src/components/DropdownNew/components/Trigger/TriggerActions.tsx
- packages/core/src/components/DropdownNew/context/DropdownContext.types.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownMultiSelect.ts
- packages/core/src/components/DropdownNew/hooks/useDropdownSelect.ts
- packages/core/src/components/DropdownNew/modes/DropdownComboboxController.tsx
- packages/core/src/components/DropdownNew/modes/DropdownMultiComboboxController.tsx
- packages/core/src/components/DropdownNew/modes/DropdownMultiSelectController.tsx
- packages/core/src/components/DropdownNew/modes/DropdownSelectController.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/9912832751
___
Enhancement
___
- Add `clearAriaLabel` prop for clear button accessibility
- Add `id` prop to dropdown hooks for proper labeling
- Enhance multi-select menu with `aria-multiselectable` attribute
- Update state management for better keyboard navigation
___
```mermaid
flowchart LR
A["BaseDropdownProps"] --> B["clearAriaLabel prop"]
C["Dropdown hooks"] --> D["id parameter"]
E["Menu component"] --> F["aria-multiselectable"]
G["TriggerActions"] --> H["Clear button aria-label"]
I["State reducers"] --> J["highlightedIndex management"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td>< …
> feat(DropdownNew): a11y improvements

- packages/core/src/components/Dialog/Dialog.tsx
https://monday.monday.com/boards/3532714909/views/80492480/pulses/18008006522
___
Enhancement
___
- Add LayerProvider wrapper to Dialog component
- Implement ref merging for container reference
- Import chainRefFunctions utility for ref handling
___
```mermaid
flowchart LR
A["Dialog Component"] --> B["LayerProvider Wrapper"]
B --> C["DialogContent"]
D["containerRef"] --> E["mergedRef"]
E --> C
```
<tr>
<td>
<details>
<summary><strong>Dialog.tsx</strong><dd><code>Add LayerProvider wrapper with ref merging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix(Dialog): add LayerProvider

- packages/core/src/components/DropdownNew/Dropdown.types.ts
https://monday.monday.com/boards/4776335071/pulses/10060403873
___
Bug fix
___
- Fix TypeScript types for `onChange` callbacks
- Add new `DropdownOption` type export
- Simplify generic type constraints in callbacks
___
```mermaid
flowchart LR
A["BaseListItemData<Item>"] --> B["Item"]
C["DropdownOption type"] --> D["Type exports"]
B --> E["onChange callbacks"]
```
<tr>
<td>
<details>
<summary><strong>Dropdown.types.ts</strong><dd><code>Fix onChange callback types and add DropdownOption export</code></dd></summary>
<hr>
packages/core/src/components/DropdownNew/Dropdown.types.ts
<ul><li>Export new …
> feat(DropdownNew): fix types
