src/components/Tooltip/Tooltip.scss

This is a change of the tooltip color to support dark theme.
It will know have the inverted-color-background instead of the mud background, So in dark theme the background can be light
- [V] PR has description
- [V] Changes to the component are backward compatible (including selectors structure). If not - add to the title of the PR "BREAKABLE_CHANGE""
- [V] All changes to the component are reflected in the ReadMe
- [V] If component is old and was not compliant with the latest guidelines - it was fixed (optional) 
- [V] CSS selectors are named using [BEM convention](http://getbem.com/naming/) 
- [V] Design is compatible with [Monday Design System](https://design.monday.com/)
- [V] All the changes to the component should be reflected in the Storybook.
- [V] Component passed Accessibility …

Tooltip inverted color instead of mud

---

plop/component/component-js.txt
src/components/Banner/Banner.jsx
src/components/Banner/Banner.scss
src/components/Banner/BannerConstants.js
src/components/Banner/__stories__/banner.stories.js
src/components/Banner/__tests__/__snapshots__/banner.jest.js.snap
src/components/Banner/__tests__/banner.jest.js
src/components/Dropdown/__stories__/dropdown.stories.js
src/components/index.js
src/published-components.js

Description:
* Add new component - Banner
* Fix plop file for component
* Make dropdown story better by including options creation in the story

feat: Add Banner component

---

src/components/Banner/Banner.jsx
src/components/Banner/Banner.scss
src/components/Banner/__tests__/__snapshots__/banner.jest.js.snap
src/components/DialogContentContainer/DialogContentContainer.scss
src/components/Dropdown/__stories__/dropdown.stories.js
src/components/Dropdown/components/SingleValue/SingleValue.scss
src/components/Menu/Menu/Menu.scss
src/components/MenuButton/MenuButton.jsx
src/components/MenuButton/__stories__/menuButton.stories.js
src/components/Tooltip/Tooltip.scss

- Styling for menu was fixed - no outline on focus for menu and children
- Banner spacing and font size for subtitle was adjusted
- Fixed small logical issue in MenuBetton.jsx - openDialogComponentClassName was added as empty string if it was not assigned.

fix: styling for menu and banner

---

src/components/ResponsiveList/ResponsiveList.scss
src/components/ResponsiveList/__stories__/responsiveList.stories.js
src/hooks/useElementsOverflowingIndex.js

Had a dropdown, and it didn't work with the responsive component, cause it has overflow hidden:
Changed it to work without overflow hidden

responsive without overflow hidden

---

src/components/Toast/Toast.jsx
src/components/Toast/Toast.scss
src/components/Toast/__stories__/toast.stories.js

give access to toast types, css change and add support on class name property
before:
after:

margin between toast button & give access to toast types 

---

src/components/ResponsiveList/ResponsiveList.jsx
src/components/ResponsiveList/__stories__/responsiveList.stories.js

Had a bug since it's drawing twice, once visible and once invisible.
Used responsiveListPlaceholder to fix it.
In the storybook example, I checked that it added an id to the placeholder search.
otherwise it had two ids and the accessibility tab shout about it.

responsive list placeholder

---

src/components/Tipseen/Tipseen.jsx
src/components/Tipseen/TipseenContent.jsx
src/components/Tipseen/__stories__/tipseen.stories.js
src/components/Tipseen/__tests__/__snapshots__/tipseenContent.jest.js.snap
src/components/Tipseen/__tests__/tipseenContent.jest.js
src/components/Tooltip/Tooltip.jsx
src/helpers/backwardCompatibilityForProperties.js

Description: Add support in tipseen component for: submitButtonText & submitButtonOnClick & dismissButtonText & dismissButtonOnClick & hideWhenReferenceHidden.
The change in the button props is moshe tzemach idea after reviewing the tipseen in monolith changes.
The hideWhenReferenceHidden support is for fixing the monolith bug.
- [v] PR has description
- [v] All changes to the component are reflected in the ReadMe
- [v] All the changes to the component should be reflected in the Storybook.
- [v] Component passed Accessibility Plugin checks
- [v] All current tests are passing
- [v] New functionality is covered with tests
- [v] Tests are compliant with TESTING_README.md instructions

Add support in tipseen component for: submitButtonText & submitButtonOnClick & dismissButtonText & dismissButtonOnClick & hideWhenReferenceHidden

---

src/components/Combobox/__stories__/combobox.stories.js
src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx

Adding tooltip content option to combobox item

---

src/components/Combobox/__tests__/__snapshots__/combobox.jest.js.snap
src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
src/components/Combobox/components/ComboboxOption/ComboboxOption.scss

The first item was close to the search. added spacing to it.

Combobox: fix the space between the search box to the first option

---

src/components/AttentionBox/AttentionBox.jsx
src/components/AttentionBox/__stories__/attentionBox.stories.js
src/components/AttentionBox/__tests__/attentionBox.jest.js
src/components/Checkbox/Checkbox.js
src/components/Checkbox/__stories__/checkbox.stories.js
src/components/Checkbox/__tests__/checkbox.jest.js

Description: Add support on className to Checkbox&AttentionBox instead of componentClassName
- [v] PR has description
- [] Changes to the component are backward compatible (including selectors structure). If not - add to the title of the PR "BREAKABLE_CHANGE""
- [v] All changes to the component are reflected in the ReadMe
- [v] If component is old and was not compliant with the latest guidelines - it was fixed (optional) 
- [ v] All the changes to the component should be reflected in the Storybook.
- [v ] Component passed Accessibility Plugin checks
- [ v] All current tests are passing
- [ v] New functionality is covered with tests
- [v ] Tests are compliant with TESTING_README.md instructions

Add support on className to Checkbox&AttentionBox instead of componentClassName

---

src/storybook/components/link/link.jsx
src/storybook/components/link/link.scss

fix spacing in links

---

src/components/Checkbox/Checkbox.js
src/components/Checkbox/__tests__/__snapshots__/checkbox.jest.js.snap
src/components/Checkbox/__tests__/checkbox.jest.js

for cases the checkbox label is complex outside element and the developer cannot use aria label by.

add aria label support for checkbox

---

src/components/Link/Link.jsx

link component - fixing missing event not passed into onClick using the new wrapper.

pass event to onclick

---

src/components/MenuButton/MenuButton.jsx

Add props `dialogShowTriggerIgnoreClass` and `dialogHideTriggerIgnoreClass` which are passed to the Dialog's corresponding props. Exposing these on MenuButton will allow users to craft more complex menu button use cases. 
Example usage of `dialogShowTriggerIgnoreClass`:
Creating more involved menu button components (via prop `component`) and using `dialogShowTriggerIgnoreClass` to prevent all clicks withing target area from opening the dialog.
Example usage of `dialogHideTriggerIgnoreClass`:
My use case 😄 - Allow users to create sub-hierarchies of MenuButtons and not having all clicks within the sub-dialogs close the parent dialog

add MenuButton props to control dialog hide/show trigger ignore class

---

src/components/MenuButton/MenuButton.jsx
src/components/MenuButton/__stories__/menuButton.stories.js

The MenuButton at its core is.. a button. I can imagine there are plenty of legitimate scenarios where a user would want to perform some logic when it's clicked. What's the harm in exposing an `onClick`? This is in addition to and would not directly affect the "show dialog" trigger. 
Also, when MenuButton was not passed any `children`, instead of rendering a Dialog with an empty div, just don't render the dialog at all. (The Dialog component already gracefully handles being passed `content` of null)

add MenuButton onClick prop

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/__tests__/driver.js
src/components/Dropdown/__tests__/dropdown.jest.js

At the moment, if the `<Dropdown>` is just a regular, controlled dropdown with a single value, it'll break since we try to run `.reduce` on it.

Fix `<Dropdown>` multi-value bug

---

src/components/Dropdown/__tests__/dropdown.jest.js
src/components/Tipseen/Tipseen.jsx
src/components/Tooltip/Tooltip.jsx

skip bad multiselect tests until it will fix and add modifiers support on tooltip and tipseen

add modifiers support to tipseen and tooltip

---

src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
src/utils/colors-utils.js

we want to export color utils for everyone. until now we don't have a default export on the color utils file which is problematic when I try to export the color utils file

export color utils as default object (for fixing error while trying to create new version)

---

src/components/Accordion/Accordion/Accordion.jsx

Until now the allow multiple functionality was buggy because the on click functionality was not working as excepted

Fix bugs on allow multiple on click

---

src/components/Avatar/Avatar.jsx
src/components/Avatar/__stories__/avatar.stories.mdx
src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.jsx
src/components/BreadcrumbsBar/BreadcrumbItem/__stories__/breadcrumbItem.stories.mdx
src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/breadcrumbItem-snapshot-tests.jest.js
src/components/Counter/Counter.jsx
src/components/Counter/__stories__/counter.stories.mdx
src/components/Counter/__tests__/__snapshots__/counter-snapshot-tests.jest.js.snap
src/components/Label/Label.jsx
src/components/Label/__stories__/label.stories.mdx
src/components/Label/__tests__/__snapshots__/label-snapshot-tests.jest.js.snap
src/components/Loader/Loader.jsx
src/components/Loader/__tests__/loader-snapshots.jest.js
src/components/Toggle/Toggle.jsx
src/components/Toggle/__stories__/toggle.stories.mdx
src/components/Toggle/__tests__/toggle-snapshot-tests.jest.js
src/components/Toggle/__tests__/toggle-tests.jest.js

add support on consistent API for all the library components for class name and disabled props
- [ V] PR has description.

Add support on consistent API for all the library components for class name and disabled props

---

src/components/Menu/Menu/Menu.jsx
src/components/Menu/MenuItem/MenuItem.jsx

As we talked about now you can pass arg to menu that will scroll to the active menu item if needed

Bugfix : scroll menu if needed

---

src/hooks/__tests__/useKeyEvent.jest.js
src/hooks/useKeyEvent/index.js

Enhance use key event hook to support modifiers

Enhance use key event

---

src/components/Button/__stories__/button.stories.mdx
src/components/Link/Link.jsx
src/components/Link/__stories__/Link.stories.mdx
src/components/Steps/Steps.jsx
src/components/Toast/__stories__/toast.stories.mdx
src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx

fix links story controls, add leanylabs as contributors and add few description to props

---

src/components/Menu/Menu/__stories__/menu.stories.js

Small fix for the code example of `Menu with 2-depth sub menu`.
| Before | After |
| - | - |
| ![image](https://user-images.githubusercontent.com/96776835/148681830-7fc5e416-34ae-4b8a-b14a-94945e902354.png) |  ![image](https://user-images.githubusercontent.com/96776835/148681843-8c84fa8e-6503-455f-8b24-a87b1dfdba46.png) |

Fixed code example of 'Menu with 2-depth sub menu'

---

.storybook/main.js
src/components/Button/__stories__/button.stories.mdx
src/components/ColorPicker/__stories__/ColorPicker.stories.mdx
src/storybook/functions/create-component-story.js

Added [Storybook actions](https://storybook.js.org/docs/react/essentials/actions), which can be easily configured to show callback examples.
I added it only to two components for now, just as a test case.
I found it useful for my current task, but please let me know if you think it shouldn't be used.

Storybook actions

---

src/components/index.js

icon button export

---

src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
src/components/GridKeyboardNavigationContext/helper.js

[Task](https://monday.monday.com/boards/470024321/pulses/2123616392)
The fix prevents cases where a reference to an unmounted component "steals" the focus for the actual element that we want to focus when navigating into an element. For example, when navigating up into a vertical list that has conditional rendering of the items.

Keyboard nav context improvements

---

src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.js
src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.mdx
src/components/GridKeyboardNavigationContext/__stories__/useGridKeyboardNavigationContext.stories.scss
src/components/GridKeyboardNavigationContext/__tests__/helper.jest.js
src/components/GridKeyboardNavigationContext/helper.js

[Task](https://monday.monday.com/boards/245345663/pulses/2205952071)
Skipping disabled container components in keyboard navigation.
(NOTE: this does not affect the "grid navigation", which occurs inside the grid. items won't be skipped there)

Skipping disabled components while navigating

---

src/components/Menu/Menu/Menu.jsx
src/components/Menu/Menu/hooks/useMenuKeyboardNavigation.jsx
src/components/Menu/MenuItem/MenuItem.jsx

Small refactor, no actual change - mostly prettier. I split it to avoid big PRs.

Menu item small refactor

---

src/components/Menu/MenuItem/MenuItem.jsx

Hovering a sub menu didn't work since the wrong ref was used. 
This bug was introduced in [my previous changes](https://github.com/mondaycom/monday-ui-react-core/pull/492).

Fixed menu item hover

---

src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.jsx
src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx
src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.jsx
src/components/ColorPicker/components/ColorPickerItemComponent/ColorPickerItemComponent.scss

[Task](https://monday.monday.com/boards/245345663/pulses/2213221889)
Came as a request from Evgeniy: previously, the icon was black - looking bad on darker colors. The white icons look good on all colors.
Also, the icon will now show even when isMultiSelection is false.

ColorPicker - white selected icon, even not on multi selection

---

src/hooks/useGridKeyboardNavigation/__tests__/useGridKeyboardNavigation.jest.js
src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.js

[Task](https://monday.monday.com/boards/245345663/pulses/2213226987)
(Evgeniy's request)
Previously, the keyboard's activeIndex feedback appeared even after selecting items with the mouse. This caused "noise", since mouse-users didn't actually need to see the feedback.
This change shouldn't have any functional effect.

Disabling activeIndex after a non-keyboard interaction

---

src/components/Checkbox/Checkbox.js
src/components/Checkbox/__stories__/checkbox.stories.mdx
src/components/Checkbox/__tests__/checkbox-tests.jest.js
src/components/Checkbox/hooks/useSupportFirefoxLabelClick.jsx

When click on checkbox with shift pressed, shift key is not true in the manual all checkbox events (even if it was true in the original event)

---

src/components/Combobox/Combobox.jsx
src/components/Combobox/__stories__/combobox.stories.mdx
src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
src/components/Combobox/__tests__/combobox-snapshot-tests.jest.js
src/components/Combobox/components/ComboboxCategory/ComboboxCategory.jsx

add divider to combo box categories

---

src/components/Dropdown/Dropdown.jsx

Dropdown - add isOptionSelected prop

Dropdown - add isOptionSelected prop

---

src/components/Tooltip/Tooltip.scss
src/components/Tooltip/TooltipConstants.js
src/components/Tooltip/__stories__/tooltip.stories.mdx

1. removing the border from the tooltip's arrow as it added some weird border around it.
from
to
2. adding tooltip themes to storybook
3. exposing white theme

tooltip: removing border from tooltip arrow + adding themes to storybook

---

src/components/GridKeyboardNavigationContext/GridKeyboardNavigationContext.js
src/components/GridKeyboardNavigationContext/__tests__/GridKeyboardNavigationContext.jest.js
src/components/Menu/Menu/__stories__/menu.stories.js
src/components/Menu/MenuGridItem/MenuGridItem.jsx
src/components/Menu/MenuGridItem/__stories__/MenuGridItem.stories.mdx
src/components/Menu/MenuGridItem/__tests__/useFocusGridItemByActiveStatus.jest.js
src/components/Menu/MenuGridItem/useFocusGridItemByActiveStatus.jsx
src/components/Menu/MenuItem/MenuItem.jsx

[Task](https://monday.monday.com/boards/245345663/pulses/2307148964)
I've added better handling for `useDocumentEventListeners`. On other Menu-related components, most of the handlers are being disabled when `useDocumentEventListeners = true`. I've matched the critical paths' behavior, to avoid stealing the focus when not intended.
NOTE: `MenuGridItem` will not work properly when `useDocumentEventListeners = true`, since most of the handlers will now be turned off. I assume here that there's no such use case yet, since `MenuGridItem` is very new, and `useDocumentEventListeners` is rarely used.

Better support for useDocumentEventListeners on Menu components

---

src/components/Menu/MenuItem/MenuItem.jsx
src/components/Menu/MenuItem/__stories__/MenuItem.stories.js
src/components/Menu/MenuItem/__stories__/MenuItem.stories.mdx
src/components/Tooltip/Tooltip.scss

tooltip is shown only for disabled and disabled reasons. Adding support for plain tooltip content.

support passing tooltip content without disabled mode

---

src/components/Dropdown/Dropdown.jsx

Added menuPlacement prop to Dropdown component

---

src/components/Dropdown/Dropdown.styles.js
src/components/Dropdown/__stories__/dropdown.stories.mdx

Add dropdown groups to storybook and change style.

Add dropdown groups to storybook and change dropdown groups style

---

src/components/Avatar/__stories__/avatar.stories.mdx

This fixes typos of the word "multiple" in reference to multiple avatars. The typo read `Multiplue` in a few instances

Fix typo of the work Multiple

---

src/hooks/useEventListener/__stories__/useEventListener.stories.mdx

This corrects a typo to the word "hover". Previously it read "Hoover"

Fixes a typo to the word "hover"

---

.storybook/manager-head.html

Preventing longer story names from being cropped.
1. The user is still allowed to resize the panel like before
2. if the user has resized the panel to a larger value than `DEFAULT_MINIMUM_LEFT_PANEL_WIDTH`, it will be saved in the local storage (like it was saved before this PR)
3. if the user decreases the panel width to below `DEFAULT_MINIMUM_LEFT_PANEL_WIDTH`, it will be reset to `DEFAULT_MINIMUM_LEFT_PANEL_WIDTH` on the next reload
| Before | After | 
| - | - | 
| ![image](https://user-images.githubusercontent.com/96776835/159966742-92f78773-73a0-494f-9369-ace9ab0f33ba.png) | ![image](https://user-images.githubusercontent.com/96776835/159966772-3e845696-1908-420e-8e31-f14473c949dd.png) |

Increase default width of left panel

---

src/components/ColorPicker/ColorPicker.jsx
src/components/ColorPicker/__tests__/colorPicker.jest.js
src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.jsx
src/components/ColorPicker/components/ColorPickerContent/ColorPickerContentComponent.jsx

Description: adding a flag to ColorPicker for showing color name tooltips

feat: adding a flag to ColorPicker for showing color name tooltips

---

src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.jsx
src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbItem.jsx

Breadcrumbs accessibility fixes:
- Add an optional disabled prop to `BreadcrumbContent` according to `disabled || isDisabled` in `BreadcrumbItem`.
- If `BreadcrumbItem` is disabled, sets the tabindex attribute to `-1`.

Support on disabled tabIndex

---

src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/breadcrumbItem-snapshot-tests.jest.js.snap
src/components/Combobox/Combobox.jsx
src/components/Combobox/__stories__/combobox.stories.mdx
src/components/Combobox/components/ComboboxItems/ComboboxItems.jsx
src/components/Combobox/components/ComboboxOption/ComboboxOption.jsx
src/components/Combobox/components/ComboboxRenderers/ComboboxRenderers.jsx

Add flag for undo a null check which cause weird behavior (combobox) 

---

src/components/Search/__stories__/Search.stories.mdx

The link referred on the Tip box is broken. Suggestion to remove it unless there is a new Canvas component with a different name. 
Sorry for putting my nose in 😅   just find out the bug and Orr told me this is open source.

fix: Remove Tip box

---

src/components/Avatar/Avatar.jsx
src/components/Avatar/AvatarContent.jsx
src/components/Avatar/__stories__/avatar.stories.mdx
src/components/Avatar/__stories__/avatar.stories.scss

We needed Avatar custom initials text styling in New Automation Store. To achieve it I added class property for text to be able to override default styling.

feat/Chris/ make Avatar initials text styling customisable

---

src/components/Clickable/Clickable.jsx

https://monday.monday.com/boards/245345663/pulses/2836633046
Clickable: added aria-hasPopup prop. All made in order to make monolith menu button accessible

Clickable: ariaHasPopup prop

---

src/components/Chips/Chips.jsx
src/components/Chips/Chips.module.scss
src/components/Chips/__tests__/__snapshots__/chips-snapshot-tests.jest.js.snap

https://monday.monday.com/boards/245345663/pulses/2867072856
Module styles to Chips in order to avoid css overrides like in case of Etay Liberman (https://monday.slack.com/archives/C02S6F817JQ/p1656349368074379)
Breaking changes, cause originally css styles naming was not unique (`.label`) and there is no way to support backward compatibility. But probably need to change also known usages of Chips where styles get overriding

Add css module support for chips component

---

src/components/Clickable/Clickable.jsx

https://monday.monday.com/boards/2861766393/pulses/2889507649
Added aria-expanded attribute regarding the monolith menu a11y task

Clickable: ariaExpanded prop added

---

src/components/EditableHeading/EditableHeading.jsx
src/components/EditableHeading/__stories__/EditableHeading.stories.mdx
src/components/Heading/Heading.jsx

https://monday.monday.com/boards/2861766393/pulses/2963392067
* Add brandFont prop
* Edit storybook example

Enable brandFont prop for heading within editable heading.

---

package-lock.json
package.json

Something went wrong with the `Update monday-ui-style` Github action. It detected the latest version and installed it without errors, but this changes weren't merged to the master. Rerun doesn't help. So doing it manually for now
https://github.com/mondaycom/monday-ui-react-core/runs/7429513118?check_suite_focus=true

Manually update monday-ui-style version to 0.1.132

---

package.json
scripts/build-esm.js

https://monday.monday.com/boards/245345663/views/62248892/pulses/2970462587
using [exports](https://webpack.js.org/guides/package-exports/) in package json to specify path for icons pointing to a newly created dist/icons/index.js file listing all available icons to support tree shaking.
We can now do `import { Close } from 'monday-ui-react-core/icons';` and tree shaking works fine.  
CommonJs and /dist path mapping still works for backward compatibility but I think we should add a dageroid rule discouraging linking directly into the dist folder

add exports to package.json + build icons esm file

---

src/components/Button/Button.scss
src/components/Checkbox/Checkbox.scss
src/components/Dropdown/Dropdown.scss
src/components/Dropdown/components/menu/menu.scss
src/components/ExpandCollapse/ExpandCollapse.scss
src/components/MenuButton/MenuButton.scss
src/components/ProgressBars/LinearProgressBar/LinearProgressBar.scss
src/components/RadioButton/RadioButton.scss
src/components/Skeleton/Skeleton.scss
src/components/Slider/SliderBase/SliderBase.scss
src/components/SplitButton/SplitButton.scss
src/components/Steps/Steps.scss
src/components/TextField/TextField.scss
src/components/Toggle/Toggle.scss

Replace "--expand-animation-timing" with "-motion-timing-enter" Globally
Replace "--expand-animation-timing" with "--motion-timing-transition" on selected components that are not changing their position.
https://monday.monday.com/boards/2861766393/pulses/3045493065

Update easing tokens

---

src/components/AttentionBox/AttentionBox.jsx
src/components/AttentionBox/AttentionBox.scss
src/components/AttentionBox/AttentionBoxConstants.js
src/components/AttentionBox/__tests__/__snapshots__/attentionBox-snapshot-tests.jest.js.snap

https://monday.monday.com/boards/2861766393/pulses/3086884014
[Chromatic link](https://62037c72e0e4d6004a9a450f-hctauvthuj.chromatic.com/?path=/docs/feedback-attentionbox--overview)
- Need to pay attention to Icon size. It's 20 x 20 now, not 24 x 24 as it was before. This happens due to limitations of current IconButton implementation - you can get Icon size = 24 only if `size` prop of `IconButton` equals `undefined`, but that's really not ever going to happen, cause there is a default value for `size: IconButton.sizes.MEDIUM`. So probably need to fix this `IconButton` logic as well
- Should tooltip be displayed on button focus?
- Also some refactor was made to make further css modules automation easier :)

AttentionBox - close icon button instead of icon

---

src/components/Checkbox/Checkbox.js
src/components/Checkbox/__stories__/checkbox.stories.mdx
src/components/Checkbox/__tests__/__snapshots__/checkbox-snapshot-tests.jest.js.snap
src/components/Checkbox/__tests__/checkbox-snapshot-tests.jest.js

- as part of effort to reduce number DOM nodes
- for some repeated elements (ex.: cells in table)
it is important to remove unneeded DOM elements

feat(checkbox): add ability to render component without label

---

src/components/Button/Button.scss
src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap

https://monday.monday.com/boards/2861766393/pulses/3258790807
* Add max for width and height to solve dimension grow when under flex parent with child set to grow.

Fix flex grow loading state size.

---

src/components/Modal/useShowHideModal.js

Hello,
This PR fixes an issue if the `onClose` callback is undefined when hidding a modal.

fix: onClose can be undefined when hidding the modal

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/DropdownConstants.js
src/components/Dropdown/__tests__/__snapshots__/dropdown-snapshot-tests.jest.js.snap

Overflow mode is a mode of a dropdown component when the menu is displayed in fixed position for display above modals with absolute position while the dropdown menu need to display outside of the modal. In this state we can't scroll because  then the menu of the dropdown position will look broken (because the fix position).
This fix allow to separate between a scroll of the menu (which is ok and we want to allow it) and a scroll of the document (which should trigger closing the dropdown menu)

Fix bug: scroll inside dropdown in overflow mode

---

src/components/Dialog/Dialog.scss

https://monday.monday.com/boards/2861766393/pulses/3506070789
Fix this bug

Fix tooltip-arrow color to adapt to the theme

---

src/storybook/stand-alone-documentaion/welcome/other-contributors-list/other-contributors-list.jsx

Quick fix for `TypeError: contributorsJson.filter is not a function`

Check if contributorsJson is an array before filtering

---

src/components/SplitButton/SplitButton.tsx

https://monday.monday.com/boards/3532714909/pulses/3563804766

Fix: Revert splitButton default props to old-fashioned defaultProps

---

src/components/Icon/Icon.tsx

It is considered unsafe to render a component directly from the class or function if you're getting it from props. The best practice for that is to create the element with React and pass it around.
This fix will should remove many warnings about rendering custom components that are not following the PascalCase naming.

Icon: follow create component best practices.

---

src/components/Button/Button.scss
src/components/IconButton/IconButton.tsx
src/components/IconButton/__tests__/__snapshots__/iconButton-snapshot-tests.jest.tsx.snap
src/components/SplitButton/SplitButton.scss
src/components/SplitButton/SplitButton.tsx

https://monday.monday.com/boards/3533418254/pulses/3534468566
According to meirav request updating active state to be the same for icon button and button (menu button is already support this)
tertiary:
secondary:

Same behaviour for active button ,active split button and active icon button

---

.storybook/preview.js
package-lock.json
package.json
rollup.config.js
src/index.js
src/style-imports.ts
src/styles/themes.scss
webpack.config.js
webpack/published-components.js

After the rollup migration we had an issue where we were trying to load monday-ui-style css with the wrong path
this fix fixes it by moving the import to the a ts file and combining it with the webpack build as multiple entries

fix css build issue :(

---

src/components/TextField/TextField.tsx

Important in case of using the textField inside a form wrapper, posting requests.

added name prop to textField

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/__stories__/dropdown.stories.mdx

Exposed 2 props relevant for loading state in the dropdown. These props exist in react-select, just wern't propogated to it.
https://user-images.githubusercontent.com/103024234/221595853-c3905d07-48e7-4a0f-b036-a3cb9f1e6cc6.mov

feature: added isLoading and loadingMessage props into Dropdown

---

src/components/Menu/Menu/Menu.tsx
src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
src/components/Menu/Menu/__tests__/menu.jest.js
src/components/Menu/MenuItem/MenuItem.tsx
src/utils/function-utils.ts

https://monday.monday.com/boards/3532714909/pulses/4328988728
By request: https://monday.slack.com/archives/C02S6F817JQ/p1681833672598009?thread_ts=1681828071.936349&cid=C02S6F817JQ
Feels like an overkill most definitely... not sure if we even need this...
Other solution would be just to omit Id from Menuitem props - and let people use its index combined with menuId

MenuItem id

---

scripts/build-utils.js
webpack/published-ts-components.js

Solves https://github.com/mondaycom/monday-ui-react-core/issues/1243
Include in the `dist/types.d.ts` file exports for components not yet migrated to ts (specifically `Dropdown`).
I also fixed the export path of `useSwitch` and add an empty line at the bottom of the file
This will now expose the following:
```ts
export { default as Button } from "./types/components/Button/Button";
.
.
.
export { default as useSwitch } from "./types/hooks/useSwitch";
.
.
.
declare const ResponsiveList: any;
declare const MultiStepIndicator: any;
declare const Dropdown: any;
declare const GridKeyboardNavigationContext: any;
declare const allIcons: any;
```

chore: expose entry in types for non-ts components

---

src/components/Avatar/__stories__/avatar.stories.mdx
src/components/AvatarGroup/__stories__/AvatarGroup.stories.mdx

The motivation is to allow a predictable copy-paste of the code snippet.
There are still some issues:
1. serialized code using the story `args` means also the `size` / `type` prop is serialized and doesn't appear as an enum
2. other examples are still using the relative path.
Will be happy for your comments and suggestions

chore: <Avatar/>, <AvatarGroup/> - update stories to show absolute urls to files and fix Avatar story to use AvatarGroup

---

src/storybook/components/visual-description/visual-description.jsx
src/storybook/stand-alone-documentaion/typography/text-styles/text-styles.jsx

Following the definition Figma: https://www.figma.com/file/UcjPooakzpU4lZyKCD2Pim/%F0%9F%A6%8B-New-typography-styles-%F0%9F%A6%8B?type=design&node-id=1-33&t=Ub5dYimpeTjCUNWs-4
1. map directly to the CSS vars
2. change titles a bit
3. remove the story CSS overrides to align the typography example to the description. The example might look bad, but this is the actual code we have and it should be resolved
</div>
Before:
After:

chore: fix typography docs to map to the exact typography css vars

---

src/components/Checkbox/__stories__/checkbox.stories.mdx
src/components/IconButton/__stories__/IconButton.stories.mdx

Seems like display bug had been occured due to inappropriate component import usage, so i fixed it :)
<details>
<summary>Screenshot comparsion</summary>
Before:
After:
</details>
Also slightly faced up usage example on IconButton page too.
<details>
<summary>Screenshot comparsion</summary>
Before:
After:
</details>

fix: incorrect display of Checkbox page in docs

---

src/components/Steps/StepsGalleryHeader.module.scss

https://monday.monday.com/boards/3532714909/pulses/4547079320
Fixes absence margin between the `GalleryHeaderDot`(s)

fix: <StepsGalleryHeader> - galleryHeaderDot increase specificity

---

src/components/Dialog/__stories__/Dialog.stories.mdx

Add a very basic example of using the Dialog in a controlled mode.
We probably hide here an issue of mixture between controlled and uncontrolled states, but at least we can be overcome it like this

chore: < Dialog > add an example for basic controlled component

---

src/components/Accordion/Accordion/Accordion.tsx

Accordion component was exposed as a simple `React.FC` which shadowed the VibeComponentProps.
This PR changes the declared type in order to expose all available props to the users.

Accordion: change declared type to VibeComponent.

---

src/components/Accordion/Accordion/Accordion.tsx

porting this fix
https://github.com/mondaycom/monday-ui-react-core/pull/1364

fix: < Accordion >: change declared type to VibeComponent

---

src/components/MultiStepIndicator/components/StepIndicator/StepIndicator.module.scss

could not reproduce in the storybook, but probably a case of long content and missing constraints

fix: MultiStepIndicator - fix divider to not squeeze bullets

---

src/components/Accordion/Accordion/Accordion.tsx
src/components/Accordion/AccordionItem/AccordionItem.tsx

Vibe props on Accordion and AccordionItem were not recognized by clients of the package. The reason was because importing of the type was with an absolute path and during the TS build, the type "got lost".

Accordion: fix vibe props are not recognized.

---

tsconfig.json

note: in current config, this should allow having full source map in a prod build and eval in dev mode (storybook)

chore: enable source maps in tsconfig

---

src/components/Combobox/Combobox.tsx

Combobox' `onOptionHover` prop was exposed as a no argument props instead of exposing the arguments that are sent with it. 
This PR adds the relevant data to the type definition.

Combobox: expose actual type instead a no argument on hover callback.

---

src/hooks/useIsOverflowing/useIsOverflowing.ts

We saw some long task on the browser coming from `Heading` component, seems that the source of the issue is this styling accessing:
```
function checkOverflow(element: HTMLElement, ignoreHeightOverflow: boolean) {
...
const isOverflowing =
element.clientWidth < element.scrollWidth || (!ignoreHeightOverflow && element.clientHeight < element.scrollHeight);
...
}
```
We might can improve this, but first thing we can do is to reduce the times it calling this function by changing the `useState` function invocation to only call this once.

improve useState to only called once in useIsOverflowing

---

src/components/DatePicker/DatePicker.module.scss

https://monday.monday.com/boards/3532714909/pulses/4803862196
Before:
---
After:

fix(DatePicker): do not set vertical alignment to be baseline (defaults to middle)

---

src/components/Chips/Chips.module.scss

https://monday.monday.com/boards/3532714909/pulses/4818138972
as it is using box-sizing of border-box, limiting the height to 22px causes the chip to be with total height of 22px instead of like regular chip which is 24px.
Before:
After:
---
Bug fix:
It caused this bug:
✅ Before, without border - correct (24px)
❌ Before, with border - wrong (22px)
✅ After, with border - correct (24px)

fix(Chips): change border color token, do not limit chip-with-border's height

---

src/tests/test-ids-utils.ts

https://monday.monday.com/boards/3532714909/pulses/4899875511
it should only not-chain if it's `null` or `undefined`, but currently, it does not chain also if it is `0` or `false`

chore(data-testid): util function does not chain id if it is falsy

---

package.json

attempt to solve this: https://github.com/mondaycom/monday-ui-react-core/issues/1423

chore: expose types for vite and next-based projects

---

src/components/TextField/TextField.tsx
src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap

Issue fix
Current: there's an unneeded and hardcoded text in the Textfield's error message aria-label.
This fix removed the aria-label from this span.

fix: removing unneeded aria-label from TextField's error message

---

src/components/Dropdown/components/menu/menu.jsx

https://monday.monday.com/boards/3532714909/pulses/5029231156
menuRenderer wasn't receiving children, so it wasn't able to render options properly, e.g. when menuRenderer looks like this
```
import React, { Fragment } from "react";
import { components } from "react-select";
import "./dropdown.stories.scss";
export const MenuRenderer = props => {
return (
<Fragment>
<components.Menu {...props} />
</Fragment>
);
};
```

fix: <Dropdown> pass children to the menuRenderer

---

src/components/Dropdown/components/menu/menu.jsx
src/components/Dropdown/components/menu/menu.module.scss

https://monday.monday.com/boards/3532714909/pulses/5135298038
When using `menuPortalTarget` the Dropdown menu while animating is locating above the select, which is causing issues (tapping Dialog issue). Tried to play with z-index to fix it, but didn't succeed. Feel like I've wasted too much time on it already, so this is a temp fix, which just disables animation when using  `menuPortalTarget`. If we don't like this temp solution, help would be appreciated here - can provide all the data which is needed to reproduce the issue
Video - on the left Dropdown with `menuPortalTarget`, on the right without. Opacity disabled and duration increased for the demo
https://github.com/mondaycom/monday-ui-react-core/assets/104433616/0185cdb6-ed24-41d8-bce8-97d314e75216

<DropdownMenu> - disable animation when using menuPortalTarget - temp fix

---

src/components/MenuButton/MenuButton.tsx

The boolean type has been changed to string in `disabledReason?` of the `<MenuButton>` component, described in the problem: #1567

fix: <MenuButton> disabledReason?: boolean change type to string

---

src/components/Combobox/__stories__/combobox.stories.mdx

Add spaces between links and text in the Tip section of Combobox
https://style.monday.com/?path=/docs/inputs-combo-box--overview
Closes issue #1578

docs: Add space between <Combobox> tips and links

---

src/hooks/useClickOutside/__stories__/useClickOutside.stories.mdx
src/hooks/useClickableProps/__stories__/useClickableProps.stories.mdx
src/hooks/useEventListener/__stories__/useEventListener.stories.mdx
src/hooks/useGridKeyboardNavigation/__stories__/useGridKeyboardNavigation.stories.mdx
src/hooks/useHover/__stories__/useHover.stories.mdx
src/hooks/useIsOverflowing/__stories__/useIsOverflowing.stories.mdx
src/hooks/useKeyEvent/__stories__/useKeyEvent.stories.mdx
src/hooks/useListenFocusTriggers/__stories__/useListenFocusTriggers.stories.mdx
src/hooks/useSetFocus/__stories__/useSetFocus.stories.mdx

Replace react docs legacy links with the new ones (https://github.com/mondaycom/monday-ui-react-core/issues/1589)

docs: replace legacy links with the new ones

---

.npmrc
package-lock.json
package.json

https://monday.monday.com/boards/3532714909/pulses/5265659631
To prevent issues in dependency resolution when using different package managers
When using `yarn install` for example it will throw an error:

chore: enforce using npm

---

README.md

This adds some useful information about the current version and a link to npm when clicked.
We can add more badges if we want (license, build, tests, coverage etc)
https://monday.monday.com/boards/3532714909/pulses/5265254654

docs: add npm version badge

---

src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.module.scss
src/components/BreadcrumbsBar/BreadcrumbItem/BreadcrumbContent/BreadcrumbContent.tsx
src/components/BreadcrumbsBar/BreadcrumbItem/__tests__/__snapshots__/breadcrumbItem-snapshot-tests.jest.js.snap
src/components/BreadcrumbsBar/__tests__/__snapshots__/breadcrumbsBar-snapshot-tests.jest.js.snap

fix: <BreadcrumbsBar> - shouldn't be clickable when type = Indication

---

src/components/ProgressBars/LinearProgressBar/LinearProgressBar.tsx
src/components/ProgressBars/LinearProgressBar/LinearProgressBarHelpers.ts

Fixes #1661
- Added a type export to the LinearProgressBarHelper.ts file to export the typeof Keys of SIZE
- Updated the type inside the LinearProgressBar Component itself by using the newly exported type size.

Bug Fix: Fixes #1661 Fixed the TS error while using size prop for <ProgressBar />

---

package.json

https://monday.monday.com/boards/3532714909/pulses/5266928257
Tested it on
- monday-ui-components https://github.com/DaPulse/monday-npm-packages/pull/4173
- vite & TS test project
- react & ts test project
- Monolith - all good but fails on borg (i think cause of the prerelease version)- https://github.com/DaPulse/dapulse/pull/64168
- One of the MFs - mf-avaliablility-calendar 
Resolves https://github.com/mondaycom/monday-ui-react-core/issues/1598

feat: fix for Vite

---

src/components/Dropdown/Dropdown.jsx
src/components/Dropdown/components/MultiValueContainer/MultiValueContainer.jsx

https://monday.monday.com/boards/3532714909/pulses/5400142555
Mixed mode of controlled-uncontrolled Dialog open state caused it to unexpectedly open from time to time and not closing on Counter click
Reproducible on other examples also, but more convenient to see on same demo story example
Base branch - https://github.com/mondaycom/monday-ui-react-core/pull/1708

fix: <Dropdown> multi - single line, fix mixed controlled-uncontrolled <Dialog> state management - move to uncontrolled

---

src/components/AlertBanner/__stories__/alertBanner.stories.js
src/components/AlertBanner/__stories__/alertBanner.stories.mdx

The issue was that the condition in `AlertBanner.tsx:109` where the condition identified the children as MDX element and not AlertBanner Text, the ellipsis actually works well, there's even a story for that.
https://monday.monday.com/boards/3532714909/pulses/5382950355

docs: extract AlertBanner template to stories file

---

src/components/Table/TableRow/TableRow.tsx

We had an issue here: https://style.monday.com/?path=/docs/data-display-table--virtualized-scroll
scrolling happened but rows were glitchy and didn't render some
can reproduce in this Storybook preview: https://62037c72e0e4d6004a9a450f-oyicztqxje.chromatic.com/?path=/docs/data-display-table--virtualized-scroll

chore: <Table/> - fix virtualization scroll issue

---

src/components/Combobox/__tests__/__snapshots__/combobox-snapshot-tests.jest.js.snap
src/components/Search/__tests__/__snapshots__/search-snapshot-tests.jest.js.snap
src/components/TextField/TextField.module.scss
src/components/TextField/TextField.tsx
src/components/TextField/__stories__/TextField.stories.mdx

https://monday.monday.com/boards/3532714909/pulses/5466372603
Issue:
https://github.com/mondaycom/monday-ui-react-core/assets/25477901/e729fd60-ea96-4077-b99b-a004e793ade1
- Removed any hover/active interaction on `TextField` icon when `onIconClick` is not supplied
- Modfied the `:active` interaction style on `TextField onIconClick` to be unified with other button interaction (scale)

fix: Modified the styling of the <TextField> icon 

---

src/components/TextField/TextField.module.scss

https://monday.monday.com/boards/3532714909/pulses/5467362370

fix: <TextField> add typograpghy mixin to the textField container to prevent avoid line-height overrides

---

src/components/Dropdown/Dropdown.styles.js

https://monday.monday.com/boards/3532714909/pulses/5536525264
Applying keyboard focus style (background-color) to disabled options as well
Following this request from ask-vibe - https://monday.slack.com/archives/C02S6F817JQ/p1700392102790859

fix: <Dropdown> disabled option - fix keyboard focused style

---

src/components/Heading/Heading.tsx
src/components/Heading/__stories__/Heading.stories.mdx
src/components/Text/Text.tsx
src/components/Text/__stories__/Text.stories.mdx
src/components/Typography/Typography.tsx
src/components/Typography/TypographyHooks.tsx
src/components/Typography/utils/TypographyContext.ts
src/hooks/useIsOverflowing/useIsOverflowing.ts

Since we set a line-height which is smaller than the font's normal line-height in the `Heading` component, whenever we check for vertical overflow - it returns true even if it doesn't seem to be overflowing. There's a 2-3px gap.
To avoid it, and instead of setting `line-height: normal` on `Heading`, we:
1. Ignore vertical overflow when it's unneeded, when `maxLines` is 1 (default).
2. Set a tolerance value to "close the gap" as described above. 4px is enough for this case. 
Also we no longer need to pass `ignoreHeightOverflow` prop to the context, I use it for the tolerance now instead.
This is kinda 🤮 but that's the best we can do.
https://monday.monday.com/boards/3532714909/pulses/5413034707

fix: typography vertical overflow tolerance

---

src/components/Tooltip/Tooltip.tsx

- `zIndex` added to Tooltip to expose this property from Dialog component
- functionally nothing changes, but usage of that parameter from typescript code no longer require ignoring type checking
https://monday.monday.com/boards/3938308886/pulses/5599287179

style(Tooltip): Explicitly expose zIndex prop in component

---

src/components/Dialog/Dialog.tsx
src/components/SplitButton/SplitButton.module.scss

The SplitButton is constructed of two elements: Button, and a Button that is wrapped as a Dialog, which actually make the component wrapper have two elements: Button, and a div (dialog+button). The Button has a line height but the div doesn't. The div inherits line-height (different than 1/normal) which makes the entire components break alignment.
The solution would be to remove `align-items: center` to align it normally without letting external line height to affect. In any way, no need to align it to the center anyway.
https://monday.monday.com/boards/3532714909/pulses/5718731997

Split button alignment fix

---

src/components/ProgressBars/LinearProgressBar/Bar/Bar.module.scss
src/components/ProgressBars/LinearProgressBar/LinearProgressBarConstants.ts

Added warning color + secondary to `LinearProgressBar`

feat: add warning color LinearProgressBar

---

.storybook/preview.tsx
src/next.ts
src/storybook/stand-alone-documentaion/playground/Playground.stories.ts

I made some change in the `next` entry that could be risky, so please verify it

chore(playground-addon): support next components and add an initial code example

---

src/components/Steps/Steps.tsx
src/components/Steps/StepsCommand.module.scss
src/components/Steps/StepsCommand.tsx
src/components/Steps/StepsConstants.ts
src/components/Steps/StepsHeader.module.scss
src/components/Steps/StepsHeader.tsx
src/components/Steps/__stories__/steps.stories.helpers.js
src/components/Steps/__stories__/steps.stories.js
src/components/Steps/__tests__/__snapshots__/steps-snapshot-tests.jest.js.snap
src/components/Steps/__tests__/steps-tests.jest.js
src/components/Tipseen/TipseenWizard.tsx
src/components/Tipseen/__stories__/tipseen.mdx
src/components/Tipseen/__stories__/tipseen.stories.js

- The button appears only for the last step, if `onFinish` prop is provided
- It's opt-in because adding it as default is breaking because the component is controlled, so adding a button that doesn't do anything is bad for UX
- Added TODO to make it the default in next major
https://monday.monday.com/boards/3532714909/pulses/5636406872

feat: add a Finish button to Steps

---

src/storybook/components/related-components/descriptions/tipseen-description.jsx

https://monday.monday.com/boards/3532714909/pulses/5762803720
We have a bug that `backButtonProps` and `nextButtonProps` override the other buttons props, opened a backlog task, but anyway it's not needed because `onChangeActiveStep` can control the state alone

docs: remove unneeded callbacks

---

src/components/Menu/MenuItemButton/MenuItemButton.tsx

the current kind type caused `MenuItemButton.kinds` to be undefined at some cases
https://monday.monday.com/boards/3532714909/pulses/5805039555

fix(MenuItemButton): fix type for kind

---

src/components/Table/TableVirtualizedBody/TableVirtualizedBody.module.scss
src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx

The Virtualized list doesn't take the Header into consideration in the height calculation so I've added it. Not sure it's the best solution, would love to hear thoughts.
https://monday.monday.com/boards/3532714909/pulses/5840033094
Before:
After:

fix(TableVirtualizedBody): take height of header into consideration

---

src/components/TextField/TextFieldConstants.ts
src/components/TextField/__tests__/TextField.jest.js
src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
src/components/TextField/__tests__/textField-snapshot-tests.jest.js

feat: add email TextFieldTextType

---

src/components/TextField/TextFieldConstants.ts
src/components/TextField/__tests__/TextField.jest.js
src/components/TextField/__tests__/__snapshots__/textField-snapshot-tests.jest.js.snap
src/components/TextField/__tests__/textField-snapshot-tests.jest.js

feat: add tel TextFieldTextType

---

src/components/Menu/MenuItem/hooks/useMenuItemMouseEvents.ts

https://monday.monday.com/boards/2520706822/pulses/5699284655
split menu item doesn't open consistently when hovering between menu items.
isActive is not turning to true even though the mouse is over the correct menu item.
isActive ---> index === activeIndex ---> true
looks like there is missing a render cycle for the menu item in order to update the isActive value so that hover on the split menu item will result in opening the sub menu.
before:
after:

fix(MenuItem): split menu items does not open sub-menu when navigating directly between two split menus

---

src/components/Menu/Menu/Menu.module.scss
src/components/Menu/Menu/__tests__/__snapshots__/menu.jest.js.snap
src/components/Menu/Menu/__tests__/menu-interactions.js
src/components/Menu/MenuItem/MenuItem.module.scss
src/components/Menu/MenuItem/MenuItem.tsx
src/components/Menu/MenuItem/__tests__/MenuItem.jest.js
src/components/Menu/MenuItem/__tests__/__snapshots__/menuItem-snapshots.jest.js.snap
src/components/SplitButton/SplitButtonMenu/__tests__/__snapshots__/splitButtonMenu-snapshot-tests.jest.tsx.snap
src/tests/interactions-utils.ts

this is a temp hack until the next major, it adds a hidden title element, not visible to screen readers and keyboard navigation, but it catches hover for tooltip width
https://monday.monday.com/boards/3532714909/pulses/5910955456

fix(MenuItem): tooltip should on all item and not only on title

---

src/components/Menu/MenuItem/MenuItem.tsx

https://monday.monday.com/boards/3532714909/pulses/6027956948

feat(MenuItem): be able to provide a component to title

---

packages/core/rollup.config.js

I use semantic fix here, and not semantic ci, to bump a patch since you cannot republish an unpublished version or overwrite a published version

fix: fix rollup build

---

.github/workflows/prerelease.yml
.github/workflows/release.yml

Lerna updates dependencies as semver compatible (with a ^) which automatically add the caret, the `--exact` flags make it use a fixed version. See [this](https://github.com/lerna/lerna/tree/main/libs/commands/version#--exact). See [this revision](https://github.com/mondaycom/monday-ui-react-core/pull/1953/files#diff-0b810c38f3c138a3d5e44854edefd5eb966617ca84e62f06511f60acc40546c7) for example:

ci: use lerna version exact

---

.github/workflows/publish-storybook.yml

We need to always build it as it's a dependency of storybook as well, no need to build core though

ci: always build before building storybook

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
packages/core/CONTRIBUTING.md

There are some broken markdown links in the codebase. This PR fixes them so that users aren't redirected to 404 pages.

docs: fix internal markdown file links

---

.github/actions/check-changed-packages/action.yml
.github/actions/determine-lerna-since-flag/action.yml
.github/workflows/chromatic.yml

https://monday.monday.com/boards/3532714909/pulses/6231010883
This PR also adds:
- reusable action that outputs the `since` flag value according to context of branch running the action
- reusable action that outputs whether there are changes to the monorepo's packages

ci(chromatic): allow to run on both master and other branches

---

.github/actions/setup/action.yml
.github/workflows/build-and-upload.yml

https://monday.monday.com/boards/3532714909/pulses/6244728962
https://monday.monday.com/boards/3532714909/pulses/6244733896

ci: use wildcard in `build-and-upload` to support future additional packages, add cache to `setup` for yarn dependencies

---

packages/core/src/components/Modal/ModalFooter/ModalFooterButtons/ModalFooterButtons.tsx
packages/core/src/components/Modal/ModalFooter/ModalFooterButtons/__tests__/__snapshots__/modalFooterButtons-snapshot-tests.jest.tsx.snap
packages/core/src/components/Modal/ModalFooter/ModalFooterButtons/__tests__/modalFooterButtons-snapshot-tests.jest.tsx
packages/core/src/components/Modal/ModalFooter/ModalFooterButtons/__tests__/modalFooterButtons-tests.jest.tsx

feat(ModalFooterButtons): support disable buttons and remove secondary

---

packages/core/src/components/Modal/ModalHeader/ModalHeader.tsx
packages/core/src/components/Tabs/Tab/Tab.tsx

feat: changed proptype from `string`/`IconSubComponentProps` to `SubIcon`

---

packages/core/src/components/MenuButton/MenuButton.tsx

https://monday.monday.com/boards/3532714909/pulses/6285146715

fix(MenuButton): call `onMenuHide` on all cases where menu is closed

---

packages/core/src/components/Label/Label.module.scss
packages/core/src/components/Label/Label.tsx
packages/core/src/components/Label/LabelCelebrationAnimation.module.scss
packages/core/src/components/Label/LabelCelebrationAnimation.tsx
packages/core/src/components/Label/__stories__/label.mdx
packages/core/src/components/Label/__stories__/label.stories.tsx

https://github.com/mondaycom/monday-ui-react-core/assets/18269880/4271b6f6-a341-42cc-b6b3-8eb3d55149be
https://monday.monday.com/boards/3532714909/pulses/6162325457

feat(Label): celebration animation

---

packages/core/src/components/Tabs/Tab/Tab.tsx
packages/core/src/components/Tabs/Tab/__tests__/__snapshots__/tab-snapshot-tests.jest.js.snap

https://monday.monday.com/boards/3532714909/pulses/6391046217
Was requested in support channel, doesn't seem like it makes sense not to accept a single `ReactElement` here

chore(Tab): allow accepting children of a single ReactElement

---

packages/core/src/components/DatePicker/YearPicker/YearPicker.module.scss
packages/core/src/components/DatePicker/YearPicker/YearsList.tsx

This bug happened since some of the years' widths are shorter than others (mostly years that start with 1), so the fix is to set a min width to the years' button
https://monday.monday.com/boards/3532714909/pulses/6234283969

fix(DatePicker): added min width to buttons inside year picker

---

packages/core/.storybook/manager.jsx
packages/core/.storybook/preview.tsx
packages/core/package.json
packages/core/src/storybook/stand-alone-documentaion/catalog/catalog.stories.tsx

https://monday.monday.com/boards/3532714909/pulses/6437258196

docs: allow having Internal section with stories only visible for dev mode

---

packages/core/src/components/Dropdown/__stories__/dropdown.mdx
packages/core/src/components/Dropdown/__stories__/dropdown.stories.helpers.tsx
packages/core/src/components/Dropdown/__stories__/dropdown.stories.js

https://monday.monday.com/boards/3532714909/pulses/4977987525

docs(Dropdown): async options story

---

packages/core/src/components/EditableText/__stories__/EditableText.stories.js
packages/core/src/components/Text/TextConstants.ts
packages/core/src/components/Text/__stories__/Text.mdx
packages/core/src/components/Text/__stories__/Text.stories.js
packages/core/src/components/Text/__stories__/Text.stories.module.scss
packages/core/src/storybook/stand-alone-documentaion/typography/typography-migration-guide.mdx
packages/core/src/storybook/stand-alone-documentaion/typography/typography.mdx
packages/core/src/styles/typography.scss
packages/style/src/config/maps/core/_core-typography-map.scss
packages/style/src/config/tokens/core/_core-typography.scss

https://monday.monday.com/boards/3532714909/pulses/6418938469

feat(Text): Add new 12px font size (Text3)

---

packages/core/src/components/Dialog/Dialog.tsx

- added exposing event handling for onDialogDidShow

feat(Dialog): add event args to dialog show methods

---

packages/core/src/components/Search/Search.tsx
packages/core/src/components/Search/Search.types.ts
packages/core/src/components/Search/__tests__/Search.jest.tsx

We have a use case for being able to hide the renderAction component passed in to the Search component once a search term is entered, which is not easily achieved by logic outside of the component (see below, clear icon showing at same time as renderAction).
Adding a `hideRenderActionOnInput` option, that defaults to false, which can be enabled so that the RenderAction is not displayed once a search term is entered.
Current behaviour when handling hiding renderAction outside of search component:

feat(Search): adds hideRenderActionOnInput option

---

packages/core/src/components/DatePicker/DatePicker.tsx

add a null check to avoid a console error when using the DatePicker component without passing the onPickDate prop, to solve this issue:
https://github.com/mondaycom/vibe/issues/2045

fix: add null protection for onPickDate callback (#2045)

---

packages/core/src/components/Menu/MenuItem/MenuItem.module.scss
packages/core/src/components/Menu/MenuItem/MenuItem.tsx
packages/core/src/components/Menu/MenuItem/__stories__/MenuItem.mdx
packages/core/src/components/Menu/MenuItem/__stories__/MenuItem.stories.tsx
packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/MenuItemSubMenuIcon.module.scss
packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/MenuItemSubMenuIcon.tsx
packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/MenuItemSubMenuIcon.types.ts
packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenuIcon/__tests__/MenuItemSubMenuIcon.jest.tsx

https://monday.monday.com/boards/3532715121/pulses/6566973814

refactor(MenuItem): separate SubMenuIcon logic from MenuItem

---

packages/core/src/components/Dialog/Dialog.tsx

When document.querySelector(containerSelector) returned a `node` that was not a `Element` the react-dom createPortal threw a [react error 200](https://react.dev/errors/200?invariant=200).
Here we fix the issue by validating the returned `contanerElement` as an Element.
- [x ] I have read the [Contribution Guide](../packages/core/CONTRIBUTING.md) for this project.

fix(Dialog.tsx): getContainer causing react error 200

---

packages/core/src/components/SplitButton/SplitButton.tsx
packages/core/src/components/SplitButton/__stories__/splitButton.stories.js

https://monday.monday.com/boards/3532714909/views/113186840/pulses/6495343163

fix(SplitButton storybook): - fix stories that use wrong prop

---

packages/core/rollup.config.js
packages/core/webpack.config.js

https://monday.monday.com/boards/3532714909/pulses/6494836185
Bundle size (unpackaged) reduced from 205MB to ~40MB. Without webpack build it's less than 2MB

build: remove sourcemaps

---

packages/core/rollup.config.js

As the rollup build doesn't affect the unpackaged size - bringing it back
https://monday.monday.com/boards/3532714909/pulses/6494836185

build: add sourcemaps to esm

---

packages/core/src/hooks/useClickOutside/__stories__/useClickOutside.mdx
packages/core/src/hooks/useClickOutside/index.ts

Support excluding classes when checking if a click occurred outside for useClickOutside hook.

feat: Ignore classes in useClickOutside hook

---

packages/core/src/components/Checkbox/__stories__/checkbox.stories.tsx

https://monday.monday.com/boards/3532714909/views/113186840/pulses/6495358494

fix(Checkbox storybook): story is using Link from storybook-blocks

---

packages/core/src/constants/colors.json

See https://github.com/mondaycom/vibe/pull/2009
Missed this specific color in original PR ⏫ 
https://monday.monday.com/docs/5264487294

fix(colors): align dark orange to a11y requirments

---

packages/core/src/components/Table/Table/Table.tsx
packages/core/src/components/Table/Table/__tests__/Table.test.tsx
packages/core/src/components/Table/TableBody/TableBody.tsx
packages/core/src/components/Table/TableRow/TableRow.tsx
packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx
packages/core/src/components/Table/context/TableContext/TableContext.tsx
packages/core/src/components/Table/context/TableContext/TableContext.types.ts
packages/core/src/components/Table/index.ts

this is a temp workaround until the virtualized table component would get a big revamp. this workaround sets List width to be the full width and not the parent container's width
https://monday.monday.com/boards/3532714909/pulses/6513670146

fix(Table): sync between body scroll and header scroll in virtualized state

---

packages/core/src/components/Modal/Modal.tsx
packages/core/src/components/Modal/__stories__/Modal.stories.tsx
packages/core/src/components/Modal/useShowHideModal.ts

https://monday.monday.com/boards/3532714909/pulses/6718830547

feat(Modal): unmount when hidden

---

packages/core/package.json
packages/core/src/components/Dropdown/Dropdown.tsx
packages/core/src/components/Dropdown/__tests__/Dropdown.test.js
packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
yarn.lock

https://monday.monday.com/boards/3532714909/pulses/6864028773
We now have `react-windowed-select`, which, for some reason, does not use `react-select` as peer dep, but as a dep.
So this causes two versions of `react-select` at our bundle, as we cannot resolve both our dependency and `react-windowed-select`'s version to same version.
**This should be reviewed with caution**
The only breaking behavior on `react-select` 4 in compare to 3 is the `isMulti` behavior.
It used to return `null` when no options were selected. now it returns always array (empty array in case no options were selected).
So I had, to not cause breaking changes, mimic the current behavior with the new `react-select`'s api for `isMulti`'s `onChange`.

feat(react-select): use react-select version 4.3.1

---

packages/core/src/components/TextField/TextField.tsx
packages/core/src/components/TextField/__tests__/TextField.test.js

https://monday.monday.com/boards/3532714909/pulses/6887647837

feat(TextField): add a controlled variant

---

packages/storybook-blocks/package.json

fix: Revert "chore: add build step postinstall for vibe-storybook-components"

---

packages/core/package.json
yarn.lock

At the end, the publish is done through the GitHub Actions action of Chromatic, so we are, currently, using the latest - it is just to keep up to date also the local dep for running Chromatic locally
Found it out during Chromatic's outage when I've tried to run build through local and got a warning from Chromatic regarding this
https://monday.monday.com/boards/3532714909/pulses/6957006224

chore(chromatic): update chromatic cli to latest version

---

packages/style/src/Themes/black/_black-theme-content-colors.scss
packages/style/src/Themes/dark/_dark-theme-content-colors.scss

Due to a11y:
Content colors are now consistent between the themes expect for the specific colors that have changed:
Dark indigo - #6129FF
Navy - #5684C5
Blackish - #9A9A9A
Teal - #4A8F98
Pecan - #806363
https://monday.monday.com/boards/3532714909/pulses/6901932066

feat(colors): remove overrides of content colors in black and dark themes

---

packages/codemod/.eslintrc.json
packages/codemod/package.json
packages/codemod/tsconfig.json
packages/codemod/tsconfig.test.json
packages/codemod/vitest.config.ts

initiating a new package called "codemod"
at the end, this should publish a package to act as a CLI tool for migrating between Vibe's majors (currently for `core`).
package name should be `@vibe/codemod`
https://monday.monday.com/boards/3532714909/pulses/6798809703

chore: init 'codemod' - a new package to store Vibe's codemods

---

packages/core/src/components/Table/Table/Table.module.scss

https://monday.monday.com/boards/3532714909/pulses/6996492663

fix(Table): hover cell background var should be declared inside the table selector and not on :root

---

packages/core/src/components/Switch/Switch.tsx
packages/core/src/components/Toggle/Toggle.tsx
packages/core/src/components/Toggle/__tests__/Toggle.test.js
packages/core/src/hooks/useSwitch/__tests__/useSwitch.test.ts
packages/core/src/hooks/useSwitch/index.ts

https://monday.monday.com/boards/3532714909/pulses/7035594767
- **useSwitch**: pass `event` as 2nd argument for `onChange`
- **Toggle**: pass `event` as 2nd argument for `onChange`
- **Switch**: pass `event` as 2nd argument for `onChange`

feat(Toggle): pass event as 2nd argument to allow working with react-hook-form

---

packages/core/package.json
yarn.lock

https://monday.monday.com/boards/3532714909/pulses/7086495216
@rivka-ungar @talkor

fix(Dropdown): nanoid 4+ supports only ESM, we should still support CJS

---

packages/core/src/components/Search/Search.tsx
packages/core/src/components/Search/Search.types.ts

Hi everyone!
Attending the idea discussion [#2101](https://github.com/mondaycom/vibe/discussions/2101), I've added the `onClear` prop to the `Search` component. It's a simple change, but at the same time, a useful one.
I decided to just add a verification inside of the function that clears the search input value once the users clicks the clear button, keeping the existing logic untouched and adding another step before clearing the input value.
I hope this change make sense to you guys!
Thanks in advance!

feat: add onClear prop to Search component

---

packages/core/src/components/Table/Table/__stories__/Table.stories.helpers.tsx
packages/core/src/components/Table/Table/__stories__/Table.stories.tsx
packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx

TableVirtualizedBody doesn't support generic types. Which means that if you have typescript configured in the project with `"strict": true`, you will get an error like this:
- Added support for generic types in `TableVirtualizedBody` component, to make it more type-safe
- Converted `Table.stories.js` file to `.tsx` + necessary types updates (without logic changes)
At the moment vibe repository is NOT strictly typed (`"strict": true` in `tsconfig.json`). Therefore, TableVirtualizedBody component works fine in storybook even without my changes. Which makes almost impossible to catch that kind of bug during development.
To avoid similar bugs in future, make Vibe type-safe and basically make it possible to use Vibe safely in the projects which are strictly typed, I highly encourage you to …

fix: Add support for generic types in the TableVirtualizedBody component

---

packages/core/src/components/DatePicker/DatePicker.tsx
packages/core/src/components/DatePicker/DatePickerHeader/DatePickerHeader.tsx
packages/core/src/components/DatePicker/YearPicker/YearPicker.tsx
packages/core/src/components/DatePicker/__tests__/DatePicker.test.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/6958030426

fix(DatePicker): Keyboard Navigation

---

packages/core/src/components/EditableHeading/__stories__/EditableHeading.stories.module.scss
packages/core/src/components/EditableHeading/__stories__/EditableHeading.stories.tsx
packages/core/src/components/Heading/HeadingConstants.ts
packages/core/src/components/Heading/__stories__/Heading.mdx
packages/core/src/components/Heading/__stories__/Heading.stories.tsx
packages/core/src/storybook/stand-alone-documentaion/typography/typography.mdx
packages/core/src/styles/typography.scss
packages/style/src/config/maps/core/_core-typography-map.scss
packages/style/src/config/tokens/core/_core-typography.scss

https://monday.monday.com/boards/3532714909/pulses/6899636911

Add medium bold to header

---

packages/core/src/components/Tabs/__stories__/Tabs.stories.tsx
packages/core/src/components/TextField/TextField.tsx
packages/core/src/components/TextField/TextField.types.ts
packages/core/src/components/TextField/TextFieldConstants.ts
packages/core/src/components/TextField/__stories__/TextField.mdx
packages/core/src/components/TextField/__stories__/TextField.stories.tsx
packages/core/src/components/TextField/__tests__/TextField.snapshot.test.js
packages/core/src/components/TextField/__tests__/TextField.test.js
packages/core/src/components/TextField/index.ts
packages/core/src/storybook/components/related-components/descriptions/text-field-description.jsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/7021052006

chore(TextField): deprecate enums

---

packages/core/src/hooks/useSwitch/__tests__/useSwitch.test.ts
packages/core/src/hooks/useSwitch/index.ts

We introduced breaking changes by mistake in #2243.
We should type the `event` as `any` and only send it back in the callback if it is a real event.
https://monday.monday.com/boards/3532714909/pulses/7139886355
Created a task for next major to remove the typeguard:
https://monday.monday.com/boards/6841644723/pulses/7169775263

fix(useSwitch): type guard to fix breaking change we accidentally introduced in previous version

---

packages/core/docs/vibe-3-changelog.md
packages/core/src/components/AvatarGroup/AvatarGroup.module.scss
packages/core/src/components/AvatarGroup/AvatarGroup.tsx

https://monday.monday.com/boards/3532714909/pulses/7170736443

chore(AvatarGroup): remove removePadding prop and apply by default

---

packages/core/src/components/MenuButton/MenuButton.module.scss

https://monday.monday.com/boards/3532714909/pulses/7080313485

fix(menuButton): fix scale for disabled menu button

---

packages/core/src/components/AvatarGroup/AvatarGroupCounterTooltipHelper.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/7205735679

fix(AvatarGroup): avatar in tipseen without image is wrong size

---

packages/core/docs/vibe-3-changelog.md
packages/core/src/components/Modal/Modal.tsx
packages/core/src/components/Modal/__tests__/Modal.test.js

https://monday.monday.com/boards/3532714909/pulses/6887875560

chore(Modal): revert removal of unmountOnClose prop

---

.github/workflows/prerelease.yml
packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.helpers.tsx
packages/core/src/components/Menu/Menu/__stories__/Menu.stories.helpers.tsx

https://monday.monday.com/boards/3532714909/pulses/7086730463
https://monday.monday.com/boards/3532714909/pulses/7086725168
It looks much cleaner IMO, and the purpose of such version is clearer (alpha versions). Plus it's based on the commit sha so it'll be unique and can be published multiple times per PR

ci(prerelease): use commit sha for prerelease version naming

---

packages/codemod/transformations/core/v2-to-v3/__tests__/use-clickable-props-hook-migration.test.ts
packages/codemod/transformations/core/v2-to-v3/use-clickable-props-hook-migration.ts
packages/core/docs/vibe-3-changelog.md

https://monday.monday.com/boards/3532714909/views/80492480/pulses/7338211944

chore(useClickableProps): Codemod for changing dataTestId to data-testid

---

packages/core/src/components/Button/Button.tsx
packages/core/src/components/IconButton/IconButton.tsx

feat: add aria-pressed prop to IconButton

---

packages/core/src/components/TextArea/TextArea.tsx

I work with `Formik` library to build a form consisting of several components from Vibe including `TextArea`. Some crucial attributes are not passed on to the native `textarea` element such as `onBlur`, `name` and `maxLength`. This PR fixes it.

fix: pass on attributes such as name, onBlur and maxLength to textarea element

---

packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.module.scss
packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.tsx
packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.types.ts
packages/core/src/components/ModalNew/ModalTopActions/__tests__/ModalTopActions.test.tsx

Which shows next to the Header, at the top of the modal
- When X button is triggered, call the `onClose` that was assigned by consumer to the `onClose` of the `Modal`.
- Renders the extra header action received initially by `Modal`.
- Positioned absolute, not actual part of the Header.
Props:
Name | Type | Description
-- | -- | --
renderAction | (color?: ModalTopActionsColor) => React.ReactElement<typeof MenuButton \| typeof IconButton> | 
color | ModalTopActionsColor 🔒(which is "light" \| "dark") | 
closeButtonAriaLabel | string | 
onClose | React.MouseEventHandler<HTMLDivElement> | 
Usage example:
```typescript
<ModalTopActions
onClose={() => console.log("Hi!")}
closeButtonAriaLabel="Close"
renderAction={() => (
<MenuButton size={MenuButton.sizes.SMALL} ariaLabel="Options">
<Menu …
```

feat(ModalTopActions): top actions component for internal use

---

packages/core/src/components/ModalNew/Modal/Modal.tsx
packages/core/src/components/ModalNew/Modal/Modal.types.tsx
packages/core/src/components/ModalNew/Modal/__tests__/Modal.test.tsx
packages/core/src/components/ModalNew/context/ModalContext.tsx
packages/core/src/components/ModalNew/context/ModalContext.types.ts

- Set `aria-labelledby` for the Modal's title element id
- Set `aria-describedby` for the Modal's description element id
The reason for it to be a setter, rather than passing a plain value to the Context and then use it (without states), is because we cannot tell if a description would be provided to the Modal by consumer.
So in ModalHeader we should call the setters according to the ids supplied there.
See https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/#rps_label for further best practices regarding `Modal`'s arias
Next steps:
- Consume the context inside `ModalHeader`
- Set the id for the title and description elements inside `ModalHeader`, using the `Modal`'s `id` prop (to have unique ids):
- `[my-modal-id]_label`
- `[my-modal-id]_desc` …

feat(Modal): use titleId and descriptionId for appropriate arias, allow setting those values through context

---

packages/core/package.json
packages/core/src/components/ModalNew/Modal/Modal.tsx
packages/core/src/tests/constants.ts
yarn.lock

Decided to go with `react-remove-scroll` which seem to be the most popular and bulletproof solution, the bundle cost is also very very light
https://monday.monday.com/boards/3532715121/pulses/7391259531

feat(Modal): disable scroll outside of modal when it is open

---

packages/core/src/components/TextArea/TextArea.tsx
packages/core/src/components/TextArea/TextArea.types.ts

**Main Changes:**
1. Spread `rest` props object to the native `textarea` tag in order to support native HTML API.
**Impact:**
1. A more robust component
**Related:** 
- https://monday.monday.com/boards/5896576795/pulses/7480825140
- https://monday.slack.com/archives/C02S6F817JQ/p1726471392017299

fix(TextArea): Spread rest props to the native textarea tag

---

packages/core/package.json
packages/core/src/components/ModalNew/Modal/Modal.tsx
packages/core/src/components/ModalNew/Modal/__tests__/Modal.test.tsx
yarn.lock

- Focus should be locked inside Modal and to not let "Tab" click to focus stuff outside of the Modal
https://monday.monday.com/boards/3532714909/pulses/7360933300
- Focus should return to last element that was opened before modal opened
https://monday.monday.com/boards/3532715121/pulses/7391253003

feat(Modal): keep focus inside opened modal, return focus to last element

---

packages/core/src/components/Dropdown/Dropdown.tsx
packages/core/src/components/Dropdown/Dropdown.types.ts
packages/core/src/components/Dropdown/DropdownConstants.ts

Adding the ability to provide an `ariaLabel` specifically for the input of the `Dropdown` component. This is fully backwards compatible, providing the aria label `"Dropdown input"` that it used to by default, but if you provide the `inputAriaLabel` prop then it will use that instead.

feat: add inputAriaLabel to Dropdown component

---

packages/icons/.gitignore
packages/icons/package.json
packages/icons/rollup.config.js
packages/icons/scripts/generate-lazy-icons.js

https://monday.monday.com/boards/3532714909/views/80492480/pulses/7338833464
Regular Icons:
Lazy icons:

feat: Add lazy load variation for each icon

---

packages/core/src/components/List/utils/ListUtils.ts
packages/core/src/components/Menu/Menu/hooks/useMenuId.tsx
packages/core/src/components/Menu/Menu/hooks/useMouseLeave.tsx
packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/MenuItemSubMenu.tsx
packages/core/src/components/Menu/MenuItem/hooks/useMenuItemMouseEvents.ts
packages/core/src/components/MenuButton/MenuButton.tsx
packages/core/src/components/Modal/Modal.tsx
packages/core/src/components/TextWithHighlight/TextWithHighlight.tsx
packages/core/src/components/ThemeProvider/ThemeProvider.tsx
packages/core/src/hooks/useClickOutside/index.ts
packages/core/src/hooks/useKeyEvent/index.ts
packages/core/src/hooks/useMediaQuery/index.ts
packages/core/src/hooks/usePopover.ts
packages/core/src/hooks/usePrevious/index.ts
packages/core/src/hooks/useVibeMediaQuery/index.ts

https://monday.monday.com/boards/4400799549/pulses/6799260682

Fix ssr issues

---

packages/codemod/package.json
packages/core/package.json
packages/storybook-blocks/package.json
packages/style/package.json

fix order for some of the fields to keep consistency (let's consider to later use linter specifically for the package json, for new packages as well)
this PR adds the "directory" subattr for each of the "repository" attribute in each of the package.json of the monorepo packages

chore: update repository directory in package json

---

packages/core/src/components/Dropdown/__tests__/__snapshots__/Dropdown.snapshot.test.js.snap
packages/core/src/components/Icon/CustomSvgIcon/CustomSvgIcon.tsx
packages/core/src/components/Icon/Icon.tsx
packages/core/src/components/Modal/__tests__/__snapshots__/Modal.snapshot.test.js.snap
packages/core/src/components/Tipseen/__tests__/__snapshots__/Tipseen.test.tsx.snap
packages/core/src/components/Typography/TypographyHooks.tsx
packages/core/src/hooks/ssr/useIsMounted.ts
packages/core/src/utils/ssr-utils.ts

https://monday.monday.com/boards/4400799549/pulses/7510834798

Add placeholder for custom svg icon for SSR [prerelease]

---

packages/core/src/storybook/components/related-components/descriptions/divider.jsx

I have removed the deprecated color names

docs(Divider): fixed `divider.jsx` and removed the deprecated color names

---

packages/core/src/components/Combobox/__tests__/Combobox.test.js
packages/core/src/components/Combobox/components/ComboboxOption/ComboboxOption.tsx

[https://github.com/mondaycom/vibe/issues/2481]: Restricted the onclick of the combobox in case of disabled options

fix: restricted onclick on the disabled

---

packages/core/src/storybook/components/related-components/descriptions/dropdown-description.jsx

Docs #2482
Add options to the dropdown in the catalog. 
Also, below is the screenshot of the change that has been made.

docs: add dropdown options in the catalog

---

packages/core/src/storybook/components/related-components/descriptions/box-description.jsx

The aim of this pull request is to make the sample Box in the BoxDescription component use a Text component for its content instead of an inline string.
The changes are implemented by replicating the suggestion in the related issue.
Fixes #2506

docs(Box): related Box should use Text instead of inline string

---

packages/core/src/components/VirtualizedGrid/__stories__/VirtualizedGrid.mdx
packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.mdx
packages/core/src/storybook/components/related-components/component-description-map.tsx
packages/core/src/storybook/components/related-components/descriptions/menu-grid-item-description.tsx

I've added missing sections to VirtualizedGrid and VirtualizedList stories.
I had to create `MenuGridItemDescription` as it was only one missing. I've took the description from `MenuGridItem` story.

docs: add missing related components section for VirtualizedGrid and VirtualizedList stories

---

packages/core/src/hooks/useDebounceEvent/__stories__/useDebounceEvent.stories.tsx

fixes: #2475 
First of all imported the Debounce type definitions and added it accordingly. Added a onClick function because its mandatory in the type definition. 
Run the test and passed all tests.

Convert use debounce event to ts

---

packages/core/src/storybook/components/related-components/descriptions/clickable-description/clickable-description.jsx

We do not currently use Vibe's `Text` component, but instead use inline string.
This PR fix this, `Text` component is now properly used.
Resolves #2507

docs(Clickable): related component should use Text instead of inline string

---

packages/core/src/storybook/components/related-components/descriptions/dialog-content-container.jsx

**What changes are you making?**
This PR replaces the inline string in the DialogContentContainer located in `packages/core/src/storybook/components/related-components/descriptions/dialog-content-container.jsx `with Vibe's Text component.
**Motivation for these changes:**
Currently, the DialogContentContainer uses inline strings, which leads to theme inconsistencies, particularly in dark mode. By implementing the Text component, we can ensure proper styling and a consistent appearance across different themes.
**Impact on the project:**
This update resolves the styling issues related to dark themes and aligns with Vibe's design specifications, enhancing the user experience.
[Link to the issue](https://github.com/mondaycom/vibe/issues/2508#issue-2583857804)
I have read the [Contribution …

docs(DialogContentContainer): replace inline strings with Vibe's Text component

---

packages/core/src/storybook/stand-alone-documentaion/colors/Colors.mdx
packages/core/src/storybook/stand-alone-documentaion/colors/colors.stories.tsx

Resolves #2499
* Implemented `colors.stories.tsx` to follow [CSF 3.0](https://storybook.js.org/docs/api/csf)
* Changed `colors.stories.mdx` to `Colors.mdx`
* Updated `Meta` to use `of` attr instead of `title`

docs(Colors): migrate "Story of" to "Canvas of"

---

packages/core/src/components/ModalNew/Modal/Modal.module.scss
packages/core/src/components/ModalNew/Modal/Modal.tsx
packages/core/src/components/ModalNew/ModalContent/ModalContent.tsx
packages/core/src/components/ModalNew/ModalContent/__tests__/ModalContent.test.tsx
packages/core/src/components/ModalNew/ModalHeader/__tests__/ModalHeader.test.tsx
packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.module.scss
packages/core/src/components/ModalNew/context/ModalContext.tsx
packages/core/src/components/ModalNew/context/ModalContext.types.ts
packages/core/src/components/ModalNew/layouts/ModalBasicLayout/ModalBasicLayout.module.scss
packages/core/src/components/ModalNew/layouts/ModalBasicLayout/ModalBasicLayout.tsx
packages/core/src/components/ModalNew/layouts/ModalBasicLayout/ModalBasicLayout.types.ts
packages/core/src/tests/constants.ts

Usage example:
```typescript
<Modal size="small">
<ModalBasicLayout>
<ModalHeader title="I'm title" />
<ModalContent>I'm content</ModalContent>
</ModalBasicLayout>
<ModalFooter /> // TBD
</Modal>
```
https://monday.monday.com/boards/3532714909/pulses/7360987899

feat(ModalBasicLayout): basic layout component for new Modal

---

packages/core/src/components/Dropdown/Dropdown.styles.js

Resolves #2182
- Font family was not getting applied in dropdown, instead it was getting applied from story body CSS directly

fix: Dropdown font broken

---

packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.stories.helpers.tsx

Resolves #2514 
Converted the `packages/core/src/components/VirtualizedList/__stories__/VirtualizedList.stories.helpers.js` file to .tsx 
Please review and merge
Do let me know if any corrections are required
Thank you

convert VirtualizedList stories helpers file to TS

---

packages/core/src/components/VirtualizedList/VirtualizedList.tsx

This change is to add `aria-label` to the Virtualised list component for accessibility 
Resolves #
https://monday.monday.com/boards/5751390280/pulses/5751449186

feat: add aria-label to VirtualizedList

---

packages/core/src/components/Modal/__stories__/Modal.mdx
packages/core/src/components/Modal/__stories__/Modal.stories.tsx

Migrated `<Story of={}>` (Deprecated) to `<Canvas of={}>` for Modal's story.
Resolves #2500

docs(Modal): migrate "Story of" to "Canvas of" in "Sizes" story

---

packages/core/src/components/ModalNew/Modal/__tests__/Modal.test.tsx
packages/core/src/components/ModalNew/ModalContent/ModalContent.tsx
packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.module.scss
packages/core/src/components/ModalNew/ModalTopActions/ModalTopActions.tsx

- Always start autofocus cycle on content
- Skip top actions (close button + render action) from autofocusing on first focus cycle of modal
https://monday.monday.com/boards/3532714909/pulses/7360929204

feat(Modal): control autofocus and keyboard navigation focus

---

packages/core/src/components/AttentionBox/AttentionBox.module.scss
packages/core/src/components/AttentionBox/AttentionBox.tsx
packages/core/src/components/AttentionBox/__stories__/AttentionBox.mdx
packages/core/src/components/AttentionBox/__stories__/AttentionBox.stories.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/7719404878

feat(AttentionBox): add prop for enter animation

---

packages/core/src/components/ModalNew/Modal/Modal.module.scss
packages/core/src/components/ModalNew/Modal/Modal.tsx
packages/core/src/components/ModalNew/Modal/Modal.types.tsx
packages/core/src/components/ModalNew/Modal/__tests__/Modal.test.tsx
packages/core/src/components/ModalNew/utils/animationVariants.ts

https://monday.monday.com/boards/3532714909/pulses/7586333722
https://monday.monday.com/boards/3532714909/pulses/7586334945

feat(Modal): add pop from center/anchor animations

---

.github/workflows/test.yml
packages/testkit/__TESTS__/dropdown.spec.js

fix upload artifacts job and try fixing test

---

packages/core/src/components/TextArea/TextArea.module.scss
packages/core/src/components/TextArea/TextArea.tsx
packages/core/src/components/TextArea/TextArea.types.ts
packages/core/src/components/TextArea/__stories__/TextArea.stories.tsx
packages/core/src/components/TextArea/__tests__/TextArea.test.tsx

Towards https://monday.monday.com/boards/3709356818/pulses/7684207310
Design [Figma](https://www.figma.com/design/U27gdArnWEFYL7XA9ZId5D/Submission-view?node-id=3919-12955&node-type=section&t=4707WZFZeZnWo4Wj-0)
Currently there is no visual feedback for the user when there is a max length set on the TextArea component. A character count should be displayed when there is a maxLength set to convey this information.
There are two attributes that influence the behaviour, when `allowExceedingLimit` is set the user is able to type more than the maximum allowed characters, but will see the input in an error state (see 2nd screenshot). When a `maxLength` only is set the user is strictly able to type no more than the allowed length.

feat(TextArea): Character count and maxLength

---

packages/core/src/components/SlideTransition/SlideTransition.module.scss
packages/core/src/components/SlideTransition/SlideTransition.tsx
packages/core/src/components/SlideTransition/SlideTransition.types.ts
packages/core/src/components/SlideTransition/utils/animationVariants.ts
packages/core/src/components/TransitionView/TransitionView.tsx
packages/core/src/components/TransitionView/TransitionView.types.ts

https://monday.monday.com/boards/3532714909/pulses/7525075588

fix(TransitionView): handle parent without definite height

---

packages/core/src/components/LegacySearch/__tests__/__snapshots__/Search.snapshot.test.tsx.snap
packages/core/src/components/TextField/TextField.module.scss
packages/core/src/components/TextField/TextField.tsx
packages/core/src/components/TextField/__tests__/TextField.test.js
packages/core/src/components/TextField/__tests__/__snapshots__/TextField.snapshot.test.tsx.snap

Towards https://monday.monday.com/boards/3709356818/pulses/7684207310
Design [Figma](https://www.figma.com/design/U27gdArnWEFYL7XA9ZId5D/Submission-view?node-id=3919-12955&node-type=section&t=4707WZFZeZnWo4Wj-0)
Related PR https://github.com/mondaycom/vibe/pull/2574
Introduces new behaviour around the maxLength of the TextField component. A new `allowExceedingLimit` flag in combination with the `maxLength` field will give the user a visual marker that they have exceeded the limit without disabling typing in the input field.
The input will display an error state once the maxLength has been exceeded (while allowing it).

feat(TextField): improved maxLength with exceeding limit UI

---

packages/core/src/components/TextArea/TextArea.tsx
packages/core/src/components/TextArea/__tests__/TextArea.test.tsx

Follow up on https://github.com/mondaycom/vibe/pull/2574
Somewhere in the process of implementing the above PR the error state wasn't triggering anymore once the max length was exceeded (when it is allowed to do so).
Before:
After:
This PR fixes the conditional logic and uses the `characterCount`  state variable to more reliably check against the `maxLength` prop.

fix(TextArea): Error state not correctly set when maxlength is exceeded

---

packages/core/src/components/Search/Search.tsx
packages/core/src/components/Search/Search.types.ts
packages/core/src/components/Search/__tests__/Search.test.tsx

https://monday.monday.com/boards/3532714909/pulses/7890250116

feat(Search): allow tracking Enter key press

---

packages/core/src/components/Icon/Icons/components/TextSmall.tsx
packages/style/src/Icons/TextSmall.svg

https://monday.monday.com/boards/3532714909/views/80492480/pulses/7881682223

fix(TextSmall): fix icon

---

packages/core/src/components/Dropdown/Dropdown.tsx
packages/core/src/components/Dropdown/Dropdown.types.ts

In this PR, I added two properties to the React Select component:  
1. inputValue
2. blurInputOnSelect
These properties allow the user to edit their search term after they have already performed a search. Currently, when the input field gains focus, the latest search is cleared, and the user can only start a new search. With these two properties, the user will have the option to edit their existing search term.
Properties added:
1. inputValue: Controls the current value of the input field programmatically, allowing the user to modify their search term.
2. blurInputOnSelect: If true, the input field will lose focus when an option is selected, providing better control over the input behavior.
Resolves #

feat(Dropdown): add inputValue and blurInputOnSelect properties to allow editing options

---

.github/workflows/publish-v2-storybook.yml

https://monday.monday.com/boards/3532714909/pulses/8005465171

ci: fix v2 storybook publish action

---

packages/core/src/components/List/List.tsx
packages/core/src/components/List/__tests__/__snapshots__/List.test.js.snap
packages/core/src/components/List/utils/ListUtils.ts

https://monday.monday.com/boards/3532714909/views/80492480/pulses/8011242971?userId=59970142

fix(List): fix ListTitle getting focus on initialization

---

package.json

If we'd not ignore the built icons component we wouldn't need it (it takes about extra ~30s)
Worth re-considering keeping the icon components IMO
https://monday.monday.com/boards/3532714909/pulses/8030088094

chore: build icons after install for initial monorepo setup

---

packages/core/src/components/Tooltip/Tooltip.tsx

https://monday.monday.com/boards/3532714909/pulses/7980028465

feat(Tooltip): be able to change max width

---

packages/core/docs/vibe-3-changelog.md

https://monday.monday.com/boards/3532714909/pulses/8036574725

docs: replace style.monday to vibe.monday, fix broken links

---

packages/core/src/components/Dropdown/hooks/useHiddenOptionsData.js

https://monday.monday.com/boards/3532714909/pulses/8041715569
Explanation about the solution:
We had a few issues.
The `isCounterShown` dependency in the `useHiddenOptionsData` caused infinite loop, as two `useEffect`s were called infinitely.
It is in the dependency array as the Dropdown calculates what chips should be hidden.
But when calculated, the counter of "+X" chip at the end isn't shown (yet), so in some scenarios you could have pushed another chip to the width of the Dropdown (let's say 4 out of 5), but then when the counter appeared (to show "+1") as it should, the whole logic got messed up (cause chip number 4 did not had space anymore as the "+1" counter, which should now show "+2", caused it to be pushed out of boundaries), and we got caught up in an infinite loop.
I solved …

fix(Dropdown): when disabled chip has extra class

---

packages/core/src/components/Tipseen/Tipseen.tsx

Wrapping the element with a Tipseen wraps it in an empty span, which interferes with the CSS. Passing the missing property to the inner component ensures the correct styling is applied.
https://monday.monday.com/boards/5703104356/pulses/8039110583
**another** way to go would be to add a default class name here: https://github.com/stasshw/vibe/blob/24828d7f2ffec00084775f56322518cc04c9a2b8/packages/core/src/components/Dialog/Dialog.tsx#L519

feat(Tipseen): allow referenceWrapperClassName prop for component

---

packages/core/src/components/Dropdown/Dropdown.types.ts

https://monday.monday.com/boards/3532714909/views/80492480/pulses/8075255489

fix(Dropdown): fix menuRenderer type

---

packages/core/src/storybook/stand-alone-documentaion/colors/content-color-row/content-color-row.jsx

This pr resolves an issue where var name of the colors in the color foundation name was incorrect 
https://vibe.monday.com/?path=/docs/foundations-colors--colors
Resolves #2664

docs(colors): add color prefix to doc's content colors

---

packages/core/src/components/Tooltip/Tooltip.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/8078910437

feat(Tooltip): add dir prop

---

packages/core/src/components/Modal/Modal/Modal.module.scss
packages/core/src/components/Modal/Modal/Modal.tsx
packages/core/src/components/Modal/Modal/Modal.types.tsx

Since I don't have a shared parent I must pass it in a prop that would propagate its value to the style of both modal and overlay
https://monday.monday.com/boards/3532714909/pulses/8077838420

feat(Modal): allow passing z-index to overlay and modal

---

packages/core/src/components/Modal/layouts/ModalBasicLayout/ModalBasicLayout.tsx
packages/core/src/components/Modal/layouts/ModalLayoutScrollableContent.tsx
packages/core/src/components/Modal/layouts/useLayoutScrolledContent.ts

- Shadow should appear if content is scrollable (even if not scrolled)
- Shadow should disappear if content is scrolled to the end
- As we want to be responsive we should observe the resize to not cause a weird behavior
https://monday.monday.com/boards/3532714909/pulses/8075041798

fix(ModalBasicLayout): fix for logic of when to show modal footer shadow

---

packages/core/src/components/SlideTransition/SlideTransition.module.scss
packages/core/src/components/SlideTransition/SlideTransition.tsx
packages/core/src/components/SlideTransition/utils/animationVariants.ts
packages/core/src/components/TransitionView/TransitionView.module.scss
packages/core/src/components/TransitionView/TransitionView.tsx
packages/core/src/components/TransitionView/TransitionView.types.ts

Motion asked to make the sliding experience a bit better, and it is great news for us as we could have removed the ugly logic of absolute and calculating height, we can now keep the slide as part of the layout flow of the browser
https://monday.monday.com/boards/3532714909/pulses/8085577206

feat(TransitionView): remove previous slide before continuing to next slide, enhance animation

---

packages/core/src/components/Modal/Modal/__stories__/Modal.stories.helpers.tsx

it used to be intended to only have it on first render (when the docs page auto opens the Modal), but design asked it to be for all close and open of the Modal
https://monday.monday.com/boards/3532714909/pulses/8087422934

docs(Modal): remove scroll and autofocus even on second open of Modal

---

packages/core/src/components/List/List.tsx
packages/core/src/components/List/utils/ListUtils.ts

https://monday.monday.com/boards/3532714909/views/80492480/pulses/8099756862

fix(List): fix error when ListItem is not HTMLElement

---

packages/core/src/components/Dropdown/Dropdown.tsx

Same fix as the one we did for `react-windowed-select` and `react-inlinesvg`.

fix(Dropdown): Fix ESM - use .default if available

---

packages/core/src/components/Modal/layouts/ModalBasicLayout/__stories__/ModalBasicLayout.mdx
packages/core/src/components/Modal/layouts/ModalBasicLayout/__stories__/ModalBasicLayout.stories.tsx
packages/core/src/components/Modal/layouts/ModalMediaLayout/__stories__/ModalMediaLayout.mdx
packages/core/src/components/Modal/layouts/ModalMediaLayout/__stories__/ModalMediaLayout.stories.tsx
packages/core/src/components/Modal/layouts/ModalSideBySideLayout/__stories__/ModalSideBySideLayout.mdx
packages/core/src/components/Modal/layouts/ModalSideBySideLayout/__stories__/ModalSideBySideLayout.stories.helpers.tsx

- Confirmation modal story
- Announcement modal story
- General improvements and fixes to docs
https://monday.monday.com/boards/3532714909/pulses/8009612433

docs(Modal): general improvements and intent modals stories

---

packages/core/src/hooks/useIsOverflowing/useIsOverflowing.ts

https://monday.monday.com/boards/3532714909/pulses/8113296723

perf: remove redundant overflow style manipulation

---

packages/core/src/components/Modal/Modal/__stories__/Modal.mdx
packages/core/src/components/Modal/Modal/__stories__/Modal.stories.helpers.tsx
packages/core/src/components/Modal/Modal/__stories__/Modal.stories.module.scss
packages/core/src/components/Modal/hooks/usePortalTarget/usePortalTarget.ts
packages/core/src/components/Modal/layouts/ModalBasicLayout/__stories__/ModalBasicLayout.stories.tsx
packages/core/src/components/Modal/layouts/ModalMediaLayout/__stories__/ModalMediaLayout.stories.tsx
packages/core/src/components/Modal/layouts/ModalSideBySideLayout/__stories__/ModalSideBySideLayout.stories.tsx

- Add a11y section
- Every wizard story - last step primary button text should be "Confirm"
- General fixes and enhancements
- Add ability to open Overview stories in Full view mode
https://monday.monday.com/boards/3532714909/pulses/8074938556

docs(Modal): stories enhancements, add a11y section

---

packages/core/src/components/EditableText/__tests__/EditableText.test.tsx
packages/core/src/components/EditableTypography/EditableTypography.tsx

we should stop propagation as well, otherwise the parent (e.g. Modal or a container) gets it in the event bubbling phase
https://monday.monday.com/boards/3532714909/pulses/8138385588

fix(EditableTypography): Enter and Esc click to end edit mode is bubbling to other places afterwards

---

packages/core/src/components/Modal/Modal/Modal.tsx
packages/core/src/components/Modal/Modal/__tests__/Modal.test.tsx

https://monday.monday.com/boards/3532714909/pulses/8138566082

fix(Modal): RemoveScroll is overriding Modal's div's ref

---

packages/core/src/components/Modal/Modal/Modal.tsx
packages/core/src/components/Modal/Modal/Modal.types.tsx
packages/core/src/components/Modal/Modal/__tests__/Modal.test.tsx

it used to work in a way that the Esc is registered to the document body, so every Esc anywhere in the document closed ALL the modals
https://monday.monday.com/boards/3532714909/pulses/8136384041

fix(Modal): Esc should be scoped to the current top modal and not to close all modals

---

packages/core/src/components/Tooltip/Tooltip.module.scss

https://monday.monday.com/boards/3532714909/views/80492480/pulses/8138323310
Following this [pr](https://github.com/mondaycom/vibe/pull/2383), since the containerSelector is no longer `tooltips-container` which provided the `white-space: pre-wrap;` style, we need to add it directly to the component.

fix(tooltip): fix text with line breaks

---

packages/core/src/components/Modal/Modal/Modal.tsx
packages/core/src/components/Modal/Modal/Modal.types.tsx
packages/core/src/components/Modal/Modal/__tests__/Modal.test.tsx
packages/core/src/components/Modal/ModalHeader/ModalHeader.tsx
packages/core/src/components/Modal/ModalHeader/ModalHeader.types.ts
packages/core/src/components/Modal/ModalHeader/__tests__/ModalHeader.test.tsx

https://monday.monday.com/boards/3532714909/pulses/8129253861
https://monday.monday.com/boards/3532714909/pulses/8129247306

feat(Modal): allow accepting custom arias, allow passing ReactNode to ModalHeader's title

---

packages/core/src/components/EditableText/__stories__/EditableText.stories.tsx
packages/core/src/components/EditableTypography/EditableTypography.module.scss
packages/core/src/components/EditableTypography/EditableTypography.tsx

https://monday.monday.com/boards/3532714909/pulses/8162783724
https://monday.monday.com/boards/3532714909/pulses/8162188621

fix(EditableTypography): improve performance

---

packages/core/src/components/Modal/Modal/Modal.module.scss
packages/core/src/components/Modal/Modal/Modal.tsx

This is done to fix LayerProvider items are wrapped behind the modal's z-index.
and it seem to be a better practice to wrap the overlay and modal.
https://monday.monday.com/boards/3532714909/pulses/8165813476

feat(Modal): wrap the overlay and modal inside a container, to allow portaling with layer provider to the container

---

packages/core/src/components/Modal/Modal/Modal.module.scss

the previous commit caused `.modal` to have `(0, 2, 0)`, which caused it to override user-defined `className`.
it wasn't released yet though
https://monday.monday.com/boards/3532714909/pulses/8165813476

fix(Modal): avoid breaking changes due to specificity

---

packages/core/src/components/EditableHeading/__stories__/EditableHeading.mdx
packages/core/src/components/Heading/__stories__/Heading.mdx
packages/core/src/components/LegacyModal/__stories__/LegacyModal.mdx
packages/core/src/components/Modal/Modal/__stories__/Modal.mdx
packages/core/src/components/Modal/layouts/ModalBasicLayout/__stories__/ModalBasicLayout.mdx
packages/core/src/components/Modal/layouts/ModalMediaLayout/__stories__/ModalMediaLayout.mdx
packages/core/src/components/Modal/layouts/ModalSideBySideLayout/__stories__/ModalSideBySideLayout.mdx

https://monday.monday.com/boards/3532714909/pulses/8179134559

docs(Modal): add import sections to let consumers know where to consume from

---

packages/icons/README.md

https://monday.monday.com/boards/3532714909/pulses/8129522467

docs(icons): Added @vibe/icons/meta to readme

---

packages/core/src/components/Slider/Slider.tsx
packages/core/src/components/Slider/Slider.types.ts
packages/core/src/components/Slider/SliderBase/SliderThumb.module.scss
packages/core/src/components/Slider/SliderBase/SliderThumb.tsx
packages/core/src/components/Slider/SliderConstants.ts
packages/core/src/components/Slider/SliderContext.tsx
packages/core/src/components/Slider/__tests__/__snapshots__/Slider-non-ranged.test.js.snap
packages/core/src/components/Slider/__tests__/__snapshots__/Slider-ranged.test.js.snap
packages/core/src/components/Slider/__tests__/__snapshots__/Slider.snapshot.test.js.snap

https://monday.monday.com/boards/3532714909/pulses/8223729904

feat(Slider): be able to change value label position and color

---

packages/core/src/components/Avatar/Avatar.module.scss
packages/core/src/components/Avatar/Avatar.types.ts
packages/core/src/components/Avatar/AvatarBadge.module.scss
packages/core/src/components/Avatar/AvatarConstants.scss
packages/core/src/components/Avatar/AvatarConstants.tsx
packages/core/src/components/Avatar/AvatarContent.module.scss
packages/core/src/components/Avatar/__stories__/Avatar.mdx
packages/core/src/components/Avatar/__stories__/Avatar.stories.scss
packages/core/src/components/Avatar/__stories__/Avatar.stories.tsx
packages/core/src/components/AvatarGroup/AvatarGroupCounter.module.scss
packages/core/src/components/AvatarGroup/AvatarGroupCounter.tsx
packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.mdx
packages/core/src/components/AvatarGroup/__stories__/AvatarGroup.stories.tsx
packages/core/src/components/AvatarGroup/__tests__/AvatarGroup.snapshot.test.js
packages/core/src/components/AvatarGroup/__tests__/__snapshots__/AvatarGroup.snapshot.test.js.snap
packages/core/src/components/Counter/Counter.module.scss
packages/core/src/components/Counter/Counter.types.ts
packages/core/src/components/Counter/CounterConstants.ts
packages/core/src/components/Counter/__stories__/Counter.mdx
packages/core/src/components/Counter/__stories__/Counter.stories.tsx

https://monday.monday.com/boards/3532714909/pulses/8246320271

feat(Avatar): add xs size

---

packages/core/src/components/Dialog/Dialog.tsx
packages/core/src/components/Dialog/modifiers/observeContentResizeModifier.ts
packages/core/src/components/Menu/MenuItem/MenuItem.tsx
packages/core/src/components/Menu/MenuItem/components/BaseMenuItem/BaseMenuItem.tsx
packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/MenuItemSubMenu.tsx
packages/core/src/components/Menu/MenuItem/components/MenuItemSubMenu/MenuItemSubMenu.types.ts
packages/core/src/hooks/usePopover.ts

https://monday.monday.com/boards/3532714909/pulses/8222833258
Before:
After:

feat(MenuItem): allow observing submenu content resize when a re-render isn't triggered

---

packages/core/src/components/ButtonGroup/ButtonGroup.tsx

Add blurOnMouseUp to button-group component.
Today we have a control over blurOnMouseUp only for button component- but in button-group it is always `true`. the option to disable it is required for certain use cases

feat(ButtonGroup): add blurOnMouseUp to ButtonGroup

---

packages/core/src/components/Combobox/Combobox.tsx
packages/core/src/components/Combobox/components/StickyCategoryHeader/StickyCategoryHeader.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/8451157596
Currently the sticky header has a background color, in order to change it we need to add a className

feat(Combobox): add className for sticky header

---

packages/core/src/components/ColorPicker/ColorPicker.tsx
packages/core/src/components/ColorPicker/__tests__/ColorPicker.test.tsx
packages/core/src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
packages/core/src/storybook/stand-alone-documentaion/playground/react-docgen-output.json

make forceUseRawColorList and showColorNameTooltip compatible
Resolves #

fix(ColorPicker): make forceUseRawColorList and showColorNameTooltip compatible

---

packages/core/src/components/Menu/MenuItem/components/BaseMenuItem/BaseMenuItem.tsx

This causes a weird behavior of showing two tooltips, one with icon and one without, and the menu items to be uninteractable
https://monday.monday.com/boards/3532714909/pulses/8775344190

fix(MenuItem): remove 2nd tooltip (already has tooltip on the MenuItem wrapper)

---

packages/core/src/components/Tipseen/Tipseen.tsx

The Tipseen component was experiencing a "double delay" issue where the content would take twice the specified showDelay time to become interactive. This was caused by both the Tipseen component and the underlying Tooltip component applying the same delay.
This fix passes a showDelay of 0 to the Tooltip while maintaining the original delay logic in the Tipseen component, ensuring the content appears and becomes interactive after exactly the specified delay time.
https://monday.monday.com/boards/3532714909/pulses/8301809774

fix(Tipseen): prevent double delay when using showDelay

---

packages/core/.storybook/main.ts
packages/core/src/types/withStaticProps.ts

https://monday.monday.com/boards/3532714909/pulses/8988817874
Also:
Switched to use react-docgen-typescript in our Storybook default docgen. Check Storybook docs:
<https://storybook.js.org/docs/api/main-config/main-config-typescript#reactdocgen>
> react-docgen-typescript invokes the TypeScript compiler, which makes it slow but generally accurate. react-docgen performs its own analysis, which is much faster but incomplete.

fix(docs): docgen can't handle ComponentType

---

packages/core/src/components/MenuButton/MenuButton.tsx

Fixing menu button tab action
https://github.com/user-attachments/assets/1b11866c-bb4d-4e69-b674-797e8d4d0560
The issue is that onDialogDidHide is called when the menu is closed, returning the focus to the menu button when tabbing to the next element. Checking if the menu is open allows tabbing to the next element

fix(MenuButton): fix tab focus when menu is closing

---

packages/core/src/components/ColorPicker/__tests__/__snapshots__/ColorPicker.test.tsx.snap
packages/core/src/components/ColorPicker/components/ColorPickerContent/ColorPickerColorsGrid.tsx
packages/core/src/components/ColorPicker/components/ColorPickerContent/ColorPickerContent.tsx
packages/core/src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.ts

As for today - there's no way to tab into ColorPickerContent
- Introduced `enableGridTabNavigation` prop in `ColorPickerColorsGrid` for focusable grid elements.
- Updated `ColorPickerContent` to accept `enableTabNavigation` prop for enabling keyboard navigation.
- Enhanced `useGridKeyboardNavigation` hook to support entry focus strategy for keyboard navigation.
https://monday.monday.com/boards/8350127532/pulses/8433955776

fix(ColorPickerContent): add keyboard tab navigation support to ColorPickerContent's grid

---

packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx

Addresses performance issues in TableVirtualizedBody, particularly noticeable during fast scrolling with many columns or complex cell content. This often resulted in excessive re-renders, blank spaces appearing, and compatibility problems with sticky columns.
Changes:
- Internal Row Memoization: Implements React.memo internally for rendered rows. This significantly reduces unnecessary re-renders when scrolling, as rows only update if their data changes, not just their position.
Before
After
- Configurable Overscanning: Adds an optional overscanCount prop (defaulting to 1). Consumers can increase this value to render more rows outside the viewport, potentially smoothing out fast scrolls at the cost of rendering more items.

fix(Table): Memoized row for optimized row rendering

---

packages/core/src/storybook/components/live-preview/LivePreview.module.scss
packages/core/src/storybook/components/live-preview/LivePreview.tsx

How it looks now:
It helps avoid "jumping" in the page when editing. it always remember the last known valid code.
https://monday.monday.com/boards/3532714909/pulses/6495484558

docs(LiveEdit): remember last known valid code for better DX

---

packages/core/src/components/Table/TableContainer/TableContainer.module.scss
packages/core/src/components/Table/TableRowMenu/TableRowMenu.tsx
packages/core/src/components/Table/context/TableRowMenuContext/TableRowMenuContext.tsx

this was changed because on some scenarios, when moving from menu button to row and back, the menu disappeared - especially in edge cases involving rapid mouse movement
https://monday.monday.com/boards/3532714909/pulses/9173208813
- **Removed all setTimeouts** for hover state transitions between row and menu.
- Hover state (`hoveredRowRef`) is now updated immediately on mouse events, resulting in a more responsive and predictable UI.
- The code now uses a simple `isMenuHovered` ref to track when the mouse is over the menu, ensuring the menu remains visible when moving between row and menu.
- `onMouseOverRow` and `onMouseOverRowMenu` now always immediately set the hover state and cancel any pending state clears.
- `onMouseLeaveRow` and `onMouseLeaveRowMenu` immediately clear the hover …

fix(Table): make row hover state immediate, robust and more reliable

---

packages/mcp/README.md

Cursor now supports deeplinks:
https://docs.cursor.com/deeplinks#markdown
https://monday.monday.com/boards/3532714909/pulses/9308682782

docs: add a quick-add deeplink button for Add to Cursor

---

packages/core/src/components/Table/Table/__tests__/Table.test.tsx
packages/core/src/components/Table/TableVirtualizedBody/TableVirtualizedBody.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/9629012734
___
Bug fix
___
- Fix loading state handling in virtualized table components
- Ensure header renders correctly during loading state
- Add comprehensive test coverage for virtualized table loading
___
```mermaid
flowchart LR
A["TableVirtualizedBody"] --> B["Extract dataState from useTable"]
B --> C["Check isLoading state"]
C --> D["Render header separately when loading"]
D --> E["Return early with header + TableBody"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>Table.test.tsx</strong><dd><code>Add virtualized table loading state …

fix(Table): fix loading state handling in TableVirtualizedBody

---

packages/style/package.json

https://monday.monday.com/boards/3532714909/pulses/9651727237
___
Other
___
- Move PostCSS and Stylelint dependencies from devDependencies to dependencies
- Ensure proper runtime availability of styling tools
___
```mermaid
flowchart LR
devDeps["devDependencies"] -- "move" --> deps["dependencies"]
deps --> postcss["postcss"]
deps --> stylelint["stylelint"]
deps --> postcssScss["postcss-scss"]
deps --> postcssParser["postcss-value-parser"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Restructure package dependencies classification</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix: add missing deps

---

packages/core/src/components/DatePicker/DatePicker.tsx
packages/core/src/components/DatePicker/__tests__/DatePicker.test.tsx

https://monday.monday.com/boards/3532714909/pulses/6381326498
___
Bug fix
___
- Add default NOOP value for `onPickDate` prop
- Prevent crashes when callback not provided
- Add tests for both single and range modes
___
```mermaid
flowchart LR
A["DatePicker Component"] --> B["onPickDate prop"]
B --> C["Default NOOP value"]
C --> D["No crash on click"]
E["Test Coverage"] --> F["Single mode test"]
E --> G["Range mode test"]
```
<tr>
<td>
<details>
<summary><strong>DatePicker.tsx</strong><dd><code>Add default callback to prevent crashes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix(DatePicker): add default value for onPickDate prop

---

packages/core/src/hooks/useFullKeyboardListeners.ts
packages/core/src/hooks/useGridKeyboardNavigation/useGridKeyboardNavigation.ts

https://monday.monday.com/boards/3532714909/views/80492480/pulses/9678436288
Enhancement
___
- Add Home and End key navigation support to keyboard listeners
- Implement first/last enabled item navigation in grid components
- Extend useFullKeyboardListeners hook with new key handlers
___
```mermaid
flowchart LR
A["useFullKeyboardListeners"] -- "adds onHome/onEnd callbacks" --> B["useGridKeyboardNavigation"]
B -- "implements navigation logic" --> C["First/Last Item Navigation"]
A -- "listens for HOME_KEYS/END_KEYS" --> D["Key Event Handlers"]
```
<tr>
<td>
<details> …

feat(Tabs): add support for Home and End key navigation

---

packages/core/src/components/Label/Label.tsx

https://monday.monday.com/boards/3532714909/pulses/9783626373
___
Bug fix
___
- Fix line kind styling when using content colors
- Apply text color instead of background color for line labels
___
```mermaid
flowchart LR
A["Content Color Check"] --> B["Kind Check Added"]
B --> C["Line Kind: Text Color"]
B --> D["Other Kinds: Background Color"]
```
<tr>
<td>
<details>
<summary><strong>Label.tsx</strong><dd><code>Fix line kind content color styling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix(Label): fix line kind when using content colors

---

packages/core/src/components/Link/Link.tsx

https://monday.monday.com/boards/3532714909/pulses/9854959969
___
Enhancement
___
- Add `style` prop to Link component for inline styling
- Enable custom CSS properties on link elements
___
```mermaid
flowchart LR
A["Link Component"] --> B["Add style prop"]
B --> C["Apply inline styles"]
C --> D["Enhanced customization"]
```
<tr>
<td>
<details>
<summary><strong>Link.tsx</strong><dd><code>Add style prop for inline styling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat(Link): add `style` prop for inline styling

---

packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/9890899920
___
Bug fix
___
- Update dropdown active state to include `isOpen` condition
- Fix visual state for non-searchable dropdowns when opened
___
```mermaid
flowchart LR
A["DropdownBase Component"] --> B["Extract isOpen from context"]
B --> C["Update active state logic"]
C --> D["Apply active styles when focused OR open"]
```
<tr>
<td>
<details>
<summary><strong>DropdownBase.tsx</strong><dd><code>Update active state logic for dropdown styling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

fix(DropdownBase): update active state to include isOpen condition

---

packages/core/src/components/DropdownNew/Dropdown.types.ts
packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.module.scss
packages/core/src/components/DropdownNew/components/DropdownBase/DropdownBase.tsx
packages/core/src/components/DropdownNew/components/Trigger/Trigger.module.scss
packages/core/src/components/DropdownNew/modes/DropdownComboboxController.tsx
packages/core/src/components/DropdownNew/modes/DropdownMultiComboboxController.tsx
packages/core/src/components/DropdownNew/modes/DropdownMultiSelectController.tsx
packages/core/src/components/DropdownNew/modes/DropdownSelectController.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/9898647435
___
Bug fix, Enhancement
___
- Fix dropdown height sizing for all size variants
- Update onBlur callback to pass focus event parameter
- Add focus state styling and outline management
- Implement focus tracking in select controllers
___
```mermaid
flowchart LR
A["Dropdown Types"] --> B["onBlur Event Fix"]
C["SCSS Styling"] --> D["Height Adjustments"]
C --> E["Focus State Styling"]
F["Controllers"] --> G["Focus Tracking"]
F --> H["Event Handling"]
```
<tr>
<td>
<details>
<summary><strong>Dropdown.types.ts</strong><dd><code>Update …

fix(Dropdown):  fix size and focus

---

packages/core/src/types/Colors.ts

https://monday.monday.com/boards/3532714909/pulses/9857616053
___
Bug fix
___
- Add missing warning color hover state mapping
___
```mermaid
flowchart LR
A["MapStateSelectedHoverColor"] --> B["Add warning hover state"]
B --> C["Complete color state mapping"]
```
<tr>
<td>
<details>
<summary><strong>Colors.ts</strong><dd><code>Add warning color hover state mapping</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/core/src/types/Colors.ts
<ul><li>Add missing <code>warning: …

fix(Chips): warning color missing hover state

---

.github/workflows/prerelease.yml

https://monday.monday.com/boards/3532714909/pulses/9960526846
___
Enhancement
___
- Add conditional checks to prevent PR comment failures
- Only prepare and create PR comments when PR exists
- Remove unnecessary quotes from workflow condition
___
```mermaid
flowchart LR
A["Push to branch"] --> B["Check for [prerelease] tag"]
B --> C["Build and publish"]
C --> D["Get PR info"]
D --> E{"PR found?"}
E -->|Yes| F["Prepare comment"]
E -->|No| G["Skip comment steps"]
F --> H["Create PR comment"]
```
<tr>
<td>
<details>
<summary><strong>prerelease.yml</strong><dd><code>Add PR existence checks to workflow …

ci: do not fail pre-release if not running with a PR open

---

packages/core/src/components/Chips/Chips.tsx
packages/core/src/components/RadioButton/RadioButton.tsx

https://monday.monday.com/boards/3532714909/views/80492480/pulses/10070825910
___
Enhancement
___
- Add accessibility props to RadioButton component
- Support ariaLabel and ariaDescribedby attributes
___
```mermaid
flowchart LR
A["RadioButton Props"] --> B["Add ariaLabel prop"]
A --> C["Add ariaDescribedby prop"]
B --> D["Apply to input element"]
C --> D
```
<tr>
<td>
<details>
<summary><strong>RadioButton.tsx</strong><dd><code>Add accessibility ARIA props support</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

feat(RadioButton): add ariaLabel & ariaDescribedBy

---

packages/core/src/components/DropdownNew/hooks/useDropdownCombobox.ts
packages/core/src/components/DropdownNew/hooks/useDropdownMultiCombobox.ts

https://monday.monday.com/boards/3532714909/views/80492480/pulses/10069205016?userId=59970142
___
Bug fix
___
- Change `onInputChange` callback to return `null` instead of empty string
- Update type signature to accept `string | null` parameter
- Modify state reducer to use `null` for cleared input values
___
```mermaid
flowchart LR
A["onInputChange callback"] --> B["Type signature updated"]
B --> C["Return null instead of empty string"]
C --> D["State reducer updated"]
```
<tr>
<td>
<details>
<summary><strong>useDropdownCombobox.ts</strong><dd><code>Update combobox to use null for cleared …

fix(DropdownNew): onInputChange return null instead of empty string

---

packages/core/package.json
packages/core/src/components/Dropdown/Dropdown.tsx
yarn.lock

Reverts mondaycom/vibe#3116
___
Bug fix
___
- Revert Dropdown component to use default Select import
- Fix react-select version to 3.2.6 from 3.3.0
___
```mermaid
flowchart LR
A["Dropdown component"] -- "revert import" --> B["Default Select import"]
C["react-select 3.3.0"] -- "downgrade" --> D["react-select 3.2.6"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Downgrade react-select dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
packages/core/package.json
- Change …

fix: Revert Dropdown use Select component as named export
